// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: users/roles/menu.proto

package menu

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MenuService_MenuA_FullMethodName = "/roles.menu.MenuService/MenuA"
	MenuService_MenuU_FullMethodName = "/roles.menu.MenuService/MenuU"
	MenuService_MenuD_FullMethodName = "/roles.menu.MenuService/MenuD"
	MenuService_MenuQ_FullMethodName = "/roles.menu.MenuService/MenuQ"
)

// MenuServiceClient is the client API for MenuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MenuServiceClient interface {
	MenuA(ctx context.Context, in *MenuARequest, opts ...grpc.CallOption) (*Response, error)
	MenuU(ctx context.Context, in *MenuURequest, opts ...grpc.CallOption) (*Response, error)
	MenuD(ctx context.Context, in *MenuDRequest, opts ...grpc.CallOption) (*Response, error)
	MenuQ(ctx context.Context, in *MenuQRequest, opts ...grpc.CallOption) (*Response, error)
}

type menuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMenuServiceClient(cc grpc.ClientConnInterface) MenuServiceClient {
	return &menuServiceClient{cc}
}

func (c *menuServiceClient) MenuA(ctx context.Context, in *MenuARequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, MenuService_MenuA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) MenuU(ctx context.Context, in *MenuURequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, MenuService_MenuU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) MenuD(ctx context.Context, in *MenuDRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, MenuService_MenuD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) MenuQ(ctx context.Context, in *MenuQRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, MenuService_MenuQ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MenuServiceServer is the server API for MenuService service.
// All implementations must embed UnimplementedMenuServiceServer
// for forward compatibility.
type MenuServiceServer interface {
	MenuA(context.Context, *MenuARequest) (*Response, error)
	MenuU(context.Context, *MenuURequest) (*Response, error)
	MenuD(context.Context, *MenuDRequest) (*Response, error)
	MenuQ(context.Context, *MenuQRequest) (*Response, error)
	mustEmbedUnimplementedMenuServiceServer()
}

// UnimplementedMenuServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMenuServiceServer struct{}

func (UnimplementedMenuServiceServer) MenuA(context.Context, *MenuARequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method MenuA not implemented")
}
func (UnimplementedMenuServiceServer) MenuU(context.Context, *MenuURequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method MenuU not implemented")
}
func (UnimplementedMenuServiceServer) MenuD(context.Context, *MenuDRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method MenuD not implemented")
}
func (UnimplementedMenuServiceServer) MenuQ(context.Context, *MenuQRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method MenuQ not implemented")
}
func (UnimplementedMenuServiceServer) mustEmbedUnimplementedMenuServiceServer() {}
func (UnimplementedMenuServiceServer) testEmbeddedByValue()                     {}

// UnsafeMenuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MenuServiceServer will
// result in compilation errors.
type UnsafeMenuServiceServer interface {
	mustEmbedUnimplementedMenuServiceServer()
}

func RegisterMenuServiceServer(s grpc.ServiceRegistrar, srv MenuServiceServer) {
	// If the following call panics, it indicates UnimplementedMenuServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MenuService_ServiceDesc, srv)
}

func _MenuService_MenuA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).MenuA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_MenuA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).MenuA(ctx, req.(*MenuARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_MenuU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).MenuU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_MenuU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).MenuU(ctx, req.(*MenuURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_MenuD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).MenuD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_MenuD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).MenuD(ctx, req.(*MenuDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_MenuQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).MenuQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_MenuQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).MenuQ(ctx, req.(*MenuQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MenuService_ServiceDesc is the grpc.ServiceDesc for MenuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MenuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "roles.menu.MenuService",
	HandlerType: (*MenuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MenuA",
			Handler:    _MenuService_MenuA_Handler,
		},
		{
			MethodName: "MenuU",
			Handler:    _MenuService_MenuU_Handler,
		},
		{
			MethodName: "MenuD",
			Handler:    _MenuService_MenuD_Handler,
		},
		{
			MethodName: "MenuQ",
			Handler:    _MenuService_MenuQ_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users/roles/menu.proto",
}
