// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: users/technique/tbl_grp_item.proto

package tbl_grp_item

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TblGrpItemAResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdxNo         int32                  `protobuf:"varint,1,opt,name=IdxNo,proto3" json:"IdxNo,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,2,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,3,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	KeyCode       string                 `protobuf:"bytes,4,opt,name=KeyCode,proto3" json:"KeyCode,omitempty"`
	TblGrpSeq     string                 `protobuf:"bytes,5,opt,name=TblGrpSeq,proto3" json:"TblGrpSeq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TblGrpItemAResult) Reset() {
	*x = TblGrpItemAResult{}
	mi := &file_users_technique_tbl_grp_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TblGrpItemAResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TblGrpItemAResult) ProtoMessage() {}

func (x *TblGrpItemAResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_technique_tbl_grp_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TblGrpItemAResult.ProtoReflect.Descriptor instead.
func (*TblGrpItemAResult) Descriptor() ([]byte, []int) {
	return file_users_technique_tbl_grp_item_proto_rawDescGZIP(), []int{0}
}

func (x *TblGrpItemAResult) GetIdxNo() int32 {
	if x != nil {
		return x.IdxNo
	}
	return 0
}

func (x *TblGrpItemAResult) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *TblGrpItemAResult) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *TblGrpItemAResult) GetKeyCode() string {
	if x != nil {
		return x.KeyCode
	}
	return ""
}

func (x *TblGrpItemAResult) GetTblGrpSeq() string {
	if x != nil {
		return x.TblGrpSeq
	}
	return ""
}

type TblGrpItemUResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdxNo         int32                  `protobuf:"varint,1,opt,name=IdxNo,proto3" json:"IdxNo,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,2,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	KeyCode       string                 `protobuf:"bytes,3,opt,name=KeyCode,proto3" json:"KeyCode,omitempty"`
	IdSeq         string                 `protobuf:"bytes,4,opt,name=IdSeq,proto3" json:"IdSeq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TblGrpItemUResult) Reset() {
	*x = TblGrpItemUResult{}
	mi := &file_users_technique_tbl_grp_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TblGrpItemUResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TblGrpItemUResult) ProtoMessage() {}

func (x *TblGrpItemUResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_technique_tbl_grp_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TblGrpItemUResult.ProtoReflect.Descriptor instead.
func (*TblGrpItemUResult) Descriptor() ([]byte, []int) {
	return file_users_technique_tbl_grp_item_proto_rawDescGZIP(), []int{1}
}

func (x *TblGrpItemUResult) GetIdxNo() int32 {
	if x != nil {
		return x.IdxNo
	}
	return 0
}

func (x *TblGrpItemUResult) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *TblGrpItemUResult) GetKeyCode() string {
	if x != nil {
		return x.KeyCode
	}
	return ""
}

func (x *TblGrpItemUResult) GetIdSeq() string {
	if x != nil {
		return x.IdSeq
	}
	return ""
}

type TblGrpItemDResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdxNo         int32                  `protobuf:"varint,1,opt,name=IdxNo,proto3" json:"IdxNo,omitempty"`
	IdSeq         string                 `protobuf:"bytes,2,opt,name=IdSeq,proto3" json:"IdSeq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TblGrpItemDResult) Reset() {
	*x = TblGrpItemDResult{}
	mi := &file_users_technique_tbl_grp_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TblGrpItemDResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TblGrpItemDResult) ProtoMessage() {}

func (x *TblGrpItemDResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_technique_tbl_grp_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TblGrpItemDResult.ProtoReflect.Descriptor instead.
func (*TblGrpItemDResult) Descriptor() ([]byte, []int) {
	return file_users_technique_tbl_grp_item_proto_rawDescGZIP(), []int{2}
}

func (x *TblGrpItemDResult) GetIdxNo() int32 {
	if x != nil {
		return x.IdxNo
	}
	return 0
}

func (x *TblGrpItemDResult) GetIdSeq() string {
	if x != nil {
		return x.IdSeq
	}
	return ""
}

type TblGrpItemQResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyItem1      string                 `protobuf:"bytes,1,opt,name=KeyItem1,proto3" json:"KeyItem1,omitempty"`
	KeyItem2      string                 `protobuf:"bytes,2,opt,name=KeyItem2,proto3" json:"KeyItem2,omitempty"`
	KeyItem3      string                 `protobuf:"bytes,3,opt,name=KeyItem3,proto3" json:"KeyItem3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TblGrpItemQResult) Reset() {
	*x = TblGrpItemQResult{}
	mi := &file_users_technique_tbl_grp_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TblGrpItemQResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TblGrpItemQResult) ProtoMessage() {}

func (x *TblGrpItemQResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_technique_tbl_grp_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TblGrpItemQResult.ProtoReflect.Descriptor instead.
func (*TblGrpItemQResult) Descriptor() ([]byte, []int) {
	return file_users_technique_tbl_grp_item_proto_rawDescGZIP(), []int{3}
}

func (x *TblGrpItemQResult) GetKeyItem1() string {
	if x != nil {
		return x.KeyItem1
	}
	return ""
}

func (x *TblGrpItemQResult) GetKeyItem2() string {
	if x != nil {
		return x.KeyItem2
	}
	return ""
}

func (x *TblGrpItemQResult) GetKeyItem3() string {
	if x != nil {
		return x.KeyItem3
	}
	return ""
}

type TblGrpItemARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*TblGrpItemAResult   `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TblGrpItemARequest) Reset() {
	*x = TblGrpItemARequest{}
	mi := &file_users_technique_tbl_grp_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TblGrpItemARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TblGrpItemARequest) ProtoMessage() {}

func (x *TblGrpItemARequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_technique_tbl_grp_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TblGrpItemARequest.ProtoReflect.Descriptor instead.
func (*TblGrpItemARequest) Descriptor() ([]byte, []int) {
	return file_users_technique_tbl_grp_item_proto_rawDescGZIP(), []int{4}
}

func (x *TblGrpItemARequest) GetResult() []*TblGrpItemAResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TblGrpItemARequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TblGrpItemURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*TblGrpItemUResult   `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TblGrpItemURequest) Reset() {
	*x = TblGrpItemURequest{}
	mi := &file_users_technique_tbl_grp_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TblGrpItemURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TblGrpItemURequest) ProtoMessage() {}

func (x *TblGrpItemURequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_technique_tbl_grp_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TblGrpItemURequest.ProtoReflect.Descriptor instead.
func (*TblGrpItemURequest) Descriptor() ([]byte, []int) {
	return file_users_technique_tbl_grp_item_proto_rawDescGZIP(), []int{5}
}

func (x *TblGrpItemURequest) GetResult() []*TblGrpItemUResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TblGrpItemURequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TblGrpItemDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*TblGrpItemDResult   `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TblGrpItemDRequest) Reset() {
	*x = TblGrpItemDRequest{}
	mi := &file_users_technique_tbl_grp_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TblGrpItemDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TblGrpItemDRequest) ProtoMessage() {}

func (x *TblGrpItemDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_technique_tbl_grp_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TblGrpItemDRequest.ProtoReflect.Descriptor instead.
func (*TblGrpItemDRequest) Descriptor() ([]byte, []int) {
	return file_users_technique_tbl_grp_item_proto_rawDescGZIP(), []int{6}
}

func (x *TblGrpItemDRequest) GetResult() []*TblGrpItemDResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TblGrpItemDRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TblGrpItemQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *TblGrpItemQResult     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TblGrpItemQRequest) Reset() {
	*x = TblGrpItemQRequest{}
	mi := &file_users_technique_tbl_grp_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TblGrpItemQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TblGrpItemQRequest) ProtoMessage() {}

func (x *TblGrpItemQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_technique_tbl_grp_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TblGrpItemQRequest.ProtoReflect.Descriptor instead.
func (*TblGrpItemQRequest) Descriptor() ([]byte, []int) {
	return file_users_technique_tbl_grp_item_proto_rawDescGZIP(), []int{7}
}

func (x *TblGrpItemQRequest) GetResult() *TblGrpItemQResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TblGrpItemQRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Page          string                 `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_users_technique_tbl_grp_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_users_technique_tbl_grp_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_users_technique_tbl_grp_item_proto_rawDescGZIP(), []int{8}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Response) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

var File_users_technique_tbl_grp_item_proto protoreflect.FileDescriptor

const file_users_technique_tbl_grp_item_proto_rawDesc = "" +
	"\n" +
	"\"users/technique/tbl_grp_item.proto\x12\x1cusers.technique.tbl_grp_item\"\x9d\x01\n" +
	"\x11TblGrpItemAResult\x12\x14\n" +
	"\x05IdxNo\x18\x01 \x01(\x05R\x05IdxNo\x12\x1c\n" +
	"\tCreatedBy\x18\x02 \x01(\tR\tCreatedBy\x12\x1c\n" +
	"\tUpdatedBy\x18\x03 \x01(\tR\tUpdatedBy\x12\x18\n" +
	"\aKeyCode\x18\x04 \x01(\tR\aKeyCode\x12\x1c\n" +
	"\tTblGrpSeq\x18\x05 \x01(\tR\tTblGrpSeq\"w\n" +
	"\x11TblGrpItemUResult\x12\x14\n" +
	"\x05IdxNo\x18\x01 \x01(\x05R\x05IdxNo\x12\x1c\n" +
	"\tUpdatedBy\x18\x02 \x01(\tR\tUpdatedBy\x12\x18\n" +
	"\aKeyCode\x18\x03 \x01(\tR\aKeyCode\x12\x14\n" +
	"\x05IdSeq\x18\x04 \x01(\tR\x05IdSeq\"?\n" +
	"\x11TblGrpItemDResult\x12\x14\n" +
	"\x05IdxNo\x18\x01 \x01(\x05R\x05IdxNo\x12\x14\n" +
	"\x05IdSeq\x18\x02 \x01(\tR\x05IdSeq\"g\n" +
	"\x11TblGrpItemQResult\x12\x1a\n" +
	"\bKeyItem1\x18\x01 \x01(\tR\bKeyItem1\x12\x1a\n" +
	"\bKeyItem2\x18\x02 \x01(\tR\bKeyItem2\x12\x1a\n" +
	"\bKeyItem3\x18\x03 \x01(\tR\bKeyItem3\"\xf6\x01\n" +
	"\x12TblGrpItemARequest\x12G\n" +
	"\x06result\x18\x01 \x03(\v2/.users.technique.tbl_grp_item.TblGrpItemAResultR\x06result\x12Z\n" +
	"\bmetadata\x18\x02 \x03(\v2>.users.technique.tbl_grp_item.TblGrpItemARequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf6\x01\n" +
	"\x12TblGrpItemURequest\x12G\n" +
	"\x06result\x18\x01 \x03(\v2/.users.technique.tbl_grp_item.TblGrpItemUResultR\x06result\x12Z\n" +
	"\bmetadata\x18\x02 \x03(\v2>.users.technique.tbl_grp_item.TblGrpItemURequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf6\x01\n" +
	"\x12TblGrpItemDRequest\x12G\n" +
	"\x06result\x18\x01 \x03(\v2/.users.technique.tbl_grp_item.TblGrpItemDResultR\x06result\x12Z\n" +
	"\bmetadata\x18\x02 \x03(\v2>.users.technique.tbl_grp_item.TblGrpItemDRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf6\x01\n" +
	"\x12TblGrpItemQRequest\x12G\n" +
	"\x06result\x18\x01 \x01(\v2/.users.technique.tbl_grp_item.TblGrpItemQResultR\x06result\x12Z\n" +
	"\bmetadata\x18\x02 \x03(\v2>.users.technique.tbl_grp_item.TblGrpItemQRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x12\n" +
	"\x04page\x18\x04 \x01(\tR\x04page2\xb7\x03\n" +
	"\x11TblGrpItemService\x12g\n" +
	"\vTblGrpItemA\x120.users.technique.tbl_grp_item.TblGrpItemARequest\x1a&.users.technique.tbl_grp_item.Response\x12g\n" +
	"\vTblGrpItemU\x120.users.technique.tbl_grp_item.TblGrpItemURequest\x1a&.users.technique.tbl_grp_item.Response\x12g\n" +
	"\vTblGrpItemD\x120.users.technique.tbl_grp_item.TblGrpItemDRequest\x1a&.users.technique.tbl_grp_item.Response\x12g\n" +
	"\vTblGrpItemQ\x120.users.technique.tbl_grp_item.TblGrpItemQRequest\x1a&.users.technique.tbl_grp_item.ResponseB0Z.server-core/proto/users/technique/tbl_grp_itemb\x06proto3"

var (
	file_users_technique_tbl_grp_item_proto_rawDescOnce sync.Once
	file_users_technique_tbl_grp_item_proto_rawDescData []byte
)

func file_users_technique_tbl_grp_item_proto_rawDescGZIP() []byte {
	file_users_technique_tbl_grp_item_proto_rawDescOnce.Do(func() {
		file_users_technique_tbl_grp_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_technique_tbl_grp_item_proto_rawDesc), len(file_users_technique_tbl_grp_item_proto_rawDesc)))
	})
	return file_users_technique_tbl_grp_item_proto_rawDescData
}

var file_users_technique_tbl_grp_item_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_users_technique_tbl_grp_item_proto_goTypes = []any{
	(*TblGrpItemAResult)(nil),  // 0: users.technique.tbl_grp_item.TblGrpItemAResult
	(*TblGrpItemUResult)(nil),  // 1: users.technique.tbl_grp_item.TblGrpItemUResult
	(*TblGrpItemDResult)(nil),  // 2: users.technique.tbl_grp_item.TblGrpItemDResult
	(*TblGrpItemQResult)(nil),  // 3: users.technique.tbl_grp_item.TblGrpItemQResult
	(*TblGrpItemARequest)(nil), // 4: users.technique.tbl_grp_item.TblGrpItemARequest
	(*TblGrpItemURequest)(nil), // 5: users.technique.tbl_grp_item.TblGrpItemURequest
	(*TblGrpItemDRequest)(nil), // 6: users.technique.tbl_grp_item.TblGrpItemDRequest
	(*TblGrpItemQRequest)(nil), // 7: users.technique.tbl_grp_item.TblGrpItemQRequest
	(*Response)(nil),           // 8: users.technique.tbl_grp_item.Response
	nil,                        // 9: users.technique.tbl_grp_item.TblGrpItemARequest.MetadataEntry
	nil,                        // 10: users.technique.tbl_grp_item.TblGrpItemURequest.MetadataEntry
	nil,                        // 11: users.technique.tbl_grp_item.TblGrpItemDRequest.MetadataEntry
	nil,                        // 12: users.technique.tbl_grp_item.TblGrpItemQRequest.MetadataEntry
}
var file_users_technique_tbl_grp_item_proto_depIdxs = []int32{
	0,  // 0: users.technique.tbl_grp_item.TblGrpItemARequest.result:type_name -> users.technique.tbl_grp_item.TblGrpItemAResult
	9,  // 1: users.technique.tbl_grp_item.TblGrpItemARequest.metadata:type_name -> users.technique.tbl_grp_item.TblGrpItemARequest.MetadataEntry
	1,  // 2: users.technique.tbl_grp_item.TblGrpItemURequest.result:type_name -> users.technique.tbl_grp_item.TblGrpItemUResult
	10, // 3: users.technique.tbl_grp_item.TblGrpItemURequest.metadata:type_name -> users.technique.tbl_grp_item.TblGrpItemURequest.MetadataEntry
	2,  // 4: users.technique.tbl_grp_item.TblGrpItemDRequest.result:type_name -> users.technique.tbl_grp_item.TblGrpItemDResult
	11, // 5: users.technique.tbl_grp_item.TblGrpItemDRequest.metadata:type_name -> users.technique.tbl_grp_item.TblGrpItemDRequest.MetadataEntry
	3,  // 6: users.technique.tbl_grp_item.TblGrpItemQRequest.result:type_name -> users.technique.tbl_grp_item.TblGrpItemQResult
	12, // 7: users.technique.tbl_grp_item.TblGrpItemQRequest.metadata:type_name -> users.technique.tbl_grp_item.TblGrpItemQRequest.MetadataEntry
	4,  // 8: users.technique.tbl_grp_item.TblGrpItemService.TblGrpItemA:input_type -> users.technique.tbl_grp_item.TblGrpItemARequest
	5,  // 9: users.technique.tbl_grp_item.TblGrpItemService.TblGrpItemU:input_type -> users.technique.tbl_grp_item.TblGrpItemURequest
	6,  // 10: users.technique.tbl_grp_item.TblGrpItemService.TblGrpItemD:input_type -> users.technique.tbl_grp_item.TblGrpItemDRequest
	7,  // 11: users.technique.tbl_grp_item.TblGrpItemService.TblGrpItemQ:input_type -> users.technique.tbl_grp_item.TblGrpItemQRequest
	8,  // 12: users.technique.tbl_grp_item.TblGrpItemService.TblGrpItemA:output_type -> users.technique.tbl_grp_item.Response
	8,  // 13: users.technique.tbl_grp_item.TblGrpItemService.TblGrpItemU:output_type -> users.technique.tbl_grp_item.Response
	8,  // 14: users.technique.tbl_grp_item.TblGrpItemService.TblGrpItemD:output_type -> users.technique.tbl_grp_item.Response
	8,  // 15: users.technique.tbl_grp_item.TblGrpItemService.TblGrpItemQ:output_type -> users.technique.tbl_grp_item.Response
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_users_technique_tbl_grp_item_proto_init() }
func file_users_technique_tbl_grp_item_proto_init() {
	if File_users_technique_tbl_grp_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_technique_tbl_grp_item_proto_rawDesc), len(file_users_technique_tbl_grp_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_technique_tbl_grp_item_proto_goTypes,
		DependencyIndexes: file_users_technique_tbl_grp_item_proto_depIdxs,
		MessageInfos:      file_users_technique_tbl_grp_item_proto_msgTypes,
	}.Build()
	File_users_technique_tbl_grp_item_proto = out.File
	file_users_technique_tbl_grp_item_proto_goTypes = nil
	file_users_technique_tbl_grp_item_proto_depIdxs = nil
}
