// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: datahub.proto

package datahub

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataHubService_Login_FullMethodName         = "/datahub.DataHubService/Login"
	DataHubService_GetSession_FullMethodName    = "/datahub.DataHubService/GetSession"
	DataHubService_GetAllConfigs_FullMethodName = "/datahub.DataHubService/GetAllConfigs"
	DataHubService_SaveConfig_FullMethodName    = "/datahub.DataHubService/SaveConfig"
	DataHubService_DeleteConfig_FullMethodName  = "/datahub.DataHubService/DeleteConfig"
	DataHubService_ProxyForward_FullMethodName  = "/datahub.DataHubService/ProxyForward"
	DataHubService_StreamProxy_FullMethodName   = "/datahub.DataHubService/StreamProxy"
	DataHubService_GetAuditLogs_FullMethodName  = "/datahub.DataHubService/GetAuditLogs"
	DataHubService_HealthCheck_FullMethodName   = "/datahub.DataHubService/HealthCheck"
)

// DataHubServiceClient is the client API for DataHubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataHubServiceClient interface {
	// Authentication & Session
	Login(ctx context.Context, in *LoginProtoRequest, opts ...grpc.CallOption) (*LoginProtoResponse, error)
	GetSession(ctx context.Context, in *SessionProtoRequest, opts ...grpc.CallOption) (*SessionProtoResponse, error)
	// Dynamic ERP Configurations
	GetAllConfigs(ctx context.Context, in *GetConfigsProtoRequest, opts ...grpc.CallOption) (*GetConfigsProtoResponse, error)
	SaveConfig(ctx context.Context, in *SaveConfigProtoRequest, opts ...grpc.CallOption) (*SaveConfigProtoResponse, error)
	DeleteConfig(ctx context.Context, in *DeleteConfigProtoRequest, opts ...grpc.CallOption) (*DeleteConfigProtoResponse, error)
	// High-Throughput Proxy
	ProxyForward(ctx context.Context, in *ProxyProtoRequest, opts ...grpc.CallOption) (*ProxyProtoResponse, error)
	StreamProxy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxyProtoRequest, ProxyProtoResponse], error)
	// Audit Logs & Health
	GetAuditLogs(ctx context.Context, in *AuditLogsProtoRequest, opts ...grpc.CallOption) (*AuditLogsProtoResponse, error)
	HealthCheck(ctx context.Context, in *HealthProtoRequest, opts ...grpc.CallOption) (*HealthProtoResponse, error)
}

type dataHubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataHubServiceClient(cc grpc.ClientConnInterface) DataHubServiceClient {
	return &dataHubServiceClient{cc}
}

func (c *dataHubServiceClient) Login(ctx context.Context, in *LoginProtoRequest, opts ...grpc.CallOption) (*LoginProtoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginProtoResponse)
	err := c.cc.Invoke(ctx, DataHubService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataHubServiceClient) GetSession(ctx context.Context, in *SessionProtoRequest, opts ...grpc.CallOption) (*SessionProtoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionProtoResponse)
	err := c.cc.Invoke(ctx, DataHubService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataHubServiceClient) GetAllConfigs(ctx context.Context, in *GetConfigsProtoRequest, opts ...grpc.CallOption) (*GetConfigsProtoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigsProtoResponse)
	err := c.cc.Invoke(ctx, DataHubService_GetAllConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataHubServiceClient) SaveConfig(ctx context.Context, in *SaveConfigProtoRequest, opts ...grpc.CallOption) (*SaveConfigProtoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveConfigProtoResponse)
	err := c.cc.Invoke(ctx, DataHubService_SaveConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataHubServiceClient) DeleteConfig(ctx context.Context, in *DeleteConfigProtoRequest, opts ...grpc.CallOption) (*DeleteConfigProtoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConfigProtoResponse)
	err := c.cc.Invoke(ctx, DataHubService_DeleteConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataHubServiceClient) ProxyForward(ctx context.Context, in *ProxyProtoRequest, opts ...grpc.CallOption) (*ProxyProtoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProxyProtoResponse)
	err := c.cc.Invoke(ctx, DataHubService_ProxyForward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataHubServiceClient) StreamProxy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxyProtoRequest, ProxyProtoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataHubService_ServiceDesc.Streams[0], DataHubService_StreamProxy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProxyProtoRequest, ProxyProtoResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataHubService_StreamProxyClient = grpc.BidiStreamingClient[ProxyProtoRequest, ProxyProtoResponse]

func (c *dataHubServiceClient) GetAuditLogs(ctx context.Context, in *AuditLogsProtoRequest, opts ...grpc.CallOption) (*AuditLogsProtoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditLogsProtoResponse)
	err := c.cc.Invoke(ctx, DataHubService_GetAuditLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataHubServiceClient) HealthCheck(ctx context.Context, in *HealthProtoRequest, opts ...grpc.CallOption) (*HealthProtoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthProtoResponse)
	err := c.cc.Invoke(ctx, DataHubService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataHubServiceServer is the server API for DataHubService service.
// All implementations must embed UnimplementedDataHubServiceServer
// for forward compatibility.
type DataHubServiceServer interface {
	// Authentication & Session
	Login(context.Context, *LoginProtoRequest) (*LoginProtoResponse, error)
	GetSession(context.Context, *SessionProtoRequest) (*SessionProtoResponse, error)
	// Dynamic ERP Configurations
	GetAllConfigs(context.Context, *GetConfigsProtoRequest) (*GetConfigsProtoResponse, error)
	SaveConfig(context.Context, *SaveConfigProtoRequest) (*SaveConfigProtoResponse, error)
	DeleteConfig(context.Context, *DeleteConfigProtoRequest) (*DeleteConfigProtoResponse, error)
	// High-Throughput Proxy
	ProxyForward(context.Context, *ProxyProtoRequest) (*ProxyProtoResponse, error)
	StreamProxy(grpc.BidiStreamingServer[ProxyProtoRequest, ProxyProtoResponse]) error
	// Audit Logs & Health
	GetAuditLogs(context.Context, *AuditLogsProtoRequest) (*AuditLogsProtoResponse, error)
	HealthCheck(context.Context, *HealthProtoRequest) (*HealthProtoResponse, error)
	mustEmbedUnimplementedDataHubServiceServer()
}

// UnimplementedDataHubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataHubServiceServer struct{}

func (UnimplementedDataHubServiceServer) Login(context.Context, *LoginProtoRequest) (*LoginProtoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedDataHubServiceServer) GetSession(context.Context, *SessionProtoRequest) (*SessionProtoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedDataHubServiceServer) GetAllConfigs(context.Context, *GetConfigsProtoRequest) (*GetConfigsProtoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllConfigs not implemented")
}
func (UnimplementedDataHubServiceServer) SaveConfig(context.Context, *SaveConfigProtoRequest) (*SaveConfigProtoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveConfig not implemented")
}
func (UnimplementedDataHubServiceServer) DeleteConfig(context.Context, *DeleteConfigProtoRequest) (*DeleteConfigProtoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConfig not implemented")
}
func (UnimplementedDataHubServiceServer) ProxyForward(context.Context, *ProxyProtoRequest) (*ProxyProtoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProxyForward not implemented")
}
func (UnimplementedDataHubServiceServer) StreamProxy(grpc.BidiStreamingServer[ProxyProtoRequest, ProxyProtoResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamProxy not implemented")
}
func (UnimplementedDataHubServiceServer) GetAuditLogs(context.Context, *AuditLogsProtoRequest) (*AuditLogsProtoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuditLogs not implemented")
}
func (UnimplementedDataHubServiceServer) HealthCheck(context.Context, *HealthProtoRequest) (*HealthProtoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedDataHubServiceServer) mustEmbedUnimplementedDataHubServiceServer() {}
func (UnimplementedDataHubServiceServer) testEmbeddedByValue()                        {}

// UnsafeDataHubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataHubServiceServer will
// result in compilation errors.
type UnsafeDataHubServiceServer interface {
	mustEmbedUnimplementedDataHubServiceServer()
}

func RegisterDataHubServiceServer(s grpc.ServiceRegistrar, srv DataHubServiceServer) {
	// If the following call panics, it indicates UnimplementedDataHubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataHubService_ServiceDesc, srv)
}

func _DataHubService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginProtoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataHubServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataHubService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataHubServiceServer).Login(ctx, req.(*LoginProtoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataHubService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionProtoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataHubServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataHubService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataHubServiceServer).GetSession(ctx, req.(*SessionProtoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataHubService_GetAllConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigsProtoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataHubServiceServer).GetAllConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataHubService_GetAllConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataHubServiceServer).GetAllConfigs(ctx, req.(*GetConfigsProtoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataHubService_SaveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveConfigProtoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataHubServiceServer).SaveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataHubService_SaveConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataHubServiceServer).SaveConfig(ctx, req.(*SaveConfigProtoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataHubService_DeleteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfigProtoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataHubServiceServer).DeleteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataHubService_DeleteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataHubServiceServer).DeleteConfig(ctx, req.(*DeleteConfigProtoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataHubService_ProxyForward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyProtoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataHubServiceServer).ProxyForward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataHubService_ProxyForward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataHubServiceServer).ProxyForward(ctx, req.(*ProxyProtoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataHubService_StreamProxy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataHubServiceServer).StreamProxy(&grpc.GenericServerStream[ProxyProtoRequest, ProxyProtoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataHubService_StreamProxyServer = grpc.BidiStreamingServer[ProxyProtoRequest, ProxyProtoResponse]

func _DataHubService_GetAuditLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditLogsProtoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataHubServiceServer).GetAuditLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataHubService_GetAuditLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataHubServiceServer).GetAuditLogs(ctx, req.(*AuditLogsProtoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataHubService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthProtoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataHubServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataHubService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataHubServiceServer).HealthCheck(ctx, req.(*HealthProtoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataHubService_ServiceDesc is the grpc.ServiceDesc for DataHubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataHubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datahub.DataHubService",
	HandlerType: (*DataHubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _DataHubService_Login_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _DataHubService_GetSession_Handler,
		},
		{
			MethodName: "GetAllConfigs",
			Handler:    _DataHubService_GetAllConfigs_Handler,
		},
		{
			MethodName: "SaveConfig",
			Handler:    _DataHubService_SaveConfig_Handler,
		},
		{
			MethodName: "DeleteConfig",
			Handler:    _DataHubService_DeleteConfig_Handler,
		},
		{
			MethodName: "ProxyForward",
			Handler:    _DataHubService_ProxyForward_Handler,
		},
		{
			MethodName: "GetAuditLogs",
			Handler:    _DataHubService_GetAuditLogs_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _DataHubService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProxy",
			Handler:       _DataHubService_StreamProxy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "datahub.proto",
}
