// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: datahub.proto

package datahub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginProtoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ConfigKey     string                 `protobuf:"bytes,3,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginProtoRequest) Reset() {
	*x = LoginProtoRequest{}
	mi := &file_datahub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginProtoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginProtoRequest) ProtoMessage() {}

func (x *LoginProtoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginProtoRequest.ProtoReflect.Descriptor instead.
func (*LoginProtoRequest) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{0}
}

func (x *LoginProtoRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginProtoRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginProtoRequest) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

type TokenSessionProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ConfigKey     string                 `protobuf:"bytes,2,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	AccessToken   string                 `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,5,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,6,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,7,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Scope         string                 `protobuf:"bytes,9,opt,name=scope,proto3" json:"scope,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenSessionProto) Reset() {
	*x = TokenSessionProto{}
	mi := &file_datahub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenSessionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenSessionProto) ProtoMessage() {}

func (x *TokenSessionProto) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenSessionProto.ProtoReflect.Descriptor instead.
func (*TokenSessionProto) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{1}
}

func (x *TokenSessionProto) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TokenSessionProto) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *TokenSessionProto) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TokenSessionProto) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenSessionProto) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenSessionProto) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenSessionProto) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *TokenSessionProto) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *TokenSessionProto) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *TokenSessionProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TokenSessionProto) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type LoginProtoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ConfigKey     string                 `protobuf:"bytes,2,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	AccessToken   string                 `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,5,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,6,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Scope         string                 `protobuf:"bytes,8,opt,name=scope,proto3" json:"scope,omitempty"`
	Session       *TokenSessionProto     `protobuf:"bytes,9,opt,name=session,proto3" json:"session,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginProtoResponse) Reset() {
	*x = LoginProtoResponse{}
	mi := &file_datahub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginProtoResponse) ProtoMessage() {}

func (x *LoginProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginProtoResponse.ProtoReflect.Descriptor instead.
func (*LoginProtoResponse) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{2}
}

func (x *LoginProtoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginProtoResponse) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *LoginProtoResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginProtoResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginProtoResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *LoginProtoResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *LoginProtoResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *LoginProtoResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *LoginProtoResponse) GetSession() *TokenSessionProto {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *LoginProtoResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SessionProtoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigKey     string                 `protobuf:"bytes,1,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionProtoRequest) Reset() {
	*x = SessionProtoRequest{}
	mi := &file_datahub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionProtoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionProtoRequest) ProtoMessage() {}

func (x *SessionProtoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionProtoRequest.ProtoReflect.Descriptor instead.
func (*SessionProtoRequest) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{3}
}

func (x *SessionProtoRequest) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *SessionProtoRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SessionProtoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Session       *TokenSessionProto     `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionProtoResponse) Reset() {
	*x = SessionProtoResponse{}
	mi := &file_datahub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionProtoResponse) ProtoMessage() {}

func (x *SessionProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionProtoResponse.ProtoReflect.Descriptor instead.
func (*SessionProtoResponse) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{4}
}

func (x *SessionProtoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SessionProtoResponse) GetSession() *TokenSessionProto {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *SessionProtoResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ErpConfigProto struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConfigKey          string                 `protobuf:"bytes,1,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	ConfigName         string                 `protobuf:"bytes,2,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	Provider           string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	AuthUrl            string                 `protobuf:"bytes,4,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	BaseApiUrl         string                 `protobuf:"bytes,5,opt,name=base_api_url,json=baseApiUrl,proto3" json:"base_api_url,omitempty"`
	Referer            string                 `protobuf:"bytes,6,opt,name=referer,proto3" json:"referer,omitempty"`
	ClientId           string                 `protobuf:"bytes,7,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret       string                 `protobuf:"bytes,8,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	DeviceCode         string                 `protobuf:"bytes,9,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"`
	ConnectionName     string                 `protobuf:"bytes,10,opt,name=connection_name,json=connectionName,proto3" json:"connection_name,omitempty"`
	GrantType          string                 `protobuf:"bytes,11,opt,name=grant_type,json=grantType,proto3" json:"grant_type,omitempty"`
	Scope              string                 `protobuf:"bytes,12,opt,name=scope,proto3" json:"scope,omitempty"`
	InsecureSkipVerify bool                   `protobuf:"varint,13,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecure_skip_verify,omitempty"`
	ExtraParams        string                 `protobuf:"bytes,14,opt,name=extra_params,json=extraParams,proto3" json:"extra_params,omitempty"`
	IsActive           bool                   `protobuf:"varint,15,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ErpConfigProto) Reset() {
	*x = ErpConfigProto{}
	mi := &file_datahub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErpConfigProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErpConfigProto) ProtoMessage() {}

func (x *ErpConfigProto) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErpConfigProto.ProtoReflect.Descriptor instead.
func (*ErpConfigProto) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{5}
}

func (x *ErpConfigProto) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *ErpConfigProto) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *ErpConfigProto) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ErpConfigProto) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

func (x *ErpConfigProto) GetBaseApiUrl() string {
	if x != nil {
		return x.BaseApiUrl
	}
	return ""
}

func (x *ErpConfigProto) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

func (x *ErpConfigProto) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ErpConfigProto) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *ErpConfigProto) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

func (x *ErpConfigProto) GetConnectionName() string {
	if x != nil {
		return x.ConnectionName
	}
	return ""
}

func (x *ErpConfigProto) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *ErpConfigProto) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ErpConfigProto) GetInsecureSkipVerify() bool {
	if x != nil {
		return x.InsecureSkipVerify
	}
	return false
}

func (x *ErpConfigProto) GetExtraParams() string {
	if x != nil {
		return x.ExtraParams
	}
	return ""
}

func (x *ErpConfigProto) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ErpConfigProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ErpConfigProto) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetConfigsProtoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigsProtoRequest) Reset() {
	*x = GetConfigsProtoRequest{}
	mi := &file_datahub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigsProtoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigsProtoRequest) ProtoMessage() {}

func (x *GetConfigsProtoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigsProtoRequest.ProtoReflect.Descriptor instead.
func (*GetConfigsProtoRequest) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{6}
}

type GetConfigsProtoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Configs       []*ErpConfigProto      `protobuf:"bytes,2,rep,name=configs,proto3" json:"configs,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigsProtoResponse) Reset() {
	*x = GetConfigsProtoResponse{}
	mi := &file_datahub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigsProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigsProtoResponse) ProtoMessage() {}

func (x *GetConfigsProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigsProtoResponse.ProtoReflect.Descriptor instead.
func (*GetConfigsProtoResponse) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{7}
}

func (x *GetConfigsProtoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetConfigsProtoResponse) GetConfigs() []*ErpConfigProto {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *GetConfigsProtoResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SaveConfigProtoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ErpConfigProto        `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveConfigProtoRequest) Reset() {
	*x = SaveConfigProtoRequest{}
	mi := &file_datahub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConfigProtoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConfigProtoRequest) ProtoMessage() {}

func (x *SaveConfigProtoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConfigProtoRequest.ProtoReflect.Descriptor instead.
func (*SaveConfigProtoRequest) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{8}
}

func (x *SaveConfigProtoRequest) GetConfig() *ErpConfigProto {
	if x != nil {
		return x.Config
	}
	return nil
}

type SaveConfigProtoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Config        *ErpConfigProto        `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveConfigProtoResponse) Reset() {
	*x = SaveConfigProtoResponse{}
	mi := &file_datahub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConfigProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConfigProtoResponse) ProtoMessage() {}

func (x *SaveConfigProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConfigProtoResponse.ProtoReflect.Descriptor instead.
func (*SaveConfigProtoResponse) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{9}
}

func (x *SaveConfigProtoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveConfigProtoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SaveConfigProtoResponse) GetConfig() *ErpConfigProto {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SaveConfigProtoResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DeleteConfigProtoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigKey     string                 `protobuf:"bytes,1,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigProtoRequest) Reset() {
	*x = DeleteConfigProtoRequest{}
	mi := &file_datahub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigProtoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigProtoRequest) ProtoMessage() {}

func (x *DeleteConfigProtoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigProtoRequest.ProtoReflect.Descriptor instead.
func (*DeleteConfigProtoRequest) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteConfigProtoRequest) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

type DeleteConfigProtoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigProtoResponse) Reset() {
	*x = DeleteConfigProtoResponse{}
	mi := &file_datahub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigProtoResponse) ProtoMessage() {}

func (x *DeleteConfigProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigProtoResponse.ProtoReflect.Descriptor instead.
func (*DeleteConfigProtoResponse) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteConfigProtoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteConfigProtoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteConfigProtoResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ProxyProtoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigKey     string                 `protobuf:"bytes,1,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Params        map[string]string      `protobuf:"bytes,6,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BodyJson      string                 `protobuf:"bytes,7,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	BodyRaw       []byte                 `protobuf:"bytes,8,opt,name=body_raw,json=bodyRaw,proto3" json:"body_raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyProtoRequest) Reset() {
	*x = ProxyProtoRequest{}
	mi := &file_datahub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyProtoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyProtoRequest) ProtoMessage() {}

func (x *ProxyProtoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyProtoRequest.ProtoReflect.Descriptor instead.
func (*ProxyProtoRequest) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{12}
}

func (x *ProxyProtoRequest) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *ProxyProtoRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProxyProtoRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ProxyProtoRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProxyProtoRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ProxyProtoRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ProxyProtoRequest) GetBodyJson() string {
	if x != nil {
		return x.BodyJson
	}
	return ""
}

func (x *ProxyProtoRequest) GetBodyRaw() []byte {
	if x != nil {
		return x.BodyRaw
	}
	return nil
}

type ProxyProtoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	TraceId       string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	DataJson      string                 `protobuf:"bytes,5,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	DataRaw       []byte                 `protobuf:"bytes,6,opt,name=data_raw,json=dataRaw,proto3" json:"data_raw,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyProtoResponse) Reset() {
	*x = ProxyProtoResponse{}
	mi := &file_datahub_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyProtoResponse) ProtoMessage() {}

func (x *ProxyProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyProtoResponse.ProtoReflect.Descriptor instead.
func (*ProxyProtoResponse) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{13}
}

func (x *ProxyProtoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProxyProtoResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ProxyProtoResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ProxyProtoResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ProxyProtoResponse) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

func (x *ProxyProtoResponse) GetDataRaw() []byte {
	if x != nil {
		return x.DataRaw
	}
	return nil
}

func (x *ProxyProtoResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type AuditLogsProtoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigKey     string                 `protobuf:"bytes,1,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogsProtoRequest) Reset() {
	*x = AuditLogsProtoRequest{}
	mi := &file_datahub_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogsProtoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogsProtoRequest) ProtoMessage() {}

func (x *AuditLogsProtoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogsProtoRequest.ProtoReflect.Descriptor instead.
func (*AuditLogsProtoRequest) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{14}
}

func (x *AuditLogsProtoRequest) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *AuditLogsProtoRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AuditLogsProtoRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type AuditLogProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TraceId        string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ConfigKey      string                 `protobuf:"bytes,3,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	Username       string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Method         string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Endpoint       string                 `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	TargetUrl      string                 `protobuf:"bytes,7,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	StatusCode     int32                  `protobuf:"varint,8,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	LatencyMs      int64                  `protobuf:"varint,9,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ClientIp       string                 `protobuf:"bytes,10,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent      string                 `protobuf:"bytes,11,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	RequestPayload string                 `protobuf:"bytes,12,opt,name=request_payload,json=requestPayload,proto3" json:"request_payload,omitempty"`
	ResponseBrief  string                 `protobuf:"bytes,13,opt,name=response_brief,json=responseBrief,proto3" json:"response_brief,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,14,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuditLogProto) Reset() {
	*x = AuditLogProto{}
	mi := &file_datahub_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogProto) ProtoMessage() {}

func (x *AuditLogProto) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogProto.ProtoReflect.Descriptor instead.
func (*AuditLogProto) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{15}
}

func (x *AuditLogProto) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditLogProto) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AuditLogProto) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *AuditLogProto) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuditLogProto) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuditLogProto) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *AuditLogProto) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *AuditLogProto) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AuditLogProto) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *AuditLogProto) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *AuditLogProto) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AuditLogProto) GetRequestPayload() string {
	if x != nil {
		return x.RequestPayload
	}
	return ""
}

func (x *AuditLogProto) GetResponseBrief() string {
	if x != nil {
		return x.ResponseBrief
	}
	return ""
}

func (x *AuditLogProto) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AuditLogProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AuditLogsProtoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Logs          []*AuditLogProto       `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogsProtoResponse) Reset() {
	*x = AuditLogsProtoResponse{}
	mi := &file_datahub_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogsProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogsProtoResponse) ProtoMessage() {}

func (x *AuditLogsProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogsProtoResponse.ProtoReflect.Descriptor instead.
func (*AuditLogsProtoResponse) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{16}
}

func (x *AuditLogsProtoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuditLogsProtoResponse) GetLogs() []*AuditLogProto {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *AuditLogsProtoResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AuditLogsProtoResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HealthProtoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthProtoRequest) Reset() {
	*x = HealthProtoRequest{}
	mi := &file_datahub_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthProtoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthProtoRequest) ProtoMessage() {}

func (x *HealthProtoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthProtoRequest.ProtoReflect.Descriptor instead.
func (*HealthProtoRequest) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{17}
}

type HealthProtoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	DbConnected   bool                   `protobuf:"varint,4,opt,name=db_connected,json=dbConnected,proto3" json:"db_connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthProtoResponse) Reset() {
	*x = HealthProtoResponse{}
	mi := &file_datahub_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthProtoResponse) ProtoMessage() {}

func (x *HealthProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datahub_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthProtoResponse.ProtoReflect.Descriptor instead.
func (*HealthProtoResponse) Descriptor() ([]byte, []int) {
	return file_datahub_proto_rawDescGZIP(), []int{18}
}

func (x *HealthProtoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthProtoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthProtoResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthProtoResponse) GetDbConnected() bool {
	if x != nil {
		return x.DbConnected
	}
	return false
}

var File_datahub_proto protoreflect.FileDescriptor

const file_datahub_proto_rawDesc = "" +
	"\n" +
	"\rdatahub.proto\x12\adatahub\"j\n" +
	"\x11LoginProtoRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"config_key\x18\x03 \x01(\tR\tconfigKey\"\xd7\x02\n" +
	"\x11TokenSessionProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"config_key\x18\x02 \x01(\tR\tconfigKey\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x05 \x01(\tR\ttokenType\x12#\n" +
	"\rrefresh_token\x18\x06 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\a \x01(\x03R\texpiresIn\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\tR\texpiresAt\x12\x14\n" +
	"\x05scope\x18\t \x01(\tR\x05scope\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"\xda\x02\n" +
	"\x12LoginProtoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"config_key\x18\x02 \x01(\tR\tconfigKey\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x05 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x06 \x01(\x03R\texpiresIn\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\tR\texpiresAt\x12\x14\n" +
	"\x05scope\x18\b \x01(\tR\x05scope\x124\n" +
	"\asession\x18\t \x01(\v2\x1a.datahub.TokenSessionProtoR\asession\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\"P\n" +
	"\x13SessionProtoRequest\x12\x1d\n" +
	"\n" +
	"config_key\x18\x01 \x01(\tR\tconfigKey\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\x8b\x01\n" +
	"\x14SessionProtoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x124\n" +
	"\asession\x18\x02 \x01(\v2\x1a.datahub.TokenSessionProtoR\asession\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xb4\x04\n" +
	"\x0eErpConfigProto\x12\x1d\n" +
	"\n" +
	"config_key\x18\x01 \x01(\tR\tconfigKey\x12\x1f\n" +
	"\vconfig_name\x18\x02 \x01(\tR\n" +
	"configName\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x19\n" +
	"\bauth_url\x18\x04 \x01(\tR\aauthUrl\x12 \n" +
	"\fbase_api_url\x18\x05 \x01(\tR\n" +
	"baseApiUrl\x12\x18\n" +
	"\areferer\x18\x06 \x01(\tR\areferer\x12\x1b\n" +
	"\tclient_id\x18\a \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\b \x01(\tR\fclientSecret\x12\x1f\n" +
	"\vdevice_code\x18\t \x01(\tR\n" +
	"deviceCode\x12'\n" +
	"\x0fconnection_name\x18\n" +
	" \x01(\tR\x0econnectionName\x12\x1d\n" +
	"\n" +
	"grant_type\x18\v \x01(\tR\tgrantType\x12\x14\n" +
	"\x05scope\x18\f \x01(\tR\x05scope\x120\n" +
	"\x14insecure_skip_verify\x18\r \x01(\bR\x12insecureSkipVerify\x12!\n" +
	"\fextra_params\x18\x0e \x01(\tR\vextraParams\x12\x1b\n" +
	"\tis_active\x18\x0f \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\tR\tupdatedAt\"\x18\n" +
	"\x16GetConfigsProtoRequest\"\x8b\x01\n" +
	"\x17GetConfigsProtoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x121\n" +
	"\aconfigs\x18\x02 \x03(\v2\x17.datahub.ErpConfigProtoR\aconfigs\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"I\n" +
	"\x16SaveConfigProtoRequest\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.datahub.ErpConfigProtoR\x06config\"\xa3\x01\n" +
	"\x17SaveConfigProtoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.datahub.ErpConfigProtoR\x06config\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"9\n" +
	"\x18DeleteConfigProtoRequest\x12\x1d\n" +
	"\n" +
	"config_key\x18\x01 \x01(\tR\tconfigKey\"t\n" +
	"\x19DeleteConfigProtoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xac\x03\n" +
	"\x11ProxyProtoRequest\x12\x1d\n" +
	"\n" +
	"config_key\x18\x01 \x01(\tR\tconfigKey\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12A\n" +
	"\aheaders\x18\x05 \x03(\v2'.datahub.ProxyProtoRequest.HeadersEntryR\aheaders\x12>\n" +
	"\x06params\x18\x06 \x03(\v2&.datahub.ProxyProtoRequest.ParamsEntryR\x06params\x12\x1b\n" +
	"\tbody_json\x18\a \x01(\tR\bbodyJson\x12\x19\n" +
	"\bbody_raw\x18\b \x01(\fR\abodyRaw\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x01\n" +
	"\x12ProxyProtoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\x12\x1b\n" +
	"\tdata_json\x18\x05 \x01(\tR\bdataJson\x12\x19\n" +
	"\bdata_raw\x18\x06 \x01(\fR\adataRaw\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"d\n" +
	"\x15AuditLogsProtoRequest\x12\x1d\n" +
	"\n" +
	"config_key\x18\x01 \x01(\tR\tconfigKey\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xd8\x03\n" +
	"\rAuditLogProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"config_key\x18\x03 \x01(\tR\tconfigKey\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x1a\n" +
	"\bendpoint\x18\x06 \x01(\tR\bendpoint\x12\x1d\n" +
	"\n" +
	"target_url\x18\a \x01(\tR\ttargetUrl\x12\x1f\n" +
	"\vstatus_code\x18\b \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\t \x01(\x03R\tlatencyMs\x12\x1b\n" +
	"\tclient_ip\x18\n" +
	" \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\v \x01(\tR\tuserAgent\x12'\n" +
	"\x0frequest_payload\x18\f \x01(\tR\x0erequestPayload\x12%\n" +
	"\x0eresponse_brief\x18\r \x01(\tR\rresponseBrief\x12#\n" +
	"\rerror_message\x18\x0e \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\"\x99\x01\n" +
	"\x16AuditLogsProtoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12*\n" +
	"\x04logs\x18\x02 \x03(\v2\x16.datahub.AuditLogProtoR\x04logs\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\x14\n" +
	"\x12HealthProtoRequest\"\x91\x01\n" +
	"\x13HealthProtoResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\fdb_connected\x18\x04 \x01(\bR\vdbConnected2\xc9\x05\n" +
	"\x0eDataHubService\x12@\n" +
	"\x05Login\x12\x1a.datahub.LoginProtoRequest\x1a\x1b.datahub.LoginProtoResponse\x12I\n" +
	"\n" +
	"GetSession\x12\x1c.datahub.SessionProtoRequest\x1a\x1d.datahub.SessionProtoResponse\x12R\n" +
	"\rGetAllConfigs\x12\x1f.datahub.GetConfigsProtoRequest\x1a .datahub.GetConfigsProtoResponse\x12O\n" +
	"\n" +
	"SaveConfig\x12\x1f.datahub.SaveConfigProtoRequest\x1a .datahub.SaveConfigProtoResponse\x12U\n" +
	"\fDeleteConfig\x12!.datahub.DeleteConfigProtoRequest\x1a\".datahub.DeleteConfigProtoResponse\x12G\n" +
	"\fProxyForward\x12\x1a.datahub.ProxyProtoRequest\x1a\x1b.datahub.ProxyProtoResponse\x12J\n" +
	"\vStreamProxy\x12\x1a.datahub.ProxyProtoRequest\x1a\x1b.datahub.ProxyProtoResponse(\x010\x01\x12O\n" +
	"\fGetAuditLogs\x12\x1e.datahub.AuditLogsProtoRequest\x1a\x1f.datahub.AuditLogsProtoResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.datahub.HealthProtoRequest\x1a\x1c.datahub.HealthProtoResponseB\x1cZ\x1aservice-datahub/pb/datahubb\x06proto3"

var (
	file_datahub_proto_rawDescOnce sync.Once
	file_datahub_proto_rawDescData []byte
)

func file_datahub_proto_rawDescGZIP() []byte {
	file_datahub_proto_rawDescOnce.Do(func() {
		file_datahub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datahub_proto_rawDesc), len(file_datahub_proto_rawDesc)))
	})
	return file_datahub_proto_rawDescData
}

var file_datahub_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_datahub_proto_goTypes = []any{
	(*LoginProtoRequest)(nil),         // 0: datahub.LoginProtoRequest
	(*TokenSessionProto)(nil),         // 1: datahub.TokenSessionProto
	(*LoginProtoResponse)(nil),        // 2: datahub.LoginProtoResponse
	(*SessionProtoRequest)(nil),       // 3: datahub.SessionProtoRequest
	(*SessionProtoResponse)(nil),      // 4: datahub.SessionProtoResponse
	(*ErpConfigProto)(nil),            // 5: datahub.ErpConfigProto
	(*GetConfigsProtoRequest)(nil),    // 6: datahub.GetConfigsProtoRequest
	(*GetConfigsProtoResponse)(nil),   // 7: datahub.GetConfigsProtoResponse
	(*SaveConfigProtoRequest)(nil),    // 8: datahub.SaveConfigProtoRequest
	(*SaveConfigProtoResponse)(nil),   // 9: datahub.SaveConfigProtoResponse
	(*DeleteConfigProtoRequest)(nil),  // 10: datahub.DeleteConfigProtoRequest
	(*DeleteConfigProtoResponse)(nil), // 11: datahub.DeleteConfigProtoResponse
	(*ProxyProtoRequest)(nil),         // 12: datahub.ProxyProtoRequest
	(*ProxyProtoResponse)(nil),        // 13: datahub.ProxyProtoResponse
	(*AuditLogsProtoRequest)(nil),     // 14: datahub.AuditLogsProtoRequest
	(*AuditLogProto)(nil),             // 15: datahub.AuditLogProto
	(*AuditLogsProtoResponse)(nil),    // 16: datahub.AuditLogsProtoResponse
	(*HealthProtoRequest)(nil),        // 17: datahub.HealthProtoRequest
	(*HealthProtoResponse)(nil),       // 18: datahub.HealthProtoResponse
	nil,                               // 19: datahub.ProxyProtoRequest.HeadersEntry
	nil,                               // 20: datahub.ProxyProtoRequest.ParamsEntry
}
var file_datahub_proto_depIdxs = []int32{
	1,  // 0: datahub.LoginProtoResponse.session:type_name -> datahub.TokenSessionProto
	1,  // 1: datahub.SessionProtoResponse.session:type_name -> datahub.TokenSessionProto
	5,  // 2: datahub.GetConfigsProtoResponse.configs:type_name -> datahub.ErpConfigProto
	5,  // 3: datahub.SaveConfigProtoRequest.config:type_name -> datahub.ErpConfigProto
	5,  // 4: datahub.SaveConfigProtoResponse.config:type_name -> datahub.ErpConfigProto
	19, // 5: datahub.ProxyProtoRequest.headers:type_name -> datahub.ProxyProtoRequest.HeadersEntry
	20, // 6: datahub.ProxyProtoRequest.params:type_name -> datahub.ProxyProtoRequest.ParamsEntry
	15, // 7: datahub.AuditLogsProtoResponse.logs:type_name -> datahub.AuditLogProto
	0,  // 8: datahub.DataHubService.Login:input_type -> datahub.LoginProtoRequest
	3,  // 9: datahub.DataHubService.GetSession:input_type -> datahub.SessionProtoRequest
	6,  // 10: datahub.DataHubService.GetAllConfigs:input_type -> datahub.GetConfigsProtoRequest
	8,  // 11: datahub.DataHubService.SaveConfig:input_type -> datahub.SaveConfigProtoRequest
	10, // 12: datahub.DataHubService.DeleteConfig:input_type -> datahub.DeleteConfigProtoRequest
	12, // 13: datahub.DataHubService.ProxyForward:input_type -> datahub.ProxyProtoRequest
	12, // 14: datahub.DataHubService.StreamProxy:input_type -> datahub.ProxyProtoRequest
	14, // 15: datahub.DataHubService.GetAuditLogs:input_type -> datahub.AuditLogsProtoRequest
	17, // 16: datahub.DataHubService.HealthCheck:input_type -> datahub.HealthProtoRequest
	2,  // 17: datahub.DataHubService.Login:output_type -> datahub.LoginProtoResponse
	4,  // 18: datahub.DataHubService.GetSession:output_type -> datahub.SessionProtoResponse
	7,  // 19: datahub.DataHubService.GetAllConfigs:output_type -> datahub.GetConfigsProtoResponse
	9,  // 20: datahub.DataHubService.SaveConfig:output_type -> datahub.SaveConfigProtoResponse
	11, // 21: datahub.DataHubService.DeleteConfig:output_type -> datahub.DeleteConfigProtoResponse
	13, // 22: datahub.DataHubService.ProxyForward:output_type -> datahub.ProxyProtoResponse
	13, // 23: datahub.DataHubService.StreamProxy:output_type -> datahub.ProxyProtoResponse
	16, // 24: datahub.DataHubService.GetAuditLogs:output_type -> datahub.AuditLogsProtoResponse
	18, // 25: datahub.DataHubService.HealthCheck:output_type -> datahub.HealthProtoResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_datahub_proto_init() }
func file_datahub_proto_init() {
	if File_datahub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datahub_proto_rawDesc), len(file_datahub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datahub_proto_goTypes,
		DependencyIndexes: file_datahub_proto_depIdxs,
		MessageInfos:      file_datahub_proto_msgTypes,
	}.Build()
	File_datahub_proto = out.File
	file_datahub_proto_goTypes = nil
	file_datahub_proto_depIdxs = nil
}
