// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: system.proto

package datahub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserSeq       string                 `protobuf:"bytes,1,opt,name=user_seq,json=userSeq,proto3" json:"user_seq,omitempty"`
	CompanySeq    int32                  `protobuf:"varint,2,opt,name=company_seq,json=companySeq,proto3" json:"company_seq,omitempty"`
	IdxNo         int32                  `protobuf:"varint,3,opt,name=idx_no,json=idxNo,proto3" json:"idx_no,omitempty"`
	EmpId         string                 `protobuf:"bytes,4,opt,name=emp_id,json=empId,proto3" json:"emp_id,omitempty"`
	EmpCode       string                 `protobuf:"bytes,5,opt,name=emp_code,json=empCode,proto3" json:"emp_code,omitempty"`
	EmpName       string                 `protobuf:"bytes,6,opt,name=emp_name,json=empName,proto3" json:"emp_name,omitempty"`
	DeptName      string                 `protobuf:"bytes,7,opt,name=dept_name,json=deptName,proto3" json:"dept_name,omitempty"`
	ManagerName   string                 `protobuf:"bytes,8,opt,name=manager_name,json=managerName,proto3" json:"manager_name,omitempty"`
	UserId        string                 `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserType      int32                  `protobuf:"varint,10,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	UserName      string                 `protobuf:"bytes,11,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email         string                 `protobuf:"bytes,12,opt,name=email,proto3" json:"email,omitempty"`
	CheckPass1    bool                   `protobuf:"varint,13,opt,name=check_pass1,json=checkPass1,proto3" json:"check_pass1,omitempty"`
	StatusAcc     bool                   `protobuf:"varint,14,opt,name=status_acc,json=statusAcc,proto3" json:"status_acc,omitempty"`
	Status        string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	Active        bool                   `protobuf:"varint,16,opt,name=active,proto3" json:"active,omitempty"`
	LanguageSeq   int32                  `protobuf:"varint,17,opt,name=language_seq,json=languageSeq,proto3" json:"language_seq,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,18,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,20,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProto) Reset() {
	*x = UserProto{}
	mi := &file_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProto) ProtoMessage() {}

func (x *UserProto) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProto.ProtoReflect.Descriptor instead.
func (*UserProto) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{0}
}

func (x *UserProto) GetUserSeq() string {
	if x != nil {
		return x.UserSeq
	}
	return ""
}

func (x *UserProto) GetCompanySeq() int32 {
	if x != nil {
		return x.CompanySeq
	}
	return 0
}

func (x *UserProto) GetIdxNo() int32 {
	if x != nil {
		return x.IdxNo
	}
	return 0
}

func (x *UserProto) GetEmpId() string {
	if x != nil {
		return x.EmpId
	}
	return ""
}

func (x *UserProto) GetEmpCode() string {
	if x != nil {
		return x.EmpCode
	}
	return ""
}

func (x *UserProto) GetEmpName() string {
	if x != nil {
		return x.EmpName
	}
	return ""
}

func (x *UserProto) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *UserProto) GetManagerName() string {
	if x != nil {
		return x.ManagerName
	}
	return ""
}

func (x *UserProto) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProto) GetUserType() int32 {
	if x != nil {
		return x.UserType
	}
	return 0
}

func (x *UserProto) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserProto) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProto) GetCheckPass1() bool {
	if x != nil {
		return x.CheckPass1
	}
	return false
}

func (x *UserProto) GetStatusAcc() bool {
	if x != nil {
		return x.StatusAcc
	}
	return false
}

func (x *UserProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserProto) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *UserProto) GetLanguageSeq() int32 {
	if x != nil {
		return x.LanguageSeq
	}
	return 0
}

func (x *UserProto) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *UserProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserProto) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *UserProto) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UserQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	StatusAcc     string                 `protobuf:"bytes,3,opt,name=status_acc,json=statusAcc,proto3" json:"status_acc,omitempty"`
	Active        string                 `protobuf:"bytes,4,opt,name=active,proto3" json:"active,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserQueryRequest) Reset() {
	*x = UserQueryRequest{}
	mi := &file_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserQueryRequest) ProtoMessage() {}

func (x *UserQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserQueryRequest.ProtoReflect.Descriptor instead.
func (*UserQueryRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{1}
}

func (x *UserQueryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserQueryRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserQueryRequest) GetStatusAcc() string {
	if x != nil {
		return x.StatusAcc
	}
	return ""
}

func (x *UserQueryRequest) GetActive() string {
	if x != nil {
		return x.Active
	}
	return ""
}

func (x *UserQueryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserQueryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*UserProto           `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	TotalAll      int64                  `protobuf:"varint,5,opt,name=total_all,json=totalAll,proto3" json:"total_all,omitempty"`
	Page          int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResponse) Reset() {
	*x = UserListResponse{}
	mi := &file_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResponse) ProtoMessage() {}

func (x *UserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResponse.ProtoReflect.Descriptor instead.
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{2}
}

func (x *UserListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserListResponse) GetData() []*UserProto {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UserListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UserListResponse) GetTotalAll() int64 {
	if x != nil {
		return x.TotalAll
	}
	return 0
}

func (x *UserListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UserMutateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserProto           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMutateRequest) Reset() {
	*x = UserMutateRequest{}
	mi := &file_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMutateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMutateRequest) ProtoMessage() {}

func (x *UserMutateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMutateRequest.ProtoReflect.Descriptor instead.
func (*UserMutateRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{3}
}

func (x *UserMutateRequest) GetUsers() []*UserProto {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserMutateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*UserProto           `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMutateResponse) Reset() {
	*x = UserMutateResponse{}
	mi := &file_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMutateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMutateResponse) ProtoMessage() {}

func (x *UserMutateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMutateResponse.ProtoReflect.Descriptor instead.
func (*UserMutateResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{4}
}

func (x *UserMutateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserMutateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserMutateResponse) GetData() []*UserProto {
	if x != nil {
		return x.Data
	}
	return nil
}

type RoleGroupProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedByName string                 `protobuf:"bytes,4,opt,name=created_by_name,json=createdByName,proto3" json:"created_by_name,omitempty"`
	IdxNo         int32                  `protobuf:"varint,5,opt,name=idx_no,json=idxNo,proto3" json:"idx_no,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleGroupProto) Reset() {
	*x = RoleGroupProto{}
	mi := &file_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleGroupProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGroupProto) ProtoMessage() {}

func (x *RoleGroupProto) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGroupProto.ProtoReflect.Descriptor instead.
func (*RoleGroupProto) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{5}
}

func (x *RoleGroupProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleGroupProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleGroupProto) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *RoleGroupProto) GetCreatedByName() string {
	if x != nil {
		return x.CreatedByName
	}
	return ""
}

func (x *RoleGroupProto) GetIdxNo() int32 {
	if x != nil {
		return x.IdxNo
	}
	return 0
}

func (x *RoleGroupProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RoleGroupProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RoleGroupProto) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RoleGroupQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleGroupQueryRequest) Reset() {
	*x = RoleGroupQueryRequest{}
	mi := &file_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleGroupQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGroupQueryRequest) ProtoMessage() {}

func (x *RoleGroupQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGroupQueryRequest.ProtoReflect.Descriptor instead.
func (*RoleGroupQueryRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{6}
}

func (x *RoleGroupQueryRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *RoleGroupQueryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RoleGroupQueryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type RoleGroupListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*RoleGroupProto      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleGroupListResponse) Reset() {
	*x = RoleGroupListResponse{}
	mi := &file_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleGroupListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGroupListResponse) ProtoMessage() {}

func (x *RoleGroupListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGroupListResponse.ProtoReflect.Descriptor instead.
func (*RoleGroupListResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{7}
}

func (x *RoleGroupListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RoleGroupListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RoleGroupListResponse) GetData() []*RoleGroupProto {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RoleGroupListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RoleGroupMutateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*RoleGroupProto      `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleGroupMutateRequest) Reset() {
	*x = RoleGroupMutateRequest{}
	mi := &file_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleGroupMutateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGroupMutateRequest) ProtoMessage() {}

func (x *RoleGroupMutateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGroupMutateRequest.ProtoReflect.Descriptor instead.
func (*RoleGroupMutateRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{8}
}

func (x *RoleGroupMutateRequest) GetGroups() []*RoleGroupProto {
	if x != nil {
		return x.Groups
	}
	return nil
}

type RoleGroupMutateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*RoleGroupProto      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleGroupMutateResponse) Reset() {
	*x = RoleGroupMutateResponse{}
	mi := &file_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleGroupMutateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGroupMutateResponse) ProtoMessage() {}

func (x *RoleGroupMutateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGroupMutateResponse.ProtoReflect.Descriptor instead.
func (*RoleGroupMutateResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{9}
}

func (x *RoleGroupMutateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RoleGroupMutateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RoleGroupMutateResponse) GetData() []*RoleGroupProto {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserRoleProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	GroupId       string                 `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,5,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoleProto) Reset() {
	*x = UserRoleProto{}
	mi := &file_system_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleProto) ProtoMessage() {}

func (x *UserRoleProto) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleProto.ProtoReflect.Descriptor instead.
func (*UserRoleProto) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{10}
}

func (x *UserRoleProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserRoleProto) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRoleProto) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserRoleProto) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UserRoleProto) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *UserRoleProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type MenuRoleProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	RootMenuId    string                 `protobuf:"bytes,3,opt,name=root_menu_id,json=rootMenuId,proto3" json:"root_menu_id,omitempty"`
	MenuId        string                 `protobuf:"bytes,4,opt,name=menu_id,json=menuId,proto3" json:"menu_id,omitempty"`
	MenuKey       string                 `protobuf:"bytes,5,opt,name=menu_key,json=menuKey,proto3" json:"menu_key,omitempty"`
	MenuLabel     string                 `protobuf:"bytes,6,opt,name=menu_label,json=menuLabel,proto3" json:"menu_label,omitempty"`
	CanView       bool                   `protobuf:"varint,7,opt,name=can_view,json=canView,proto3" json:"can_view,omitempty"`
	CanCreate     bool                   `protobuf:"varint,8,opt,name=can_create,json=canCreate,proto3" json:"can_create,omitempty"`
	CanEdit       bool                   `protobuf:"varint,9,opt,name=can_edit,json=canEdit,proto3" json:"can_edit,omitempty"`
	CanDelete     bool                   `protobuf:"varint,10,opt,name=can_delete,json=canDelete,proto3" json:"can_delete,omitempty"`
	CanExport     bool                   `protobuf:"varint,11,opt,name=can_export,json=canExport,proto3" json:"can_export,omitempty"`
	CanPrint      bool                   `protobuf:"varint,12,opt,name=can_print,json=canPrint,proto3" json:"can_print,omitempty"`
	DataScope     string                 `protobuf:"bytes,13,opt,name=data_scope,json=dataScope,proto3" json:"data_scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuRoleProto) Reset() {
	*x = MenuRoleProto{}
	mi := &file_system_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuRoleProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuRoleProto) ProtoMessage() {}

func (x *MenuRoleProto) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuRoleProto.ProtoReflect.Descriptor instead.
func (*MenuRoleProto) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{11}
}

func (x *MenuRoleProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MenuRoleProto) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *MenuRoleProto) GetRootMenuId() string {
	if x != nil {
		return x.RootMenuId
	}
	return ""
}

func (x *MenuRoleProto) GetMenuId() string {
	if x != nil {
		return x.MenuId
	}
	return ""
}

func (x *MenuRoleProto) GetMenuKey() string {
	if x != nil {
		return x.MenuKey
	}
	return ""
}

func (x *MenuRoleProto) GetMenuLabel() string {
	if x != nil {
		return x.MenuLabel
	}
	return ""
}

func (x *MenuRoleProto) GetCanView() bool {
	if x != nil {
		return x.CanView
	}
	return false
}

func (x *MenuRoleProto) GetCanCreate() bool {
	if x != nil {
		return x.CanCreate
	}
	return false
}

func (x *MenuRoleProto) GetCanEdit() bool {
	if x != nil {
		return x.CanEdit
	}
	return false
}

func (x *MenuRoleProto) GetCanDelete() bool {
	if x != nil {
		return x.CanDelete
	}
	return false
}

func (x *MenuRoleProto) GetCanExport() bool {
	if x != nil {
		return x.CanExport
	}
	return false
}

func (x *MenuRoleProto) GetCanPrint() bool {
	if x != nil {
		return x.CanPrint
	}
	return false
}

func (x *MenuRoleProto) GetDataScope() string {
	if x != nil {
		return x.DataScope
	}
	return ""
}

type RolePermQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	RootMenuId    string                 `protobuf:"bytes,2,opt,name=root_menu_id,json=rootMenuId,proto3" json:"root_menu_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermQueryRequest) Reset() {
	*x = RolePermQueryRequest{}
	mi := &file_system_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermQueryRequest) ProtoMessage() {}

func (x *RolePermQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermQueryRequest.ProtoReflect.Descriptor instead.
func (*RolePermQueryRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{12}
}

func (x *RolePermQueryRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RolePermQueryRequest) GetRootMenuId() string {
	if x != nil {
		return x.RootMenuId
	}
	return ""
}

type RolePermResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Users         []*UserRoleProto       `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	Menus         []*MenuRoleProto       `protobuf:"bytes,4,rep,name=menus,proto3" json:"menus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermResponse) Reset() {
	*x = RolePermResponse{}
	mi := &file_system_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermResponse) ProtoMessage() {}

func (x *RolePermResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermResponse.ProtoReflect.Descriptor instead.
func (*RolePermResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{13}
}

func (x *RolePermResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RolePermResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RolePermResponse) GetUsers() []*UserRoleProto {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *RolePermResponse) GetMenus() []*MenuRoleProto {
	if x != nil {
		return x.Menus
	}
	return nil
}

type RootMenuProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RootMenuId    string                 `protobuf:"bytes,2,opt,name=root_menu_id,json=rootMenuId,proto3" json:"root_menu_id,omitempty"`
	RootMenuKey   string                 `protobuf:"bytes,3,opt,name=root_menu_key,json=rootMenuKey,proto3" json:"root_menu_key,omitempty"`
	RootMenuLabel string                 `protobuf:"bytes,4,opt,name=root_menu_label,json=rootMenuLabel,proto3" json:"root_menu_label,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	OrderSeq      int32                  `protobuf:"varint,6,opt,name=order_seq,json=orderSeq,proto3" json:"order_seq,omitempty"`
	View          bool                   `protobuf:"varint,7,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootMenuProto) Reset() {
	*x = RootMenuProto{}
	mi := &file_system_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootMenuProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootMenuProto) ProtoMessage() {}

func (x *RootMenuProto) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootMenuProto.ProtoReflect.Descriptor instead.
func (*RootMenuProto) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{14}
}

func (x *RootMenuProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RootMenuProto) GetRootMenuId() string {
	if x != nil {
		return x.RootMenuId
	}
	return ""
}

func (x *RootMenuProto) GetRootMenuKey() string {
	if x != nil {
		return x.RootMenuKey
	}
	return ""
}

func (x *RootMenuProto) GetRootMenuLabel() string {
	if x != nil {
		return x.RootMenuLabel
	}
	return ""
}

func (x *RootMenuProto) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *RootMenuProto) GetOrderSeq() int32 {
	if x != nil {
		return x.OrderSeq
	}
	return 0
}

func (x *RootMenuProto) GetView() bool {
	if x != nil {
		return x.View
	}
	return false
}

type MenuProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MenuKey       string                 `protobuf:"bytes,2,opt,name=menu_key,json=menuKey,proto3" json:"menu_key,omitempty"`
	MenuSubRootId string                 `protobuf:"bytes,3,opt,name=menu_sub_root_id,json=menuSubRootId,proto3" json:"menu_sub_root_id,omitempty"`
	MenuRootId    string                 `protobuf:"bytes,4,opt,name=menu_root_id,json=menuRootId,proto3" json:"menu_root_id,omitempty"`
	MenuLabel     string                 `protobuf:"bytes,5,opt,name=menu_label,json=menuLabel,proto3" json:"menu_label,omitempty"`
	MenuLink      string                 `protobuf:"bytes,6,opt,name=menu_link,json=menuLink,proto3" json:"menu_link,omitempty"`
	MenuType      string                 `protobuf:"bytes,7,opt,name=menu_type,json=menuType,proto3" json:"menu_type,omitempty"` // 'submenu' | 'menu'
	Icon          string                 `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	OrderSeq      int32                  `protobuf:"varint,9,opt,name=order_seq,json=orderSeq,proto3" json:"order_seq,omitempty"`
	View          bool                   `protobuf:"varint,10,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuProto) Reset() {
	*x = MenuProto{}
	mi := &file_system_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuProto) ProtoMessage() {}

func (x *MenuProto) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuProto.ProtoReflect.Descriptor instead.
func (*MenuProto) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{15}
}

func (x *MenuProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MenuProto) GetMenuKey() string {
	if x != nil {
		return x.MenuKey
	}
	return ""
}

func (x *MenuProto) GetMenuSubRootId() string {
	if x != nil {
		return x.MenuSubRootId
	}
	return ""
}

func (x *MenuProto) GetMenuRootId() string {
	if x != nil {
		return x.MenuRootId
	}
	return ""
}

func (x *MenuProto) GetMenuLabel() string {
	if x != nil {
		return x.MenuLabel
	}
	return ""
}

func (x *MenuProto) GetMenuLink() string {
	if x != nil {
		return x.MenuLink
	}
	return ""
}

func (x *MenuProto) GetMenuType() string {
	if x != nil {
		return x.MenuType
	}
	return ""
}

func (x *MenuProto) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MenuProto) GetOrderSeq() int32 {
	if x != nil {
		return x.OrderSeq
	}
	return 0
}

func (x *MenuProto) GetView() bool {
	if x != nil {
		return x.View
	}
	return false
}

type StructureQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootMenuId    string                 `protobuf:"bytes,1,opt,name=root_menu_id,json=rootMenuId,proto3" json:"root_menu_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructureQueryRequest) Reset() {
	*x = StructureQueryRequest{}
	mi := &file_system_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructureQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructureQueryRequest) ProtoMessage() {}

func (x *StructureQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructureQueryRequest.ProtoReflect.Descriptor instead.
func (*StructureQueryRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{16}
}

func (x *StructureQueryRequest) GetRootMenuId() string {
	if x != nil {
		return x.RootMenuId
	}
	return ""
}

type StructureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RootMenus     []*RootMenuProto       `protobuf:"bytes,3,rep,name=root_menus,json=rootMenus,proto3" json:"root_menus,omitempty"`
	Menus         []*MenuProto           `protobuf:"bytes,4,rep,name=menus,proto3" json:"menus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructureResponse) Reset() {
	*x = StructureResponse{}
	mi := &file_system_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructureResponse) ProtoMessage() {}

func (x *StructureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructureResponse.ProtoReflect.Descriptor instead.
func (*StructureResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{17}
}

func (x *StructureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StructureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StructureResponse) GetRootMenus() []*RootMenuProto {
	if x != nil {
		return x.RootMenus
	}
	return nil
}

func (x *StructureResponse) GetMenus() []*MenuProto {
	if x != nil {
		return x.Menus
	}
	return nil
}

var File_system_proto protoreflect.FileDescriptor

const file_system_proto_rawDesc = "" +
	"\n" +
	"\fsystem.proto\x12\adatahub\"\xe3\x04\n" +
	"\tUserProto\x12\x19\n" +
	"\buser_seq\x18\x01 \x01(\tR\auserSeq\x12\x1f\n" +
	"\vcompany_seq\x18\x02 \x01(\x05R\n" +
	"companySeq\x12\x15\n" +
	"\x06idx_no\x18\x03 \x01(\x05R\x05idxNo\x12\x15\n" +
	"\x06emp_id\x18\x04 \x01(\tR\x05empId\x12\x19\n" +
	"\bemp_code\x18\x05 \x01(\tR\aempCode\x12\x19\n" +
	"\bemp_name\x18\x06 \x01(\tR\aempName\x12\x1b\n" +
	"\tdept_name\x18\a \x01(\tR\bdeptName\x12!\n" +
	"\fmanager_name\x18\b \x01(\tR\vmanagerName\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_type\x18\n" +
	" \x01(\x05R\buserType\x12\x1b\n" +
	"\tuser_name\x18\v \x01(\tR\buserName\x12\x14\n" +
	"\x05email\x18\f \x01(\tR\x05email\x12\x1f\n" +
	"\vcheck_pass1\x18\r \x01(\bR\n" +
	"checkPass1\x12\x1d\n" +
	"\n" +
	"status_acc\x18\x0e \x01(\bR\tstatusAcc\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12\x16\n" +
	"\x06active\x18\x10 \x01(\bR\x06active\x12!\n" +
	"\flanguage_seq\x18\x11 \x01(\x05R\vlanguageSeq\x12\x1d\n" +
	"\n" +
	"created_by\x18\x12 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\x13 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x14 \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\tR\tupdatedAt\"\xb0\x01\n" +
	"\x10UserQueryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"status_acc\x18\x03 \x01(\tR\tstatusAcc\x12\x16\n" +
	"\x06active\x18\x04 \x01(\tR\x06active\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\xd2\x01\n" +
	"\x10UserListResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x03 \x03(\v2\x12.datahub.UserProtoR\x04data\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x12\x1b\n" +
	"\ttotal_all\x18\x05 \x01(\x03R\btotalAll\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\"=\n" +
	"\x11UserMutateRequest\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.datahub.UserProtoR\x05users\"p\n" +
	"\x12UserMutateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x03 \x03(\v2\x12.datahub.UserProtoR\x04data\"\xe3\x01\n" +
	"\x0eRoleGroupProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12&\n" +
	"\x0fcreated_by_name\x18\x04 \x01(\tR\rcreatedByName\x12\x15\n" +
	"\x06idx_no\x18\x05 \x01(\x05R\x05idxNo\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"b\n" +
	"\x15RoleGroupQueryRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x8e\x01\n" +
	"\x15RoleGroupListResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x03(\v2\x17.datahub.RoleGroupProtoR\x04data\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"I\n" +
	"\x16RoleGroupMutateRequest\x12/\n" +
	"\x06groups\x18\x01 \x03(\v2\x17.datahub.RoleGroupProtoR\x06groups\"z\n" +
	"\x17RoleGroupMutateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x03(\v2\x17.datahub.RoleGroupProtoR\x04data\"\xae\x01\n" +
	"\rUserRoleProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x05 \x01(\tR\tgroupName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\xfe\x02\n" +
	"\rMenuRoleProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12 \n" +
	"\froot_menu_id\x18\x03 \x01(\tR\n" +
	"rootMenuId\x12\x17\n" +
	"\amenu_id\x18\x04 \x01(\tR\x06menuId\x12\x19\n" +
	"\bmenu_key\x18\x05 \x01(\tR\amenuKey\x12\x1d\n" +
	"\n" +
	"menu_label\x18\x06 \x01(\tR\tmenuLabel\x12\x19\n" +
	"\bcan_view\x18\a \x01(\bR\acanView\x12\x1d\n" +
	"\n" +
	"can_create\x18\b \x01(\bR\tcanCreate\x12\x19\n" +
	"\bcan_edit\x18\t \x01(\bR\acanEdit\x12\x1d\n" +
	"\n" +
	"can_delete\x18\n" +
	" \x01(\bR\tcanDelete\x12\x1d\n" +
	"\n" +
	"can_export\x18\v \x01(\bR\tcanExport\x12\x1b\n" +
	"\tcan_print\x18\f \x01(\bR\bcanPrint\x12\x1d\n" +
	"\n" +
	"data_scope\x18\r \x01(\tR\tdataScope\"S\n" +
	"\x14RolePermQueryRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12 \n" +
	"\froot_menu_id\x18\x02 \x01(\tR\n" +
	"rootMenuId\"\xa2\x01\n" +
	"\x10RolePermResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x05users\x18\x03 \x03(\v2\x16.datahub.UserRoleProtoR\x05users\x12,\n" +
	"\x05menus\x18\x04 \x03(\v2\x16.datahub.MenuRoleProtoR\x05menus\"\xd2\x01\n" +
	"\rRootMenuProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\froot_menu_id\x18\x02 \x01(\tR\n" +
	"rootMenuId\x12\"\n" +
	"\rroot_menu_key\x18\x03 \x01(\tR\vrootMenuKey\x12&\n" +
	"\x0froot_menu_label\x18\x04 \x01(\tR\rrootMenuLabel\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x1b\n" +
	"\torder_seq\x18\x06 \x01(\x05R\borderSeq\x12\x12\n" +
	"\x04view\x18\a \x01(\bR\x04view\"\x9f\x02\n" +
	"\tMenuProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bmenu_key\x18\x02 \x01(\tR\amenuKey\x12'\n" +
	"\x10menu_sub_root_id\x18\x03 \x01(\tR\rmenuSubRootId\x12 \n" +
	"\fmenu_root_id\x18\x04 \x01(\tR\n" +
	"menuRootId\x12\x1d\n" +
	"\n" +
	"menu_label\x18\x05 \x01(\tR\tmenuLabel\x12\x1b\n" +
	"\tmenu_link\x18\x06 \x01(\tR\bmenuLink\x12\x1b\n" +
	"\tmenu_type\x18\a \x01(\tR\bmenuType\x12\x12\n" +
	"\x04icon\x18\b \x01(\tR\x04icon\x12\x1b\n" +
	"\torder_seq\x18\t \x01(\x05R\borderSeq\x12\x12\n" +
	"\x04view\x18\n" +
	" \x01(\bR\x04view\"9\n" +
	"\x15StructureQueryRequest\x12 \n" +
	"\froot_menu_id\x18\x01 \x01(\tR\n" +
	"rootMenuId\"\xa8\x01\n" +
	"\x11StructureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\n" +
	"root_menus\x18\x03 \x03(\v2\x16.datahub.RootMenuProtoR\trootMenus\x12(\n" +
	"\x05menus\x18\x04 \x03(\v2\x12.datahub.MenuProtoR\x05menus2\xf4\x06\n" +
	"\x11SystemDataService\x12B\n" +
	"\n" +
	"QueryUsers\x12\x19.datahub.UserQueryRequest\x1a\x19.datahub.UserListResponse\x12C\n" +
	"\bAddUsers\x12\x1a.datahub.UserMutateRequest\x1a\x1b.datahub.UserMutateResponse\x12F\n" +
	"\vUpdateUsers\x12\x1a.datahub.UserMutateRequest\x1a\x1b.datahub.UserMutateResponse\x12F\n" +
	"\vDeleteUsers\x12\x1a.datahub.UserMutateRequest\x1a\x1b.datahub.UserMutateResponse\x12Q\n" +
	"\x0fQueryRoleGroups\x12\x1e.datahub.RoleGroupQueryRequest\x1a\x1e.datahub.RoleGroupListResponse\x12R\n" +
	"\rAddRoleGroups\x12\x1f.datahub.RoleGroupMutateRequest\x1a .datahub.RoleGroupMutateResponse\x12U\n" +
	"\x10UpdateRoleGroups\x12\x1f.datahub.RoleGroupMutateRequest\x1a .datahub.RoleGroupMutateResponse\x12U\n" +
	"\x10DeleteRoleGroups\x12\x1f.datahub.RoleGroupMutateRequest\x1a .datahub.RoleGroupMutateResponse\x12P\n" +
	"\x14QueryRolePermissions\x12\x1d.datahub.RolePermQueryRequest\x1a\x19.datahub.RolePermResponse\x12K\n" +
	"\x13SaveRolePermissions\x12\x19.datahub.RolePermResponse\x1a\x19.datahub.RolePermResponse\x12R\n" +
	"\x14QuerySystemStructure\x12\x1e.datahub.StructureQueryRequest\x1a\x1a.datahub.StructureResponseB\x1cZ\x1aservice-datahub/pb/datahubb\x06proto3"

var (
	file_system_proto_rawDescOnce sync.Once
	file_system_proto_rawDescData []byte
)

func file_system_proto_rawDescGZIP() []byte {
	file_system_proto_rawDescOnce.Do(func() {
		file_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_proto_rawDesc), len(file_system_proto_rawDesc)))
	})
	return file_system_proto_rawDescData
}

var file_system_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_system_proto_goTypes = []any{
	(*UserProto)(nil),               // 0: datahub.UserProto
	(*UserQueryRequest)(nil),        // 1: datahub.UserQueryRequest
	(*UserListResponse)(nil),        // 2: datahub.UserListResponse
	(*UserMutateRequest)(nil),       // 3: datahub.UserMutateRequest
	(*UserMutateResponse)(nil),      // 4: datahub.UserMutateResponse
	(*RoleGroupProto)(nil),          // 5: datahub.RoleGroupProto
	(*RoleGroupQueryRequest)(nil),   // 6: datahub.RoleGroupQueryRequest
	(*RoleGroupListResponse)(nil),   // 7: datahub.RoleGroupListResponse
	(*RoleGroupMutateRequest)(nil),  // 8: datahub.RoleGroupMutateRequest
	(*RoleGroupMutateResponse)(nil), // 9: datahub.RoleGroupMutateResponse
	(*UserRoleProto)(nil),           // 10: datahub.UserRoleProto
	(*MenuRoleProto)(nil),           // 11: datahub.MenuRoleProto
	(*RolePermQueryRequest)(nil),    // 12: datahub.RolePermQueryRequest
	(*RolePermResponse)(nil),        // 13: datahub.RolePermResponse
	(*RootMenuProto)(nil),           // 14: datahub.RootMenuProto
	(*MenuProto)(nil),               // 15: datahub.MenuProto
	(*StructureQueryRequest)(nil),   // 16: datahub.StructureQueryRequest
	(*StructureResponse)(nil),       // 17: datahub.StructureResponse
}
var file_system_proto_depIdxs = []int32{
	0,  // 0: datahub.UserListResponse.data:type_name -> datahub.UserProto
	0,  // 1: datahub.UserMutateRequest.users:type_name -> datahub.UserProto
	0,  // 2: datahub.UserMutateResponse.data:type_name -> datahub.UserProto
	5,  // 3: datahub.RoleGroupListResponse.data:type_name -> datahub.RoleGroupProto
	5,  // 4: datahub.RoleGroupMutateRequest.groups:type_name -> datahub.RoleGroupProto
	5,  // 5: datahub.RoleGroupMutateResponse.data:type_name -> datahub.RoleGroupProto
	10, // 6: datahub.RolePermResponse.users:type_name -> datahub.UserRoleProto
	11, // 7: datahub.RolePermResponse.menus:type_name -> datahub.MenuRoleProto
	14, // 8: datahub.StructureResponse.root_menus:type_name -> datahub.RootMenuProto
	15, // 9: datahub.StructureResponse.menus:type_name -> datahub.MenuProto
	1,  // 10: datahub.SystemDataService.QueryUsers:input_type -> datahub.UserQueryRequest
	3,  // 11: datahub.SystemDataService.AddUsers:input_type -> datahub.UserMutateRequest
	3,  // 12: datahub.SystemDataService.UpdateUsers:input_type -> datahub.UserMutateRequest
	3,  // 13: datahub.SystemDataService.DeleteUsers:input_type -> datahub.UserMutateRequest
	6,  // 14: datahub.SystemDataService.QueryRoleGroups:input_type -> datahub.RoleGroupQueryRequest
	8,  // 15: datahub.SystemDataService.AddRoleGroups:input_type -> datahub.RoleGroupMutateRequest
	8,  // 16: datahub.SystemDataService.UpdateRoleGroups:input_type -> datahub.RoleGroupMutateRequest
	8,  // 17: datahub.SystemDataService.DeleteRoleGroups:input_type -> datahub.RoleGroupMutateRequest
	12, // 18: datahub.SystemDataService.QueryRolePermissions:input_type -> datahub.RolePermQueryRequest
	13, // 19: datahub.SystemDataService.SaveRolePermissions:input_type -> datahub.RolePermResponse
	16, // 20: datahub.SystemDataService.QuerySystemStructure:input_type -> datahub.StructureQueryRequest
	2,  // 21: datahub.SystemDataService.QueryUsers:output_type -> datahub.UserListResponse
	4,  // 22: datahub.SystemDataService.AddUsers:output_type -> datahub.UserMutateResponse
	4,  // 23: datahub.SystemDataService.UpdateUsers:output_type -> datahub.UserMutateResponse
	4,  // 24: datahub.SystemDataService.DeleteUsers:output_type -> datahub.UserMutateResponse
	7,  // 25: datahub.SystemDataService.QueryRoleGroups:output_type -> datahub.RoleGroupListResponse
	9,  // 26: datahub.SystemDataService.AddRoleGroups:output_type -> datahub.RoleGroupMutateResponse
	9,  // 27: datahub.SystemDataService.UpdateRoleGroups:output_type -> datahub.RoleGroupMutateResponse
	9,  // 28: datahub.SystemDataService.DeleteRoleGroups:output_type -> datahub.RoleGroupMutateResponse
	13, // 29: datahub.SystemDataService.QueryRolePermissions:output_type -> datahub.RolePermResponse
	13, // 30: datahub.SystemDataService.SaveRolePermissions:output_type -> datahub.RolePermResponse
	17, // 31: datahub.SystemDataService.QuerySystemStructure:output_type -> datahub.StructureResponse
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_system_proto_init() }
func file_system_proto_init() {
	if File_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_proto_rawDesc), len(file_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_proto_goTypes,
		DependencyIndexes: file_system_proto_depIdxs,
		MessageInfos:      file_system_proto_msgTypes,
	}.Build()
	File_system_proto = out.File
	file_system_proto_goTypes = nil
	file_system_proto_depIdxs = nil
}
