syntax = "proto3";

package lookup.wh.help_item;

option go_package = "service-lookup/proto/lookup/wh/help_item;help_item";

service HelpItemService {
  rpc ItemsH (ItemHRequest) returns (Response);
}

message ItemHResult {
  string KeyItem1 = 1;
  string KeyItem2 = 2;
  string KeyItem3 = 3;
}
message ItemHRequest {
  ItemHResult result = 1;
  map<string, string> metadata = 2;
}

message Response {
  bool   success = 1;
  string message = 2;
  string data    = 3;
  string errors  = 4;
  string page = 5;
}
