syntax = "proto3";

package lookup.auth.help_lang;

option go_package = "service-lookup/proto/lookup/auth/help_lang;help_lang";

service LookupLangDictService {
  rpc LangDictH (Empty) returns (Response);
  rpc DictVersionQ (Empty) returns (Response);
}

message EmptyResult {
  string KeyItem1 = 1;
  string KeyItem2 = 2;
  string KeyItem3 = 3;
}
message Empty {
  EmptyResult result = 1;
  map<string, string> metadata = 2;
}

message Response {
  bool   success = 1;
  string message = 2;
  string data    = 3;
  string errors  = 4;
  string page = 5;
}
