// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: users/technique/tbl_grp.proto

package tbl_grp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TblGrpAResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdxNo         int32                  `protobuf:"varint,1,opt,name=IdxNo,proto3" json:"IdxNo,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,2,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,3,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	KeyCode       string                 `protobuf:"bytes,4,opt,name=KeyCode,proto3" json:"KeyCode,omitempty"`
	TableName     string                 `protobuf:"bytes,5,opt,name=TableName,proto3" json:"TableName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TblGrpAResult) Reset() {
	*x = TblGrpAResult{}
	mi := &file_users_technique_tbl_grp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TblGrpAResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TblGrpAResult) ProtoMessage() {}

func (x *TblGrpAResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_technique_tbl_grp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TblGrpAResult.ProtoReflect.Descriptor instead.
func (*TblGrpAResult) Descriptor() ([]byte, []int) {
	return file_users_technique_tbl_grp_proto_rawDescGZIP(), []int{0}
}

func (x *TblGrpAResult) GetIdxNo() int32 {
	if x != nil {
		return x.IdxNo
	}
	return 0
}

func (x *TblGrpAResult) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *TblGrpAResult) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *TblGrpAResult) GetKeyCode() string {
	if x != nil {
		return x.KeyCode
	}
	return ""
}

func (x *TblGrpAResult) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type TblGrpUResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdxNo         int32                  `protobuf:"varint,1,opt,name=IdxNo,proto3" json:"IdxNo,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,2,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	KeyCode       string                 `protobuf:"bytes,3,opt,name=KeyCode,proto3" json:"KeyCode,omitempty"`
	TableName     string                 `protobuf:"bytes,4,opt,name=TableName,proto3" json:"TableName,omitempty"`
	IdSeq         string                 `protobuf:"bytes,5,opt,name=IdSeq,proto3" json:"IdSeq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TblGrpUResult) Reset() {
	*x = TblGrpUResult{}
	mi := &file_users_technique_tbl_grp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TblGrpUResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TblGrpUResult) ProtoMessage() {}

func (x *TblGrpUResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_technique_tbl_grp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TblGrpUResult.ProtoReflect.Descriptor instead.
func (*TblGrpUResult) Descriptor() ([]byte, []int) {
	return file_users_technique_tbl_grp_proto_rawDescGZIP(), []int{1}
}

func (x *TblGrpUResult) GetIdxNo() int32 {
	if x != nil {
		return x.IdxNo
	}
	return 0
}

func (x *TblGrpUResult) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *TblGrpUResult) GetKeyCode() string {
	if x != nil {
		return x.KeyCode
	}
	return ""
}

func (x *TblGrpUResult) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *TblGrpUResult) GetIdSeq() string {
	if x != nil {
		return x.IdSeq
	}
	return ""
}

type TblGrpDResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdxNo         int32                  `protobuf:"varint,1,opt,name=IdxNo,proto3" json:"IdxNo,omitempty"`
	IdSeq         string                 `protobuf:"bytes,2,opt,name=IdSeq,proto3" json:"IdSeq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TblGrpDResult) Reset() {
	*x = TblGrpDResult{}
	mi := &file_users_technique_tbl_grp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TblGrpDResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TblGrpDResult) ProtoMessage() {}

func (x *TblGrpDResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_technique_tbl_grp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TblGrpDResult.ProtoReflect.Descriptor instead.
func (*TblGrpDResult) Descriptor() ([]byte, []int) {
	return file_users_technique_tbl_grp_proto_rawDescGZIP(), []int{2}
}

func (x *TblGrpDResult) GetIdxNo() int32 {
	if x != nil {
		return x.IdxNo
	}
	return 0
}

func (x *TblGrpDResult) GetIdSeq() string {
	if x != nil {
		return x.IdSeq
	}
	return ""
}

type TblGrpQResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyItem1      string                 `protobuf:"bytes,1,opt,name=KeyItem1,proto3" json:"KeyItem1,omitempty"`
	KeyItem2      string                 `protobuf:"bytes,2,opt,name=KeyItem2,proto3" json:"KeyItem2,omitempty"`
	KeyItem3      string                 `protobuf:"bytes,3,opt,name=KeyItem3,proto3" json:"KeyItem3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TblGrpQResult) Reset() {
	*x = TblGrpQResult{}
	mi := &file_users_technique_tbl_grp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TblGrpQResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TblGrpQResult) ProtoMessage() {}

func (x *TblGrpQResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_technique_tbl_grp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TblGrpQResult.ProtoReflect.Descriptor instead.
func (*TblGrpQResult) Descriptor() ([]byte, []int) {
	return file_users_technique_tbl_grp_proto_rawDescGZIP(), []int{3}
}

func (x *TblGrpQResult) GetKeyItem1() string {
	if x != nil {
		return x.KeyItem1
	}
	return ""
}

func (x *TblGrpQResult) GetKeyItem2() string {
	if x != nil {
		return x.KeyItem2
	}
	return ""
}

func (x *TblGrpQResult) GetKeyItem3() string {
	if x != nil {
		return x.KeyItem3
	}
	return ""
}

type TblGrpARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*TblGrpAResult       `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TblGrpARequest) Reset() {
	*x = TblGrpARequest{}
	mi := &file_users_technique_tbl_grp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TblGrpARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TblGrpARequest) ProtoMessage() {}

func (x *TblGrpARequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_technique_tbl_grp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TblGrpARequest.ProtoReflect.Descriptor instead.
func (*TblGrpARequest) Descriptor() ([]byte, []int) {
	return file_users_technique_tbl_grp_proto_rawDescGZIP(), []int{4}
}

func (x *TblGrpARequest) GetResult() []*TblGrpAResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TblGrpARequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TblGrpURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*TblGrpUResult       `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TblGrpURequest) Reset() {
	*x = TblGrpURequest{}
	mi := &file_users_technique_tbl_grp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TblGrpURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TblGrpURequest) ProtoMessage() {}

func (x *TblGrpURequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_technique_tbl_grp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TblGrpURequest.ProtoReflect.Descriptor instead.
func (*TblGrpURequest) Descriptor() ([]byte, []int) {
	return file_users_technique_tbl_grp_proto_rawDescGZIP(), []int{5}
}

func (x *TblGrpURequest) GetResult() []*TblGrpUResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TblGrpURequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TblGrpDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*TblGrpDResult       `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TblGrpDRequest) Reset() {
	*x = TblGrpDRequest{}
	mi := &file_users_technique_tbl_grp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TblGrpDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TblGrpDRequest) ProtoMessage() {}

func (x *TblGrpDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_technique_tbl_grp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TblGrpDRequest.ProtoReflect.Descriptor instead.
func (*TblGrpDRequest) Descriptor() ([]byte, []int) {
	return file_users_technique_tbl_grp_proto_rawDescGZIP(), []int{6}
}

func (x *TblGrpDRequest) GetResult() []*TblGrpDResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TblGrpDRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TblGrpQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *TblGrpQResult         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TblGrpQRequest) Reset() {
	*x = TblGrpQRequest{}
	mi := &file_users_technique_tbl_grp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TblGrpQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TblGrpQRequest) ProtoMessage() {}

func (x *TblGrpQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_technique_tbl_grp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TblGrpQRequest.ProtoReflect.Descriptor instead.
func (*TblGrpQRequest) Descriptor() ([]byte, []int) {
	return file_users_technique_tbl_grp_proto_rawDescGZIP(), []int{7}
}

func (x *TblGrpQRequest) GetResult() *TblGrpQResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TblGrpQRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Page          string                 `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_users_technique_tbl_grp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_users_technique_tbl_grp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_users_technique_tbl_grp_proto_rawDescGZIP(), []int{8}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Response) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

var File_users_technique_tbl_grp_proto protoreflect.FileDescriptor

const file_users_technique_tbl_grp_proto_rawDesc = "" +
	"\n" +
	"\x1dusers/technique/tbl_grp.proto\x12\x17users.technique.tbl_grp\"\x99\x01\n" +
	"\rTblGrpAResult\x12\x14\n" +
	"\x05IdxNo\x18\x01 \x01(\x05R\x05IdxNo\x12\x1c\n" +
	"\tCreatedBy\x18\x02 \x01(\tR\tCreatedBy\x12\x1c\n" +
	"\tUpdatedBy\x18\x03 \x01(\tR\tUpdatedBy\x12\x18\n" +
	"\aKeyCode\x18\x04 \x01(\tR\aKeyCode\x12\x1c\n" +
	"\tTableName\x18\x05 \x01(\tR\tTableName\"\x91\x01\n" +
	"\rTblGrpUResult\x12\x14\n" +
	"\x05IdxNo\x18\x01 \x01(\x05R\x05IdxNo\x12\x1c\n" +
	"\tUpdatedBy\x18\x02 \x01(\tR\tUpdatedBy\x12\x18\n" +
	"\aKeyCode\x18\x03 \x01(\tR\aKeyCode\x12\x1c\n" +
	"\tTableName\x18\x04 \x01(\tR\tTableName\x12\x14\n" +
	"\x05IdSeq\x18\x05 \x01(\tR\x05IdSeq\";\n" +
	"\rTblGrpDResult\x12\x14\n" +
	"\x05IdxNo\x18\x01 \x01(\x05R\x05IdxNo\x12\x14\n" +
	"\x05IdSeq\x18\x02 \x01(\tR\x05IdSeq\"c\n" +
	"\rTblGrpQResult\x12\x1a\n" +
	"\bKeyItem1\x18\x01 \x01(\tR\bKeyItem1\x12\x1a\n" +
	"\bKeyItem2\x18\x02 \x01(\tR\bKeyItem2\x12\x1a\n" +
	"\bKeyItem3\x18\x03 \x01(\tR\bKeyItem3\"\xe0\x01\n" +
	"\x0eTblGrpARequest\x12>\n" +
	"\x06result\x18\x01 \x03(\v2&.users.technique.tbl_grp.TblGrpAResultR\x06result\x12Q\n" +
	"\bmetadata\x18\x02 \x03(\v25.users.technique.tbl_grp.TblGrpARequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe0\x01\n" +
	"\x0eTblGrpURequest\x12>\n" +
	"\x06result\x18\x01 \x03(\v2&.users.technique.tbl_grp.TblGrpUResultR\x06result\x12Q\n" +
	"\bmetadata\x18\x02 \x03(\v25.users.technique.tbl_grp.TblGrpURequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe0\x01\n" +
	"\x0eTblGrpDRequest\x12>\n" +
	"\x06result\x18\x01 \x03(\v2&.users.technique.tbl_grp.TblGrpDResultR\x06result\x12Q\n" +
	"\bmetadata\x18\x02 \x03(\v25.users.technique.tbl_grp.TblGrpDRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe0\x01\n" +
	"\x0eTblGrpQRequest\x12>\n" +
	"\x06result\x18\x01 \x01(\v2&.users.technique.tbl_grp.TblGrpQResultR\x06result\x12Q\n" +
	"\bmetadata\x18\x02 \x03(\v25.users.technique.tbl_grp.TblGrpQRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x12\n" +
	"\x04page\x18\x04 \x01(\tR\x04page2\xeb\x02\n" +
	"\rTblGrpService\x12U\n" +
	"\aTblGrpA\x12'.users.technique.tbl_grp.TblGrpARequest\x1a!.users.technique.tbl_grp.Response\x12U\n" +
	"\aTblGrpU\x12'.users.technique.tbl_grp.TblGrpURequest\x1a!.users.technique.tbl_grp.Response\x12U\n" +
	"\aTblGrpD\x12'.users.technique.tbl_grp.TblGrpDRequest\x1a!.users.technique.tbl_grp.Response\x12U\n" +
	"\aTblGrpQ\x12'.users.technique.tbl_grp.TblGrpQRequest\x1a!.users.technique.tbl_grp.ResponseB+Z)server-core/proto/users/technique/tbl_grpb\x06proto3"

var (
	file_users_technique_tbl_grp_proto_rawDescOnce sync.Once
	file_users_technique_tbl_grp_proto_rawDescData []byte
)

func file_users_technique_tbl_grp_proto_rawDescGZIP() []byte {
	file_users_technique_tbl_grp_proto_rawDescOnce.Do(func() {
		file_users_technique_tbl_grp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_technique_tbl_grp_proto_rawDesc), len(file_users_technique_tbl_grp_proto_rawDesc)))
	})
	return file_users_technique_tbl_grp_proto_rawDescData
}

var file_users_technique_tbl_grp_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_users_technique_tbl_grp_proto_goTypes = []any{
	(*TblGrpAResult)(nil),  // 0: users.technique.tbl_grp.TblGrpAResult
	(*TblGrpUResult)(nil),  // 1: users.technique.tbl_grp.TblGrpUResult
	(*TblGrpDResult)(nil),  // 2: users.technique.tbl_grp.TblGrpDResult
	(*TblGrpQResult)(nil),  // 3: users.technique.tbl_grp.TblGrpQResult
	(*TblGrpARequest)(nil), // 4: users.technique.tbl_grp.TblGrpARequest
	(*TblGrpURequest)(nil), // 5: users.technique.tbl_grp.TblGrpURequest
	(*TblGrpDRequest)(nil), // 6: users.technique.tbl_grp.TblGrpDRequest
	(*TblGrpQRequest)(nil), // 7: users.technique.tbl_grp.TblGrpQRequest
	(*Response)(nil),       // 8: users.technique.tbl_grp.Response
	nil,                    // 9: users.technique.tbl_grp.TblGrpARequest.MetadataEntry
	nil,                    // 10: users.technique.tbl_grp.TblGrpURequest.MetadataEntry
	nil,                    // 11: users.technique.tbl_grp.TblGrpDRequest.MetadataEntry
	nil,                    // 12: users.technique.tbl_grp.TblGrpQRequest.MetadataEntry
}
var file_users_technique_tbl_grp_proto_depIdxs = []int32{
	0,  // 0: users.technique.tbl_grp.TblGrpARequest.result:type_name -> users.technique.tbl_grp.TblGrpAResult
	9,  // 1: users.technique.tbl_grp.TblGrpARequest.metadata:type_name -> users.technique.tbl_grp.TblGrpARequest.MetadataEntry
	1,  // 2: users.technique.tbl_grp.TblGrpURequest.result:type_name -> users.technique.tbl_grp.TblGrpUResult
	10, // 3: users.technique.tbl_grp.TblGrpURequest.metadata:type_name -> users.technique.tbl_grp.TblGrpURequest.MetadataEntry
	2,  // 4: users.technique.tbl_grp.TblGrpDRequest.result:type_name -> users.technique.tbl_grp.TblGrpDResult
	11, // 5: users.technique.tbl_grp.TblGrpDRequest.metadata:type_name -> users.technique.tbl_grp.TblGrpDRequest.MetadataEntry
	3,  // 6: users.technique.tbl_grp.TblGrpQRequest.result:type_name -> users.technique.tbl_grp.TblGrpQResult
	12, // 7: users.technique.tbl_grp.TblGrpQRequest.metadata:type_name -> users.technique.tbl_grp.TblGrpQRequest.MetadataEntry
	4,  // 8: users.technique.tbl_grp.TblGrpService.TblGrpA:input_type -> users.technique.tbl_grp.TblGrpARequest
	5,  // 9: users.technique.tbl_grp.TblGrpService.TblGrpU:input_type -> users.technique.tbl_grp.TblGrpURequest
	6,  // 10: users.technique.tbl_grp.TblGrpService.TblGrpD:input_type -> users.technique.tbl_grp.TblGrpDRequest
	7,  // 11: users.technique.tbl_grp.TblGrpService.TblGrpQ:input_type -> users.technique.tbl_grp.TblGrpQRequest
	8,  // 12: users.technique.tbl_grp.TblGrpService.TblGrpA:output_type -> users.technique.tbl_grp.Response
	8,  // 13: users.technique.tbl_grp.TblGrpService.TblGrpU:output_type -> users.technique.tbl_grp.Response
	8,  // 14: users.technique.tbl_grp.TblGrpService.TblGrpD:output_type -> users.technique.tbl_grp.Response
	8,  // 15: users.technique.tbl_grp.TblGrpService.TblGrpQ:output_type -> users.technique.tbl_grp.Response
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_users_technique_tbl_grp_proto_init() }
func file_users_technique_tbl_grp_proto_init() {
	if File_users_technique_tbl_grp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_technique_tbl_grp_proto_rawDesc), len(file_users_technique_tbl_grp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_technique_tbl_grp_proto_goTypes,
		DependencyIndexes: file_users_technique_tbl_grp_proto_depIdxs,
		MessageInfos:      file_users_technique_tbl_grp_proto_msgTypes,
	}.Build()
	File_users_technique_tbl_grp_proto = out.File
	file_users_technique_tbl_grp_proto_goTypes = nil
	file_users_technique_tbl_grp_proto_depIdxs = nil
}
