// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: users/roles/perm_resource_fields.proto

package perm_resource_fields

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PermResourceFieldsService_PermResourceFieldsA_FullMethodName = "/users.roles.perm_resource_fields.PermResourceFieldsService/PermResourceFieldsA"
	PermResourceFieldsService_PermResourceFieldsU_FullMethodName = "/users.roles.perm_resource_fields.PermResourceFieldsService/PermResourceFieldsU"
	PermResourceFieldsService_PermResourceFieldsD_FullMethodName = "/users.roles.perm_resource_fields.PermResourceFieldsService/PermResourceFieldsD"
	PermResourceFieldsService_PermResourceFieldsQ_FullMethodName = "/users.roles.perm_resource_fields.PermResourceFieldsService/PermResourceFieldsQ"
)

// PermResourceFieldsServiceClient is the client API for PermResourceFieldsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PermResourceFieldsServiceClient interface {
	PermResourceFieldsA(ctx context.Context, in *PermResourceFieldsARequest, opts ...grpc.CallOption) (*Response, error)
	PermResourceFieldsU(ctx context.Context, in *PermResourceFieldsURequest, opts ...grpc.CallOption) (*Response, error)
	PermResourceFieldsD(ctx context.Context, in *PermResourceFieldsDRequest, opts ...grpc.CallOption) (*Response, error)
	PermResourceFieldsQ(ctx context.Context, in *PermResourceFieldsQRequest, opts ...grpc.CallOption) (*Response, error)
}

type permResourceFieldsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPermResourceFieldsServiceClient(cc grpc.ClientConnInterface) PermResourceFieldsServiceClient {
	return &permResourceFieldsServiceClient{cc}
}

func (c *permResourceFieldsServiceClient) PermResourceFieldsA(ctx context.Context, in *PermResourceFieldsARequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PermResourceFieldsService_PermResourceFieldsA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permResourceFieldsServiceClient) PermResourceFieldsU(ctx context.Context, in *PermResourceFieldsURequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PermResourceFieldsService_PermResourceFieldsU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permResourceFieldsServiceClient) PermResourceFieldsD(ctx context.Context, in *PermResourceFieldsDRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PermResourceFieldsService_PermResourceFieldsD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permResourceFieldsServiceClient) PermResourceFieldsQ(ctx context.Context, in *PermResourceFieldsQRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PermResourceFieldsService_PermResourceFieldsQ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermResourceFieldsServiceServer is the server API for PermResourceFieldsService service.
// All implementations must embed UnimplementedPermResourceFieldsServiceServer
// for forward compatibility.
type PermResourceFieldsServiceServer interface {
	PermResourceFieldsA(context.Context, *PermResourceFieldsARequest) (*Response, error)
	PermResourceFieldsU(context.Context, *PermResourceFieldsURequest) (*Response, error)
	PermResourceFieldsD(context.Context, *PermResourceFieldsDRequest) (*Response, error)
	PermResourceFieldsQ(context.Context, *PermResourceFieldsQRequest) (*Response, error)
	mustEmbedUnimplementedPermResourceFieldsServiceServer()
}

// UnimplementedPermResourceFieldsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPermResourceFieldsServiceServer struct{}

func (UnimplementedPermResourceFieldsServiceServer) PermResourceFieldsA(context.Context, *PermResourceFieldsARequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method PermResourceFieldsA not implemented")
}
func (UnimplementedPermResourceFieldsServiceServer) PermResourceFieldsU(context.Context, *PermResourceFieldsURequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method PermResourceFieldsU not implemented")
}
func (UnimplementedPermResourceFieldsServiceServer) PermResourceFieldsD(context.Context, *PermResourceFieldsDRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method PermResourceFieldsD not implemented")
}
func (UnimplementedPermResourceFieldsServiceServer) PermResourceFieldsQ(context.Context, *PermResourceFieldsQRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method PermResourceFieldsQ not implemented")
}
func (UnimplementedPermResourceFieldsServiceServer) mustEmbedUnimplementedPermResourceFieldsServiceServer() {
}
func (UnimplementedPermResourceFieldsServiceServer) testEmbeddedByValue() {}

// UnsafePermResourceFieldsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermResourceFieldsServiceServer will
// result in compilation errors.
type UnsafePermResourceFieldsServiceServer interface {
	mustEmbedUnimplementedPermResourceFieldsServiceServer()
}

func RegisterPermResourceFieldsServiceServer(s grpc.ServiceRegistrar, srv PermResourceFieldsServiceServer) {
	// If the following call panics, it indicates UnimplementedPermResourceFieldsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PermResourceFieldsService_ServiceDesc, srv)
}

func _PermResourceFieldsService_PermResourceFieldsA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermResourceFieldsARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermResourceFieldsServiceServer).PermResourceFieldsA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermResourceFieldsService_PermResourceFieldsA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermResourceFieldsServiceServer).PermResourceFieldsA(ctx, req.(*PermResourceFieldsARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermResourceFieldsService_PermResourceFieldsU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermResourceFieldsURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermResourceFieldsServiceServer).PermResourceFieldsU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermResourceFieldsService_PermResourceFieldsU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermResourceFieldsServiceServer).PermResourceFieldsU(ctx, req.(*PermResourceFieldsURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermResourceFieldsService_PermResourceFieldsD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermResourceFieldsDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermResourceFieldsServiceServer).PermResourceFieldsD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermResourceFieldsService_PermResourceFieldsD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermResourceFieldsServiceServer).PermResourceFieldsD(ctx, req.(*PermResourceFieldsDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermResourceFieldsService_PermResourceFieldsQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermResourceFieldsQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermResourceFieldsServiceServer).PermResourceFieldsQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermResourceFieldsService_PermResourceFieldsQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermResourceFieldsServiceServer).PermResourceFieldsQ(ctx, req.(*PermResourceFieldsQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PermResourceFieldsService_ServiceDesc is the grpc.ServiceDesc for PermResourceFieldsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PermResourceFieldsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.roles.perm_resource_fields.PermResourceFieldsService",
	HandlerType: (*PermResourceFieldsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PermResourceFieldsA",
			Handler:    _PermResourceFieldsService_PermResourceFieldsA_Handler,
		},
		{
			MethodName: "PermResourceFieldsU",
			Handler:    _PermResourceFieldsService_PermResourceFieldsU_Handler,
		},
		{
			MethodName: "PermResourceFieldsD",
			Handler:    _PermResourceFieldsService_PermResourceFieldsD_Handler,
		},
		{
			MethodName: "PermResourceFieldsQ",
			Handler:    _PermResourceFieldsService_PermResourceFieldsQ_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users/roles/perm_resource_fields.proto",
}
