// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: users/roles/perm_fields.proto

package perm_fields

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PermFieldsService_PermFieldsA_FullMethodName = "/users.roles.perm_fields.PermFieldsService/PermFieldsA"
	PermFieldsService_PermFieldsU_FullMethodName = "/users.roles.perm_fields.PermFieldsService/PermFieldsU"
	PermFieldsService_PermFieldsD_FullMethodName = "/users.roles.perm_fields.PermFieldsService/PermFieldsD"
	PermFieldsService_PermFieldsQ_FullMethodName = "/users.roles.perm_fields.PermFieldsService/PermFieldsQ"
)

// PermFieldsServiceClient is the client API for PermFieldsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PermFieldsServiceClient interface {
	PermFieldsA(ctx context.Context, in *PermFieldsARequest, opts ...grpc.CallOption) (*Response, error)
	PermFieldsU(ctx context.Context, in *PermFieldsURequest, opts ...grpc.CallOption) (*Response, error)
	PermFieldsD(ctx context.Context, in *PermFieldsDRequest, opts ...grpc.CallOption) (*Response, error)
	PermFieldsQ(ctx context.Context, in *PermFieldsQRequest, opts ...grpc.CallOption) (*Response, error)
}

type permFieldsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPermFieldsServiceClient(cc grpc.ClientConnInterface) PermFieldsServiceClient {
	return &permFieldsServiceClient{cc}
}

func (c *permFieldsServiceClient) PermFieldsA(ctx context.Context, in *PermFieldsARequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PermFieldsService_PermFieldsA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permFieldsServiceClient) PermFieldsU(ctx context.Context, in *PermFieldsURequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PermFieldsService_PermFieldsU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permFieldsServiceClient) PermFieldsD(ctx context.Context, in *PermFieldsDRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PermFieldsService_PermFieldsD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permFieldsServiceClient) PermFieldsQ(ctx context.Context, in *PermFieldsQRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PermFieldsService_PermFieldsQ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermFieldsServiceServer is the server API for PermFieldsService service.
// All implementations must embed UnimplementedPermFieldsServiceServer
// for forward compatibility.
type PermFieldsServiceServer interface {
	PermFieldsA(context.Context, *PermFieldsARequest) (*Response, error)
	PermFieldsU(context.Context, *PermFieldsURequest) (*Response, error)
	PermFieldsD(context.Context, *PermFieldsDRequest) (*Response, error)
	PermFieldsQ(context.Context, *PermFieldsQRequest) (*Response, error)
	mustEmbedUnimplementedPermFieldsServiceServer()
}

// UnimplementedPermFieldsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPermFieldsServiceServer struct{}

func (UnimplementedPermFieldsServiceServer) PermFieldsA(context.Context, *PermFieldsARequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method PermFieldsA not implemented")
}
func (UnimplementedPermFieldsServiceServer) PermFieldsU(context.Context, *PermFieldsURequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method PermFieldsU not implemented")
}
func (UnimplementedPermFieldsServiceServer) PermFieldsD(context.Context, *PermFieldsDRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method PermFieldsD not implemented")
}
func (UnimplementedPermFieldsServiceServer) PermFieldsQ(context.Context, *PermFieldsQRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method PermFieldsQ not implemented")
}
func (UnimplementedPermFieldsServiceServer) mustEmbedUnimplementedPermFieldsServiceServer() {}
func (UnimplementedPermFieldsServiceServer) testEmbeddedByValue()                           {}

// UnsafePermFieldsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermFieldsServiceServer will
// result in compilation errors.
type UnsafePermFieldsServiceServer interface {
	mustEmbedUnimplementedPermFieldsServiceServer()
}

func RegisterPermFieldsServiceServer(s grpc.ServiceRegistrar, srv PermFieldsServiceServer) {
	// If the following call panics, it indicates UnimplementedPermFieldsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PermFieldsService_ServiceDesc, srv)
}

func _PermFieldsService_PermFieldsA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermFieldsARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermFieldsServiceServer).PermFieldsA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermFieldsService_PermFieldsA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermFieldsServiceServer).PermFieldsA(ctx, req.(*PermFieldsARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermFieldsService_PermFieldsU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermFieldsURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermFieldsServiceServer).PermFieldsU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermFieldsService_PermFieldsU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermFieldsServiceServer).PermFieldsU(ctx, req.(*PermFieldsURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermFieldsService_PermFieldsD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermFieldsDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermFieldsServiceServer).PermFieldsD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermFieldsService_PermFieldsD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermFieldsServiceServer).PermFieldsD(ctx, req.(*PermFieldsDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermFieldsService_PermFieldsQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermFieldsQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermFieldsServiceServer).PermFieldsQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermFieldsService_PermFieldsQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermFieldsServiceServer).PermFieldsQ(ctx, req.(*PermFieldsQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PermFieldsService_ServiceDesc is the grpc.ServiceDesc for PermFieldsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PermFieldsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.roles.perm_fields.PermFieldsService",
	HandlerType: (*PermFieldsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PermFieldsA",
			Handler:    _PermFieldsService_PermFieldsA_Handler,
		},
		{
			MethodName: "PermFieldsU",
			Handler:    _PermFieldsService_PermFieldsU_Handler,
		},
		{
			MethodName: "PermFieldsD",
			Handler:    _PermFieldsService_PermFieldsD_Handler,
		},
		{
			MethodName: "PermFieldsQ",
			Handler:    _PermFieldsService_PermFieldsQ_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users/roles/perm_fields.proto",
}
