// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: users/app/group_role.proto

package group_role

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppGroupRoleAResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdxNo         int32                  `protobuf:"varint,1,opt,name=IdxNo,proto3" json:"IdxNo,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppGroupRoleAResult) Reset() {
	*x = AppGroupRoleAResult{}
	mi := &file_users_app_group_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppGroupRoleAResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGroupRoleAResult) ProtoMessage() {}

func (x *AppGroupRoleAResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_group_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGroupRoleAResult.ProtoReflect.Descriptor instead.
func (*AppGroupRoleAResult) Descriptor() ([]byte, []int) {
	return file_users_app_group_role_proto_rawDescGZIP(), []int{0}
}

func (x *AppGroupRoleAResult) GetIdxNo() int32 {
	if x != nil {
		return x.IdxNo
	}
	return 0
}

func (x *AppGroupRoleAResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppGroupRoleAResult) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type AppGroupRoleUResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdxNo         int32                  `protobuf:"varint,1,opt,name=IdxNo,proto3" json:"IdxNo,omitempty"`
	IdSeq         string                 `protobuf:"bytes,2,opt,name=IdSeq,proto3" json:"IdSeq,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppGroupRoleUResult) Reset() {
	*x = AppGroupRoleUResult{}
	mi := &file_users_app_group_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppGroupRoleUResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGroupRoleUResult) ProtoMessage() {}

func (x *AppGroupRoleUResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_group_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGroupRoleUResult.ProtoReflect.Descriptor instead.
func (*AppGroupRoleUResult) Descriptor() ([]byte, []int) {
	return file_users_app_group_role_proto_rawDescGZIP(), []int{1}
}

func (x *AppGroupRoleUResult) GetIdxNo() int32 {
	if x != nil {
		return x.IdxNo
	}
	return 0
}

func (x *AppGroupRoleUResult) GetIdSeq() string {
	if x != nil {
		return x.IdSeq
	}
	return ""
}

func (x *AppGroupRoleUResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppGroupRoleUResult) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type AppGroupRoleDResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdSeq         string                 `protobuf:"bytes,1,opt,name=IdSeq,proto3" json:"IdSeq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppGroupRoleDResult) Reset() {
	*x = AppGroupRoleDResult{}
	mi := &file_users_app_group_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppGroupRoleDResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGroupRoleDResult) ProtoMessage() {}

func (x *AppGroupRoleDResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_group_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGroupRoleDResult.ProtoReflect.Descriptor instead.
func (*AppGroupRoleDResult) Descriptor() ([]byte, []int) {
	return file_users_app_group_role_proto_rawDescGZIP(), []int{2}
}

func (x *AppGroupRoleDResult) GetIdSeq() string {
	if x != nil {
		return x.IdSeq
	}
	return ""
}

type AppGroupRoleQResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyItem1      string                 `protobuf:"bytes,1,opt,name=KeyItem1,proto3" json:"KeyItem1,omitempty"`
	KeyItem2      string                 `protobuf:"bytes,2,opt,name=KeyItem2,proto3" json:"KeyItem2,omitempty"`
	KeyItem3      string                 `protobuf:"bytes,3,opt,name=KeyItem3,proto3" json:"KeyItem3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppGroupRoleQResult) Reset() {
	*x = AppGroupRoleQResult{}
	mi := &file_users_app_group_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppGroupRoleQResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGroupRoleQResult) ProtoMessage() {}

func (x *AppGroupRoleQResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_group_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGroupRoleQResult.ProtoReflect.Descriptor instead.
func (*AppGroupRoleQResult) Descriptor() ([]byte, []int) {
	return file_users_app_group_role_proto_rawDescGZIP(), []int{3}
}

func (x *AppGroupRoleQResult) GetKeyItem1() string {
	if x != nil {
		return x.KeyItem1
	}
	return ""
}

func (x *AppGroupRoleQResult) GetKeyItem2() string {
	if x != nil {
		return x.KeyItem2
	}
	return ""
}

func (x *AppGroupRoleQResult) GetKeyItem3() string {
	if x != nil {
		return x.KeyItem3
	}
	return ""
}

type AppGroupRoleARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*AppGroupRoleAResult `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppGroupRoleARequest) Reset() {
	*x = AppGroupRoleARequest{}
	mi := &file_users_app_group_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppGroupRoleARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGroupRoleARequest) ProtoMessage() {}

func (x *AppGroupRoleARequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_group_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGroupRoleARequest.ProtoReflect.Descriptor instead.
func (*AppGroupRoleARequest) Descriptor() ([]byte, []int) {
	return file_users_app_group_role_proto_rawDescGZIP(), []int{4}
}

func (x *AppGroupRoleARequest) GetResult() []*AppGroupRoleAResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AppGroupRoleARequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AppGroupRoleURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*AppGroupRoleUResult `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppGroupRoleURequest) Reset() {
	*x = AppGroupRoleURequest{}
	mi := &file_users_app_group_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppGroupRoleURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGroupRoleURequest) ProtoMessage() {}

func (x *AppGroupRoleURequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_group_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGroupRoleURequest.ProtoReflect.Descriptor instead.
func (*AppGroupRoleURequest) Descriptor() ([]byte, []int) {
	return file_users_app_group_role_proto_rawDescGZIP(), []int{5}
}

func (x *AppGroupRoleURequest) GetResult() []*AppGroupRoleUResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AppGroupRoleURequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AppGroupRoleDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*AppGroupRoleDResult `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppGroupRoleDRequest) Reset() {
	*x = AppGroupRoleDRequest{}
	mi := &file_users_app_group_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppGroupRoleDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGroupRoleDRequest) ProtoMessage() {}

func (x *AppGroupRoleDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_group_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGroupRoleDRequest.ProtoReflect.Descriptor instead.
func (*AppGroupRoleDRequest) Descriptor() ([]byte, []int) {
	return file_users_app_group_role_proto_rawDescGZIP(), []int{6}
}

func (x *AppGroupRoleDRequest) GetResult() []*AppGroupRoleDResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AppGroupRoleDRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AppGroupRoleQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *AppGroupRoleQResult   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppGroupRoleQRequest) Reset() {
	*x = AppGroupRoleQRequest{}
	mi := &file_users_app_group_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppGroupRoleQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGroupRoleQRequest) ProtoMessage() {}

func (x *AppGroupRoleQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_group_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGroupRoleQRequest.ProtoReflect.Descriptor instead.
func (*AppGroupRoleQRequest) Descriptor() ([]byte, []int) {
	return file_users_app_group_role_proto_rawDescGZIP(), []int{7}
}

func (x *AppGroupRoleQRequest) GetResult() *AppGroupRoleQResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AppGroupRoleQRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Page          string                 `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_users_app_group_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_group_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_users_app_group_role_proto_rawDescGZIP(), []int{8}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Response) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

var File_users_app_group_role_proto protoreflect.FileDescriptor

const file_users_app_group_role_proto_rawDesc = "" +
	"\n" +
	"\x1ausers/app/group_role.proto\x12\x14users.app.group_role\"Y\n" +
	"\x13AppGroupRoleAResult\x12\x14\n" +
	"\x05IdxNo\x18\x01 \x01(\x05R\x05IdxNo\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x18\n" +
	"\aComment\x18\x03 \x01(\tR\aComment\"o\n" +
	"\x13AppGroupRoleUResult\x12\x14\n" +
	"\x05IdxNo\x18\x01 \x01(\x05R\x05IdxNo\x12\x14\n" +
	"\x05IdSeq\x18\x02 \x01(\tR\x05IdSeq\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x18\n" +
	"\aComment\x18\x04 \x01(\tR\aComment\"+\n" +
	"\x13AppGroupRoleDResult\x12\x14\n" +
	"\x05IdSeq\x18\x01 \x01(\tR\x05IdSeq\"i\n" +
	"\x13AppGroupRoleQResult\x12\x1a\n" +
	"\bKeyItem1\x18\x01 \x01(\tR\bKeyItem1\x12\x1a\n" +
	"\bKeyItem2\x18\x02 \x01(\tR\bKeyItem2\x12\x1a\n" +
	"\bKeyItem3\x18\x03 \x01(\tR\bKeyItem3\"\xec\x01\n" +
	"\x14AppGroupRoleARequest\x12A\n" +
	"\x06result\x18\x01 \x03(\v2).users.app.group_role.AppGroupRoleAResultR\x06result\x12T\n" +
	"\bmetadata\x18\x02 \x03(\v28.users.app.group_role.AppGroupRoleARequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xec\x01\n" +
	"\x14AppGroupRoleURequest\x12A\n" +
	"\x06result\x18\x01 \x03(\v2).users.app.group_role.AppGroupRoleUResultR\x06result\x12T\n" +
	"\bmetadata\x18\x02 \x03(\v28.users.app.group_role.AppGroupRoleURequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xec\x01\n" +
	"\x14AppGroupRoleDRequest\x12A\n" +
	"\x06result\x18\x01 \x03(\v2).users.app.group_role.AppGroupRoleDResultR\x06result\x12T\n" +
	"\bmetadata\x18\x02 \x03(\v28.users.app.group_role.AppGroupRoleDRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xec\x01\n" +
	"\x14AppGroupRoleQRequest\x12A\n" +
	"\x06result\x18\x01 \x01(\v2).users.app.group_role.AppGroupRoleQResultR\x06result\x12T\n" +
	"\bmetadata\x18\x02 \x03(\v28.users.app.group_role.AppGroupRoleQRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x12\n" +
	"\x04page\x18\x04 \x01(\tR\x04page2\x89\x03\n" +
	"\x13AppGroupRoleService\x12[\n" +
	"\rAppGroupRoleA\x12*.users.app.group_role.AppGroupRoleARequest\x1a\x1e.users.app.group_role.Response\x12[\n" +
	"\rAppGroupRoleU\x12*.users.app.group_role.AppGroupRoleURequest\x1a\x1e.users.app.group_role.Response\x12[\n" +
	"\rAppGroupRoleD\x12*.users.app.group_role.AppGroupRoleDRequest\x1a\x1e.users.app.group_role.Response\x12[\n" +
	"\rAppGroupRoleQ\x12*.users.app.group_role.AppGroupRoleQRequest\x1a\x1e.users.app.group_role.ResponseB(Z&server-core/proto/users/app/group_roleb\x06proto3"

var (
	file_users_app_group_role_proto_rawDescOnce sync.Once
	file_users_app_group_role_proto_rawDescData []byte
)

func file_users_app_group_role_proto_rawDescGZIP() []byte {
	file_users_app_group_role_proto_rawDescOnce.Do(func() {
		file_users_app_group_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_app_group_role_proto_rawDesc), len(file_users_app_group_role_proto_rawDesc)))
	})
	return file_users_app_group_role_proto_rawDescData
}

var file_users_app_group_role_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_users_app_group_role_proto_goTypes = []any{
	(*AppGroupRoleAResult)(nil),  // 0: users.app.group_role.AppGroupRoleAResult
	(*AppGroupRoleUResult)(nil),  // 1: users.app.group_role.AppGroupRoleUResult
	(*AppGroupRoleDResult)(nil),  // 2: users.app.group_role.AppGroupRoleDResult
	(*AppGroupRoleQResult)(nil),  // 3: users.app.group_role.AppGroupRoleQResult
	(*AppGroupRoleARequest)(nil), // 4: users.app.group_role.AppGroupRoleARequest
	(*AppGroupRoleURequest)(nil), // 5: users.app.group_role.AppGroupRoleURequest
	(*AppGroupRoleDRequest)(nil), // 6: users.app.group_role.AppGroupRoleDRequest
	(*AppGroupRoleQRequest)(nil), // 7: users.app.group_role.AppGroupRoleQRequest
	(*Response)(nil),             // 8: users.app.group_role.Response
	nil,                          // 9: users.app.group_role.AppGroupRoleARequest.MetadataEntry
	nil,                          // 10: users.app.group_role.AppGroupRoleURequest.MetadataEntry
	nil,                          // 11: users.app.group_role.AppGroupRoleDRequest.MetadataEntry
	nil,                          // 12: users.app.group_role.AppGroupRoleQRequest.MetadataEntry
}
var file_users_app_group_role_proto_depIdxs = []int32{
	0,  // 0: users.app.group_role.AppGroupRoleARequest.result:type_name -> users.app.group_role.AppGroupRoleAResult
	9,  // 1: users.app.group_role.AppGroupRoleARequest.metadata:type_name -> users.app.group_role.AppGroupRoleARequest.MetadataEntry
	1,  // 2: users.app.group_role.AppGroupRoleURequest.result:type_name -> users.app.group_role.AppGroupRoleUResult
	10, // 3: users.app.group_role.AppGroupRoleURequest.metadata:type_name -> users.app.group_role.AppGroupRoleURequest.MetadataEntry
	2,  // 4: users.app.group_role.AppGroupRoleDRequest.result:type_name -> users.app.group_role.AppGroupRoleDResult
	11, // 5: users.app.group_role.AppGroupRoleDRequest.metadata:type_name -> users.app.group_role.AppGroupRoleDRequest.MetadataEntry
	3,  // 6: users.app.group_role.AppGroupRoleQRequest.result:type_name -> users.app.group_role.AppGroupRoleQResult
	12, // 7: users.app.group_role.AppGroupRoleQRequest.metadata:type_name -> users.app.group_role.AppGroupRoleQRequest.MetadataEntry
	4,  // 8: users.app.group_role.AppGroupRoleService.AppGroupRoleA:input_type -> users.app.group_role.AppGroupRoleARequest
	5,  // 9: users.app.group_role.AppGroupRoleService.AppGroupRoleU:input_type -> users.app.group_role.AppGroupRoleURequest
	6,  // 10: users.app.group_role.AppGroupRoleService.AppGroupRoleD:input_type -> users.app.group_role.AppGroupRoleDRequest
	7,  // 11: users.app.group_role.AppGroupRoleService.AppGroupRoleQ:input_type -> users.app.group_role.AppGroupRoleQRequest
	8,  // 12: users.app.group_role.AppGroupRoleService.AppGroupRoleA:output_type -> users.app.group_role.Response
	8,  // 13: users.app.group_role.AppGroupRoleService.AppGroupRoleU:output_type -> users.app.group_role.Response
	8,  // 14: users.app.group_role.AppGroupRoleService.AppGroupRoleD:output_type -> users.app.group_role.Response
	8,  // 15: users.app.group_role.AppGroupRoleService.AppGroupRoleQ:output_type -> users.app.group_role.Response
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_users_app_group_role_proto_init() }
func file_users_app_group_role_proto_init() {
	if File_users_app_group_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_app_group_role_proto_rawDesc), len(file_users_app_group_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_app_group_role_proto_goTypes,
		DependencyIndexes: file_users_app_group_role_proto_depIdxs,
		MessageInfos:      file_users_app_group_role_proto_msgTypes,
	}.Build()
	File_users_app_group_role_proto = out.File
	file_users_app_group_role_proto_goTypes = nil
	file_users_app_group_role_proto_depIdxs = nil
}
