// Cơ sở dữ liệu Cẩm nang Công thức & Từ điển Cột dữ liệu Báo cáo Sản xuất GsHub
// Bao gồm cả 2 phân hệ: Thống kê sản xuất (TKSX) và Kế hoạch sản xuất (KHSX)

export const STAT_FORMULA_DATABASE = [
  // ==================== I. THẺ KPI ĐIỀU HÀNH (TKSX) ====================
  {
    id: 'kpi_total_tickets',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'KPI',
    categoryName: 'I. Thẻ KPI Điều hành',
    columnId: 'totalTickets / TicketCode',
    columnName: 'Tổng phiếu thống kê sản xuất',
    title: 'Tổng phiếu thống kê sản xuất',
    scope: 'Mục I: Thẻ KPI Tổng quan (Ô 1)',
    formula: 'COUNT(TicketCode) trong kỳ lọc',
    source: 'CSDL _ERPProdStatsDetail (Trường: TicketCode)',
    description:
      'Phản ánh tổng lượng tác nghiệp ghi nhận số liệu sản xuất thực tế tại hiện trường sau khi áp dụng các bộ lọc ngày, máy, tổ.',
    notes:
      'Tự động phân tách số phiếu lập trực tiếp từ thiết bị MES tại hiện trường so với các nguồn khác.'
  },
  {
    id: 'kpi_over_12h_check',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'KPI',
    categoryName: 'I. Thẻ KPI Điều hành',
    columnId: 'runtimeOver12hCheck / AuditCategory',
    columnName: 'Phiếu chạy máy > 12h (Cần kiểm tra)',
    title: 'Thời gian chạy máy > 12h (Cần kiểm tra)',
    scope: 'Mục I: Thẻ KPI Tổng quan (Ô 2) & Mục 4.2',
    formula: 'COUNT(Tickets) WHERE DurationMinutes > 720 VÀ ProdQty < 50.000 SP',
    source: 'CSDL _ERPProdStatsDetail (Trường: DurationMinutes, ProdQty, ActualRunTime)',
    description:
      'Cảnh báo các phiếu thống kê sản xuất có thời gian chạy máy kéo dài bất thường (>12 giờ) nhưng sản lượng nhỏ (<50k sp), cần Quản lý sản xuất kiểm tra.',
    notes: 'Bấm trực tiếp vào thẻ để mở cửa sổ tra cứu chi tiết danh sách phiếu cần kiểm tra.'
  },
  {
    id: 'kpi_under_5min',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'KPI',
    categoryName: 'I. Thẻ KPI Điều hành',
    columnId: 'runtimeUnder5Min / under5Min',
    columnName: 'Thao tác < 5 phút (Thao tác nhanh)',
    title: 'Thao tác < 5 phút (Thao tác nhanh / Nhập vội)',
    scope: 'Mục I: Thẻ KPI Tổng quan (Ô 3) & Mục 4.2',
    formula: 'COUNT(Tickets) WHERE DurationMinutes < 5 phút',
    source: 'CSDL _ERPProdStatsDetail (Trường: DurationMinutes hoặc EndTime - StartTime < 5 phút)',
    description:
      'Cảnh báo các phiếu thống kê thao tác quá vội vàng hoặc nạp hàng loạt sau ca, cần kiểm tra và chuẩn hóa thao tác đúng quy trình vận hành MES.',
    notes: 'Bấm trực tiếp vào thẻ để mở cửa sổ tra cứu chi tiết danh sách phiếu thao tác nhanh.'
  },
  {
    id: 'kpi_mes_rate',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'KPI',
    categoryName: 'I. Thẻ KPI Điều hành',
    columnId: 'mesRate / TicketCreationLocation',
    columnName: 'Tỷ lệ số hóa quy trình qua MES (%)',
    title: 'Tỷ lệ số hóa quy trình qua MES (MES Rate)',
    scope: 'Mục I: Thẻ KPI Tổng quan (Ô 4) & Mục 4.2',
    formula: '(Số phiếu tạo trực tiếp trên MES / Tổng số phiếu) × 100%',
    source: 'CSDL _ERPProdStatsDetail (Trường: TicketCreationLocation / Source chứa "MES")',
    description:
      'Đo lường mức độ chuẩn hóa số hóa và tự động hóa quy trình sản xuất tại hiện trường, loại bỏ hoàn toàn việc ghi chép sổ sách thủ công.',
    notes: 'Mục tiêu vận hành chuẩn: Duy trì 100% phiếu lập trực tiếp tại trạm máy MES.'
  },
  {
    id: 'kpi_sync_latency',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'KPI',
    categoryName: 'I. Thẻ KPI Điều hành',
    columnId: 'syncLatencyFormatted / SyncDelayMinutes',
    columnName: 'Độ trễ thời gian đồng bộ 2 hệ thống (Sync Latency)',
    title: 'Độ trễ thời gian đồng bộ 2 hệ thống (Sync Latency)',
    scope: 'Mục III: Biểu đồ Tiến trình Đồng bộ & Thẻ KPI Tích hợp',
    formula: 'Avg(MesApprovalTime - TicketCreatedDate) [Quy đổi sang HH:mm:ss]',
    source:
      'CSDL _ERPProdStatsDetail (Trường: SyncDelayMinutes, MesApprovalTime, TicketCreatedDate)',
    description:
      'Đánh giá tính tức thời và độ tin cậy của luồng dữ liệu truyền từ máy trạm sản xuất về máy chủ điều hành trung tâm.',
    notes: 'Thời gian đồng bộ lý tưởng: < 10 giây. Hệ thống phân nhóm: ≤10s, 11–30s, 31–60s, >60s.'
  },
  {
    id: 'kpi_auto_export',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'KPI',
    categoryName: 'I. Thẻ KPI Điều hành',
    columnId: 'autoExportRate / AutoIoStatus',
    columnName: 'Tỷ lệ liên kết chứng từ tự động (Auto-Logistics Rate)',
    title: 'Tỷ lệ liên kết chứng từ tự động (Auto-Logistics Rate)',
    scope: 'Mục III: Biểu đồ Phân bổ Loại Ghi chú Tự động',
    formula:
      '(Số phiếu Có XKTĐ, Có NKTĐ / (Số phiếu Có XKTĐ, Có NKTĐ + Số phiếu Không có XKTĐ, Không có NKTĐ)) × 100%',
    source: 'CSDL _ERPProdStatsDetail (Trường: AutoIoStatus, AutoExport, AutoImport, ExportDocNo)',
    description:
      'Theo dõi tỷ lệ phát sinh chứng từ kho tự động. Phiếu đạt tính các phiếu có trạng thái Có XKTĐ, Có NKTĐ; loại trừ Không sử dụng NVL.',
    notes:
      'Toàn bộ phân loại trạng thái chứng từ tự động được tổng hợp linh động từ cột AutoIoStatus thực tế.'
  },
  {
    id: 'kpi_total_actual_qty',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'KPI',
    categoryName: 'I. Thẻ KPI Điều hành',
    columnId: 'totalActualQty / actualQty',
    columnName: 'Tổng sản lượng sản xuất thực tế',
    title: 'Tổng sản lượng sản xuất thực tế (Total Actual Qty)',
    scope: 'Thẻ KPI Tổng quan & Header Báo cáo',
    formula: 'SUM(ProdQty) trong kỳ lọc',
    source: 'CSDL _ERPProdStatsDetail (Trường: ProdQty, ActualMeters)',
    description: 'Tổng khối lượng hoặc số lượng sản phẩm toàn bộ các máy/tổ đã gia công trong kỳ.',
    notes: 'Bao gồm cả sản phẩm đạt chuẩn và phế phẩm.'
  },
  {
    id: 'kpi_total_pass_qty',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'KPI',
    categoryName: 'I. Thẻ KPI Điều hành',
    columnId: 'totalPassQty / passQty',
    columnName: 'Tổng sản lượng đạt chuẩn KCS',
    title: 'Tổng sản lượng đạt chuẩn KCS (Total Pass Qty)',
    scope: 'Thẻ KPI Tổng quan & Header Báo cáo',
    formula: 'SUM(PassQty) trong kỳ lọc',
    source: 'CSDL _ERPProdStatsDetail (Trường: PassQty, StatPassQty)',
    description:
      'Tổng sản lượng sản phẩm đạt tiêu chuẩn chất lượng xuất xưởng hoặc chuyển công đoạn tiếp theo.',
    notes: 'Là cơ sở tính toán doanh thu và năng suất thực tế.'
  },
  {
    id: 'kpi_total_runtime_hours',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'KPI',
    categoryName: 'I. Thẻ KPI Điều hành',
    columnId: 'totalRuntimeHours / runtimeHours',
    columnName: 'Tổng giờ chạy máy tích lũy (h)',
    title: 'Tổng giờ chạy máy tích lũy toàn hệ thống',
    scope: 'Thẻ KPI Tổng quan & Header Báo cáo',
    formula: 'SUM(DurationMinutes / 60) trong kỳ lọc',
    source: 'CSDL _ERPProdStatsDetail (Trường: DurationMinutes, ActualRunTime)',
    description: 'Tổng số giờ máy hoạt động thực tế trên toàn bộ các dây chuyền và xưởng sản xuất.',
    notes: 'Căn cứ đánh giá khấu hao thiết bị, bảo trì và hiệu suất OEE.'
  },

  // ==================== II. BIỂU ĐỒ PHÂN TÍCH (TKSX) ====================
  {
    id: 'chart_machine_runtime',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'CHARTS',
    categoryName: 'II. Biểu đồ Phân tích',
    columnId: 'totalRuntimeHours / RuntimeHours',
    columnName: 'Tổng giờ chạy máy theo cụm máy (Machine Runtime)',
    title: 'Thống kê tổng giờ chạy máy theo cụm máy',
    scope: 'Mục 1: Biểu đồ Giờ chạy máy theo cụm máy',
    formula: 'Sum(RuntimeHours) = Sum(DurationMinutes / 60) của máy i',
    source: 'CSDL _ERPProdStatsDetail (Trường: ActualRunTime, DurationMinutes, MachineCode)',
    description:
      'Đánh giá tổng thời gian vận hành thực tế tích lũy của từng cụm máy và tổ sản xuất, giúp phân tích tải trọng làm việc.',
    notes:
      'Được sắp xếp giảm dần theo tổng giờ chạy để làm nổi bật thiết bị làm việc công suất cao nhất.'
  },
  {
    id: 'chart_machine_limit_24h',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'CHARTS',
    categoryName: 'II. Biểu đồ Phân tích',
    columnId: 'isOver24h / ReferenceLine y=24',
    columnName: 'Đường chuẩn 24h & Cột đỏ cảnh báo quá tải',
    title: 'Đường giới hạn 24h/ngày & Cảnh báo cột đỏ',
    scope: 'Mục 1: Biểu đồ Giờ chạy máy (Đường nét đứt y=24)',
    formula: 'IF(totalRuntimeHours > 24, "Đỏ Cảnh Báo", "Chuẩn xanh")',
    source: 'Quy chuẩn định mức vận hành 24 giờ/ngày trên mỗi thiết bị máy móc',
    description:
      'Đường tham chiếu đỏ nét đứt y=24h giúp nhận diện tức thì các cụm máy vận hành vượt quá giới hạn 24 giờ trong kỳ báo cáo.',
    notes: 'Trục Y tự động co giãn tối thiểu 26h để đảm bảo đường 24h luôn hiển thị rõ ràng.'
  },
  {
    id: 'chart_runtime_vs_capacity',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'CHARTS',
    categoryName: 'II. Biểu đồ Phân tích',
    columnId: 'runtimeVsCapacity / Tải trọng (%)',
    columnName: 'Tải trọng chạy máy (% so với chuẩn 24h)',
    title: 'Phân bổ tải trọng vận hành máy',
    scope: 'Mục 1: Biểu đồ Phân bổ Tải trọng Máy',
    formula: '(Tổng giờ chạy thực tế / (Số ngày lọc × 24h)) × 100%',
    source: 'Tính toán từ totalRuntimeHours và khoảng thời gian lọc',
    description: 'Đo lường tỷ lệ tận dụng công suất khả dụng tối đa của từng máy.',
    notes: '>100% cảnh báo quá tải hoặc ghi nhận trùng giờ chạy máy.'
  },
  {
    id: 'chart_team_output_quality',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'CHARTS',
    categoryName: 'II. Biểu đồ Phân tích',
    columnId: 'actualQty, passQty, defectQty',
    columnName: 'Sản lượng sản xuất, Đạt & Lỗi theo tổ',
    title: 'Thống kê sản lượng sản xuất & đạt theo tổ',
    scope: 'Mục 2: Biểu đồ Sản lượng sản xuất & Đạt theo tổ',
    formula: 'SL Sản xuất = Sum(actualQty) | SL Đạt = Sum(passQty) | SL Lỗi = Sum(defectQty)',
    source: 'CSDL _ERPProdStatsDetail (Trường: ProdQty, PassQty, DefectQty, TeamName)',
    description:
      'Trực quan hóa đối chiếu khối lượng sản xuất thực tế, số lượng đạt tiêu chuẩn và lượng phế phẩm/lỗi của từng tổ sản xuất trong kỳ lọc.',
    notes: 'Biểu đồ cột 3 thành phần: SL Sản xuất, SL Đạt và SL Lỗi.'
  },
  {
    id: 'chart_daily_trend_stat',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'CHARTS',
    categoryName: 'II. Biểu đồ Phân tích',
    columnId: 'dailyTrendData / chartByDay',
    columnName: 'Diễn biến sản lượng & Tỷ lệ Đạt theo ngày',
    title: 'Biểu đồ Diễn biến sản lượng và Tỷ lệ Đạt hàng ngày',
    scope: 'Mục 2 & Mục Tổng hợp: Biểu đồ dòng thời gian theo ngày',
    formula:
      'Theo từng ngày: SL SX = SUM(ProdQty), SL Đạt = SUM(PassQty), Tỷ lệ = (Đạt / SX) * 100%',
    source: 'CSDL _ERPProdStatsDetail (Nhóm theo ProdDate)',
    description:
      'Theo dõi nhịp độ sản xuất từng ngày và biến động chất lượng KCS trong suốt chu kỳ.',
    notes: 'Biểu đồ kết hợp cột (Sản lượng) và đường (Tỷ lệ Đạt %).'
  },
  {
    id: 'chart_sync_delay_breakdown',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'CHARTS',
    categoryName: 'II. Biểu đồ Phân tích',
    columnId: 'syncDelayBreakdown',
    columnName: 'Phân nhóm độ trễ đồng bộ MES - ERP',
    title: 'Phân bổ tiến trình độ trễ đồng bộ dữ liệu',
    scope: 'Mục III: Biểu đồ Phân nhóm Đồng bộ',
    formula: 'Phân chia các khoảng: ≤10s, 11–30s, 31–60s, >60s',
    source: 'CSDL _ERPProdStatsDetail (Trường: SyncDelayMinutes)',
    description: 'Đo lường mức độ ổn định của đường truyền và tiến trình tích hợp hệ thống.',
    notes: 'Tỷ lệ nhóm ≤10s càng cao thể hiện hệ thống vận hành thời gian thực càng tốt.'
  },
  {
    id: 'chart_auto_export_breakdown',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'CHARTS',
    categoryName: 'II. Biểu đồ Phân tích',
    columnId: 'autoExportBreakdown',
    columnName: 'Phân loại chứng từ tự động (Auto-Logistics)',
    title: 'Phân bổ trạng thái chứng từ tự động xuất/nhập kho',
    scope: 'Mục III: Biểu đồ Tròn Phân bổ Chứng từ',
    formula: 'COUNT(Tickets) phân theo AutoIoStatus (Có XKTĐ, Có NKTĐ, v.v.)',
    source: 'CSDL _ERPProdStatsDetail (Trường: AutoIoStatus)',
    description:
      'Giám sát tỷ lệ tự động liên kết kho vật tư và thành phẩm mà không cần can thiệp thủ công.',
    notes: 'Bấm vào từng cung biểu đồ để lọc các phiếu tương ứng.'
  },

  // ==================== IV. BẢNG BIỂU CHI TIẾT & MA TRẬN (TKSX) ====================
  {
    id: 'col_machine_name',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'machineName / MachineName',
    columnName: 'Tên máy sản xuất',
    title: 'Tên máy sản xuất (Machine Name)',
    scope: 'Mục 4.1 & Mục 4.3 (Cột 6)',
    formula: 'Hiển thị tên định danh máy từ hệ thống',
    source: 'CSDL _ERPProdStatsDetail (Trường: MachineName, MachineCode)',
    description: 'Tên định danh của máy móc hoặc vị trí công đoạn sản xuất tại hiện trường.',
    notes: 'Hỗ trợ tìm kiếm nhanh theo tên máy hoặc mã máy.'
  },
  {
    id: 'col_machine_code',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'machineCode / MachineCode',
    columnName: 'Mã máy sản xuất',
    title: 'Mã máy sản xuất (Machine Code)',
    scope: 'Mục 4.1 (Cột 2)',
    formula: 'Mã code kỹ thuật duy nhất của máy trên hệ thống ERP/MES',
    source: 'CSDL _ERPProdStatsDetail (Trường: MachineCode)',
    description: 'Mã máy chuẩn hóa dùng để liên kết dữ liệu thống kê, bảo trì và kế hoạch.',
    notes: 'Ví dụ: IN01, IN02, BE01, CL01, TC01...'
  },
  {
    id: 'col_team_name',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'teamName / TeamName',
    columnName: 'Tổ sản xuất phụ trách',
    title: 'Tên tổ sản xuất (Production Team)',
    scope: 'Mục 4.1, 4.2 & 4.3',
    formula: 'Tên đơn vị tổ quản lý máy/ca sản xuất',
    source: 'CSDL _ERPProdStatsDetail (Trường: TeamName)',
    description: 'Phân loại dữ liệu theo tổ chịu trách nhiệm gia công trực tiếp.',
    notes: 'Hỗ trợ bộ lọc nhanh theo từng tổ.'
  },
  {
    id: 'col_runtime_hours_stat',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'runtimeHours / totalRuntimeHours',
    columnName: 'Tổng giờ chạy máy (h)',
    title: 'Thời gian chạy máy thực tế tích lũy',
    scope: 'Mục 4.1: Cột 4 | Mục 4.2: Cột 7',
    formula: 'SUM(DurationMinutes / 60)',
    source: 'CSDL _ERPProdStatsDetail (Trường: DurationMinutes)',
    description: 'Tổng thời lượng máy vận hành thực tế phục vụ sản xuất.',
    notes: 'Định dạng hiển thị 1-2 chữ số thập phân (VD: 18.5h).'
  },
  {
    id: 'col_actual_qty',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'actualQty / totalActualQty',
    columnName: 'SL Sản xuất thực tế',
    title: 'Sản lượng sản xuất thực tế (Actual Quantity)',
    scope: 'Mục 4.1: Cột 5 | Mục 4.2: Cột 3 | Mục 4.3: Cột 9',
    formula: 'Sum(ProdQty) hoặc Sum(ActualMeters)',
    source: 'CSDL _ERPProdStatsDetail (Trường: ProdQty, ActualMeters, StatPassQty)',
    description: 'Tổng sản lượng thực tế máy đã thực hiện trong ca sản xuất.',
    notes: 'Đơn vị: Chiếc / Mét / Tấm tùy theo dòng sản phẩm.'
  },
  {
    id: 'col_pass_qty',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'passQty / totalPassQty',
    columnName: 'SL Đạt chuẩn KCS',
    title: 'Sản lượng đạt tiêu chuẩn (Pass Quantity)',
    scope: 'Mục 4.1: Cột 6 | Mục 4.2: Cột 4 | Mục 4.3: Cột 10',
    formula: 'Sum(PassQty)',
    source: 'CSDL _ERPProdStatsDetail (Trường: PassQty, StatPassQty)',
    description: 'Số lượng sản phẩm vượt qua quy trình kiểm soát chất lượng KCS.',
    notes: 'SL Đạt luôn nhỏ hơn hoặc bằng SL Sản xuất thực tế.'
  },
  {
    id: 'col_defect_qty',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'defectQty / totalDefectQty',
    columnName: 'SL Lỗi / Phế phẩm',
    title: 'Số lượng lỗi / Phế phẩm (Defect Quantity)',
    scope: 'Mục 4.1: Cột 7 | Mục 4.2: Cột 5 | Mục 4.3: Cột 11',
    formula: 'DefectQty > 0 ? DefectQty : MAX(0, SL Sản xuất - SL Đạt)',
    source: 'CSDL _ERPProdStatsDetail (Trường: DefectQty, hoặc ProdQty - PassQty)',
    description:
      'Lượng sản phẩm bị loại bỏ do không đạt tiêu chuẩn kỹ thuật hoặc hỏng trong quá trình chạy máy.',
    notes: 'Được tính toán tự động đảm bảo số liệu luôn khớp với SL Sản xuất và SL Đạt.'
  },
  {
    id: 'col_pass_rate',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'passRate',
    columnName: 'Tỷ lệ đạt chuẩn KCS (%)',
    title: 'Tỷ lệ đạt chuẩn KCS (Quality Pass Rate)',
    scope: 'Mục 4.1: Cột 8 | Mục 4.2: Cột 6 | Mục 4.3: Cột 12',
    formula: '(Tổng SL Đạt / Tổng SL Sản xuất) × 100%',
    source: 'Tính toán trực tiếp từ totalPassQty và totalActualQty',
    description:
      'Chỉ số đo lường chất lượng sản phẩm xuất xưởng của từng máy, tổ hoặc từng lệnh sản xuất.',
    notes: 'Ngưỡng chuẩn: ≥ 95% (Đạt tiêu chuẩn xanh), < 95% (Cần rà soát nguyên nhân phế phẩm).'
  },
  {
    id: 'col_machine_speed',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'speed / passPerHour',
    columnName: 'SL Đạt / Giờ (Tốc độ máy sp/h)',
    title: 'Năng suất tốc độ máy theo giờ',
    scope: 'Mục 4.1: Ma trận cụm máy (Cột 10)',
    formula: 'Tổng SL Đạt KCS / Tổng Giờ chạy máy thực tế',
    source: 'Tính toán từ totalPassQty và totalRuntimeHours',
    description:
      'Đo lường năng lực tạo ra sản phẩm đạt chuẩn KCS trên mỗi giờ vận hành thực tế của từng máy.',
    notes: 'Định mức tính theo đơn vị sản phẩm trên giờ (SP/h).'
  },
  {
    id: 'col_ticket_count',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'tickets / ticketCount',
    columnName: 'Số phiếu thống kê thực hiện',
    title: 'Số lượng phiếu thống kê ghi nhận',
    scope: 'Mục 4.1 (Cột 9) & Mục 4.2 (Cột 2)',
    formula: 'COUNT(Tickets) của máy hoặc tổ đó',
    source: 'CSDL _ERPProdStatsDetail',
    description: 'Tổng số lần lập phiếu xác nhận sản lượng cho máy/tổ.',
    notes: 'Phản ánh tần suất vận hành và chuyển giao lệnh sản xuất.'
  },
  {
    id: 'col_duration_minutes',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'durationMinutes / DurationMinutes',
    columnName: 'Thời gian chạy máy (phút)',
    title: 'Thời gian chạy máy tính theo phút',
    scope: 'Mục 4.3: Bảng chi tiết phiếu (Cột 8)',
    formula: 'DATEDIFF(minute, StartTime, EndTime)',
    source: 'CSDL _ERPProdStatsDetail (Trường: DurationMinutes)',
    description: 'Thời gian thực tế máy hoạt động trên từng phiếu thống kê.',
    notes: 'Dùng để phân loại phiếu >12h hoặc <5 phút.'
  },
  {
    id: 'col_supervisor_stat',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'supervisor / statPerson',
    columnName: 'Người thống kê / Giám sát',
    title: 'Nhân sự lập phiếu / Giám sát ca',
    scope: 'Mục 4.3: Bảng chi tiết phiếu (Cột 13)',
    formula: 'Tên hoặc mã nhân viên ghi nhận sản lượng',
    source: 'CSDL _ERPProdStatsDetail (Trường: Supervisor, StatPerson)',
    description: 'Xác định trách nhiệm ca kíp và người thao tác nhập liệu trên MES/ERP.',
    notes: 'Hỗ trợ lọc và tìm kiếm theo nhân sự.'
  },
  {
    id: 'col_created_source',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'createdSource / TicketCreationLocation',
    columnName: 'Nguồn tạo phiếu (MES / ERP)',
    title: 'Nguồn phát sinh dữ liệu phiếu thống kê',
    scope: 'Mục 4.3: Bảng chi tiết phiếu (Cột 14)',
    formula: 'MES Terminal / Web Portal / ERP Import',
    source: 'CSDL _ERPProdStatsDetail (Trường: CreatedSource, TicketCreationLocation)',
    description: 'Xác định phiếu được tạo trực tiếp tại máy trạm MES hay nhập liệu bổ sung.',
    notes: 'Căn cứ tính toán Tỷ lệ số hóa MES (MES Rate).'
  },
  {
    id: 'col_auto_io_status',
    reportType: 'stat',
    reportTypeName: 'Thống kê SX (TKSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'autoIoStatus / AutoIoStatus',
    columnName: 'Trạng thái Auto IO (Kho tự động)',
    title: 'Trạng thái liên kết chứng từ kho tự động',
    scope: 'Mục 4.3: Bảng chi tiết phiếu (Cột 15)',
    formula: 'Có XKTĐ & NKTĐ | Có XKTĐ | Không có XKTĐ/NKTĐ',
    source: 'CSDL _ERPProdStatsDetail (Trường: AutoIoStatus)',
    description: 'Xác nhận trạng thái tạo phiếu xuất kho tự động và nhập kho tự động.',
    notes: 'Liên kết trực tiếp với hệ thống quản lý kho WMS/ERP.'
  }
]

export const PLAN_FORMULA_DATABASE = [
  // ==================== I. THẺ KPI ĐIỀU HÀNH (KHSX) ====================
  {
    id: 'kpi_total_orders',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'KPI',
    categoryName: 'I. Thẻ KPI Điều hành',
    columnId: 'totalOrders / IdSeq',
    columnName: 'Tổng số lệnh thao tác',
    title: 'Tổng số lệnh thao tác điều phối',
    scope: 'Thẻ KPI 1 & Toàn bộ báo cáo KHSX',
    formula: 'COUNT(IdSeq) trong phạm vi bộ lọc',
    source: 'CSDL _ERPPlanDetail (Trường: OperationNo, DocNo, IdSeq)',
    description:
      'Tổng số lệnh điều phối sản xuất nằm trong phạm vi ngày và các điều kiện lọc được chọn.',
    notes: 'Tổng hợp số lượng phân bổ theo từng công đoạn.'
  },
  {
    id: 'kpi_sx_sai_ngay',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'KPI',
    categoryName: 'I. Thẻ KPI Điều hành',
    columnId: 'sxSaiNgayCount / StatusDpSx',
    columnName: 'SX sai ngày KH',
    title: 'Sản xuất sai ngày kế hoạch',
    scope: 'Thẻ KPI 2 & Mục 3 & Mục 6',
    formula: 'COUNT IF (StatusDpSx = "SX sai ngày KH" HOẶC OpDate != RoutingDocDate)',
    source: 'So khớp ngày thực hiện (OpDate) với ngày điều phối (RoutingDocDate)',
    description:
      'Số lượng và tỷ lệ lệnh có ngày sản xuất thực tế lệch so với ngày kế hoạch ban đầu.',
    notes: 'Cần phân tích nguyên nhân điều chỉnh tiến độ giao hàng.'
  },
  {
    id: 'kpi_truot_kh',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'KPI',
    categoryName: 'I. Thẻ KPI Điều hành',
    columnId: 'truotKhCount / StatusDpSx',
    columnName: 'Trượt KH (Trượt kế hoạch)',
    title: 'Lệnh trượt kế hoạch sản xuất',
    scope: 'Thẻ KPI 3 & Mục 3 & Mục 6',
    formula: 'COUNT IF (StatusDpSx = "Trượt KH" HOẶC StatPassQty < TargetProdQty * 0.9)',
    source: 'Cột StatusDpSx hoặc tỷ lệ sản lượng đạt so với kế hoạch',
    description:
      'Các lệnh không hoàn thành đúng tiến độ hoặc bị thiếu hụt sản lượng so với chỉ tiêu kế hoạch.',
    notes: 'Căn cứ đánh giá mức độ hoàn thành chỉ tiêu giao khoán.'
  },
  {
    id: 'kpi_khop_sl',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'KPI',
    categoryName: 'I. Thẻ KPI Điều hành',
    columnId: 'khopSlCount / StatusDpSx',
    columnName: 'Khớp số lượng',
    title: 'Lệnh khớp số lượng kế hoạch',
    scope: 'Thẻ KPI 4 & Mục 3 & Mục 6',
    formula: 'COUNT IF (StatusDpSx = "Khớp số lượng")',
    source: 'Cột StatusDpSx từ hệ thống ERP/MES',
    description: 'Các lệnh hoàn thành đúng số lượng yêu cầu theo kế hoạch sản xuất đã giao.',
    notes: 'Chỉ số ưu tiên phản ánh năng lực dự báo và thực thi.'
  },
  {
    id: 'kpi_khop_job',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'KPI',
    categoryName: 'I. Thẻ KPI Điều hành',
    columnId: 'khopJobCount / StatusDpSx',
    columnName: 'Khớp job',
    title: 'Lệnh khớp job sản xuất',
    scope: 'Thẻ KPI 5 & Mục 3 & Mục 6',
    formula: 'COUNT IF (StatusDpSx = "Khớp job")',
    source: 'Cột StatusDpSx từ hệ thống ERP/MES',
    description: 'Các lệnh hoàn thành đúng quy cách job mặt hàng và thời điểm sản xuất.',
    notes: 'Phản ánh độ tuân thủ quy trình sắp xếp thứ tự ca máy.'
  },
  {
    id: 'kpi_khop_rate',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'KPI',
    categoryName: 'I. Thẻ KPI Điều hành',
    columnId: 'khopRate / passRate',
    columnName: 'Tỷ lệ Khớp Lệnh Tổng thể (%)',
    title: 'Tỷ lệ Lệnh Khớp Chuẩn Kế Hoạch (Pass Rate)',
    scope: 'Thẻ KPI Tổng hợp & Bảng Ma trận PIC',
    formula: '((Khớp SL + Khớp Job) / Tổng số lệnh) × 100%',
    source: 'Tổng hợp từ StatusDpSx trong _ERPPlanDetail',
    description: 'Đo lường độ chính xác tổng thể của kế hoạch điều phối sản xuất.',
    notes: 'Chỉ tiêu chất lượng quan trọng hàng đầu của bộ phận Lập kế hoạch.'
  },
  {
    id: 'kpi_total_plan_qty',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'KPI',
    categoryName: 'I. Thẻ KPI Điều hành',
    columnId: 'totalPlanQty / TargetProdQty',
    columnName: 'Tổng sản lượng kế hoạch giao',
    title: 'Tổng sản lượng kế hoạch mục tiêu (Total Plan Qty)',
    scope: 'Header Báo cáo & Thẻ KPI KHSX',
    formula: 'SUM(TargetProdQty) trong kỳ lọc',
    source: 'CSDL _ERPPlanDetail (Trường: TargetProdQty, PlanQty)',
    description: 'Tổng khối lượng sản phẩm được giao khoán sản xuất theo lệnh.',
    notes: 'Dùng làm mẫu số để tính Tỷ lệ hoàn thành kế hoạch sản lượng.'
  },
  {
    id: 'kpi_plan_completion_rate',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'KPI',
    categoryName: 'I. Thẻ KPI Điều hành',
    columnId: 'completionRate / planCompletionRate',
    columnName: 'Tỷ lệ hoàn thành kế hoạch (%)',
    title: 'Tỷ lệ hoàn thành sản lượng theo kế hoạch',
    scope: 'Header Báo cáo & Thống kê Sản lượng KHSX',
    formula: '(Tổng SL Thực tế Đạt / Tổng SL Kế hoạch) × 100%',
    source: 'Tính toán từ totalActualQty và totalPlanQty',
    description: 'Đo lường mức độ đáp ứng chỉ tiêu sản lượng thực tế so với cam kết kế hoạch.',
    notes: '≥100%: Hoàn thành vượt mức kế hoạch; <100%: Chưa đạt chỉ tiêu.'
  },

  // ==================== II. BIỂU ĐỒ PHÂN TÍCH (KHSX) ====================
  {
    id: 'chart_plan_vs_actual_team',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'CHARTS',
    categoryName: 'II. Biểu đồ Phân tích',
    columnId: 'planQty, actualQty, targetProdQty',
    columnName: 'Sản lượng Kế hoạch vs Thực tế theo tổ',
    title: 'So sánh Kế hoạch và Thực tế theo tổ',
    scope: 'Mục 2: Biểu đồ Tiến độ theo tổ',
    formula: 'SL Kế hoạch = Sum(TargetProdQty) | SL Thực tế = Sum(StatPassQty)',
    source: 'CSDL _ERPPlanDetail (Trường: TargetProdQty, StatPassQty, TeamName)',
    description:
      'So sánh tương quan giữa sản lượng được phân bổ theo kế hoạch và sản lượng thực tế máy/tổ đạt được.',
    notes: 'Biểu đồ dạng cột kép trực quan tỷ lệ hoàn thành %.'
  },
  {
    id: 'chart_plan_vs_actual_machine',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'CHARTS',
    categoryName: 'II. Biểu đồ Phân tích',
    columnId: 'machineBreakdown / chartByMachine',
    columnName: 'Sản lượng Kế hoạch vs Thực tế theo cụm máy',
    title: 'Tiến độ thực hiện kế hoạch theo từng cụm máy',
    scope: 'Mục 2: Biểu đồ Tiến độ theo Máy',
    formula: 'SL Kế hoạch = Sum(TargetProdQty) | SL Thực tế = Sum(StatPassQty) của từng máy',
    source: 'CSDL _ERPPlanDetail (Trường: MachineCode, TargetProdQty, StatPassQty)',
    description: 'Phân tích hiệu suất hoàn thành kế hoạch tại từng đầu máy công đoạn.',
    notes: 'Giúp phát hiện ngay điểm nghẽn công đoạn (bottleneck).'
  },
  {
    id: 'chart_plan_daily_trend',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'CHARTS',
    categoryName: 'II. Biểu đồ Phân tích',
    columnId: 'dailyTrendData / chartByDay',
    columnName: 'Diễn biến tiến độ KHSX theo ngày',
    title: 'Biểu đồ Tiến độ Kế hoạch vs Thực tế hàng ngày',
    scope: 'Mục 2 & Mục Tổng hợp: Tiến độ thời gian theo ngày',
    formula:
      'Theo từng ngày: SL KH = SUM(TargetProdQty), SL TT = SUM(StatPassQty), Tỷ lệ = (TT / KH) * 100%',
    source: 'CSDL _ERPPlanDetail (Nhóm theo OpDate / RoutingDocDate)',
    description: 'Theo dõi nhịp độ giao hàng và thực hiện kế hoạch từng ngày trong chu kỳ.',
    notes: 'Đối chiếu trực quan giữa lượng đặt kế hoạch và năng lực đáp ứng thực tế.'
  },
  {
    id: 'chart_dp_status_breakdown',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'CHARTS',
    categoryName: 'II. Biểu đồ Phân tích',
    columnId: 'dpStatusBreakdown',
    columnName: 'Phân bổ trạng thái điều phối sản xuất',
    title: 'Phân tích cơ cấu trạng thái điều phối (DP Status Breakdown)',
    scope: 'Mục 3: Biểu đồ Cơ cấu Điều phối',
    formula: 'COUNT(Orders) phân theo: Khớp SL, Khớp Job, SX sai ngày KH, Trượt KH',
    source: 'CSDL _ERPPlanDetail (Trường: StatusDpSx)',
    description: 'Trực quan hóa tỷ trọng các trạng thái thực hiện kế hoạch.',
    notes: 'Các mảng màu trực quan giúp lãnh đạo nắm nhanh tỷ lệ tuân thủ lịch sản xuất.'
  },
  {
    id: 'chart_capa_status_breakdown',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'CHARTS',
    categoryName: 'II. Biểu đồ Phân tích',
    columnId: 'capaStatusBreakdown',
    columnName: 'Phân bổ đánh giá định mức Capa',
    title: 'Phân tích năng lực thực thi so với Định mức (Capa Breakdown)',
    scope: 'Mục 4: Biểu đồ Đánh giá Định mức Capa',
    formula: 'COUNT(Orders) phân theo: Nhanh hơn ĐM, Đúng ĐM, Chậm hơn ĐM, Chưa có ĐM',
    source: 'CSDL _ERPPlanDetail (So sánh tốc độ thực tế vs định mức thiết kế)',
    description: 'Đánh giá độ chính xác của định mức công suất máy được cài đặt trên hệ thống.',
    notes: 'Cơ sở quan trọng để bộ phận Kỹ thuật cập nhật lại định mức cho phù hợp thực tế.'
  },

  // ==================== IV. BẢNG BIỂU CHI TIẾT & MA TRẬN (KHSX) ====================
  {
    id: 'col_plan_master_pic',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'planMaster / picName',
    columnName: 'Nhân sự phụ trách Kế hoạch (PIC)',
    title: 'Nhân sự lập kế hoạch / PIC điều phối',
    scope: 'Mục 2: Bảng Ma trận PIC (Cột 1)',
    formula: 'Tên nhân sự được phân công lập lịch sản xuất',
    source: 'CSDL _ERPPlanDetail (Trường: PlanMaster, Supervisor, PicName)',
    description: 'Phân bổ trách nhiệm điều hành kế hoạch theo từng chuyên viên điều phối.',
    notes: 'Hỗ trợ lọc và phân tích đánh giá năng lực từng PIC.'
  },
  {
    id: 'col_plan_khop_growth_rate',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'passGrowthRate / khopGrowthRate',
    columnName: 'Tăng trưởng Khớp %',
    title: 'Tốc độ tăng trưởng lệnh Khớp qua chu kỳ thời gian',
    scope: 'Mục 2: Bảng Ma trận Tăng trưởng PIC (Cột 7)',
    formula:
      '((Tổng Khớp kỳ cuối - Tổng Khớp kỳ đầu) / Tổng Khớp kỳ đầu) × 100% [Tổng Khớp = Khớp SL + Khớp Job]',
    source: 'Chuỗi dữ liệu thời gian periodList.picStats[PIC]',
    description:
      'Đo lường mức độ tăng hoặc giảm về năng lực lập và điều phối các lệnh đạt độ khớp chuẩn (Khớp SL + Khớp Job) giữa kỳ cuối so với kỳ đầu.',
    notes:
      'Chỉ số dương (+) thể hiện sự tiến bộ tích cực, chỉ số âm (-) cảnh báo sự suy giảm độ chính xác kế hoạch.'
  },
  {
    id: 'col_plan_total_growth_rate',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'ordersGrowthRate',
    columnName: 'Tăng trưởng Tổng %',
    title: 'Tốc độ tăng trưởng tổng số lệnh điều phối',
    scope: 'Mục 2: Bảng Ma trận Tăng trưởng PIC (Cột 8)',
    formula: '((Tổng lệnh kỳ cuối - Tổng lệnh kỳ đầu) / Tổng lệnh kỳ đầu) × 100%',
    source: 'Chuỗi dữ liệu thời gian periodList.picStats[PIC]',
    description:
      'Đo lường mức độ biến động khối lượng công việc và số lượng lệnh mà nhân sự PIC đó phụ trách qua các chu kỳ thời gian.',
    notes:
      'Dùng đối chiếu tương quan với Tăng trưởng Khớp % để đánh giá năng lực điều phối khi quy mô lệnh tăng lên.'
  },
  {
    id: 'col_plan_khop_sl_rate',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'khopSlRate',
    columnName: 'Tỷ lệ Khớp SL (%)',
    title: 'Tỷ lệ lệnh Khớp số lượng trên tổng lệnh',
    scope: 'Mục 2: Bảng Ma trận (Cột 3) & Mục 3',
    formula: '(Số lệnh Khớp SL / Tổng số lệnh) × 100%',
    source: 'Tổng hợp từ StatusDpSx = "Khớp số lượng" / TotalOrders',
    description:
      'Tỷ lệ % các lệnh sản xuất đạt chuẩn chính xác về khối lượng sản phẩm kế hoạch giao.',
    notes: 'Chỉ số đo lường mức độ sát sao của kế hoạch với năng lực thực tế.'
  },
  {
    id: 'col_plan_khop_job_rate',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'khopJobRate',
    columnName: 'Tỷ lệ Khớp Job (%)',
    title: 'Tỷ lệ lệnh Khớp Job sản xuất trên tổng lệnh',
    scope: 'Mục 2: Bảng Ma trận (Cột 4) & Mục 3',
    formula: '(Số lệnh Khớp Job / Tổng số lệnh) × 100%',
    source: 'Tổng hợp từ StatusDpSx = "Khớp job" / TotalOrders',
    description:
      'Tỷ lệ % các lệnh tuân thủ chính xác thứ tự mặt hàng, quy cách gia công và định tuyến sản xuất.',
    notes: 'Đánh giá tính kỷ luật trong sắp xếp lịch sản xuất hiện trường.'
  },
  {
    id: 'col_plan_sx_sai_ngay_rate',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'sxSaiNgayRate',
    columnName: 'Tỷ lệ SX Sai Ngày (%)',
    title: 'Tỷ lệ lệnh sản xuất lệch ngày kế hoạch',
    scope: 'Mục 2: Bảng Ma trận (Cột 5)',
    formula: '(Số lệnh SX sai ngày KH / Tổng số lệnh) × 100%',
    source: 'StatusDpSx = "SX sai ngày KH" / TotalOrders',
    description: 'Tỷ trọng các lệnh bị điều chỉnh hoặc đổi lịch thực hiện.',
    notes: 'Càng thấp càng thể hiện tính ổn định cao của lịch sản xuất.'
  },
  {
    id: 'col_plan_truot_kh_rate',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'truotKhRate',
    columnName: 'Tỷ lệ Trượt KH (%)',
    title: 'Tỷ lệ lệnh bị trượt kế hoạch sản xuất',
    scope: 'Mục 2: Bảng Ma trận (Cột 6)',
    formula: '(Số lệnh Trượt KH / Tổng số lệnh) × 100%',
    source: 'StatusDpSx = "Trượt KH" / TotalOrders',
    description: 'Tỷ trọng các lệnh bị lỡ tiến độ hoặc thiếu hụt sản lượng cam kết.',
    notes: 'Chỉ số cảnh báo nguy cơ trễ hẹn giao hàng cho khách.'
  },
  {
    id: 'col_plan_work_order',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'WorkOrderNo / DocNo',
    columnName: 'Số lệnh sản xuất (LSX)',
    title: 'Số lệnh sản xuất điều phối',
    scope: 'Mục 6: Bảng Chi tiết Lệnh',
    formula: 'Số lệnh điều phối định danh từ phòng Kế hoạch',
    source: 'Bảng _ERPPlanDetail (Trường: WorkOrderNo, DocNo)',
    description: 'Mã số chứng từ kế hoạch ban hành cho xưởng sản xuất thực hiện.',
    notes: 'Mỗi lệnh tương ứng với 1 công đoạn gia công.'
  },
  {
    id: 'col_plan_item_name',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'ItemName / ProductName',
    columnName: 'Tên sản phẩm / Mặt hàng',
    title: 'Tên sản phẩm trong kế hoạch',
    scope: 'Mục 6: Bảng Chi tiết Lệnh',
    formula: 'Tên mặt hàng thành phẩm hoặc bán thành phẩm',
    source: 'Bảng _ERPPlanDetail (Trường: ItemName, ItemCode)',
    description: 'Quy cách sản phẩm gia công theo đơn hàng của khách hàng.',
    notes: 'Hiển thị kèm mã mặt hàng ItemCode.'
  },
  {
    id: 'col_plan_target_qty',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'TargetProdQty / PlanQty',
    columnName: 'Sản lượng mục tiêu kế hoạch',
    title: 'Sản lượng mục tiêu kế hoạch (Target Qty)',
    scope: 'Mục 6: Bảng Chi tiết Lệnh',
    formula: 'Số lượng sản phẩm giao khoán theo kế hoạch',
    source: 'Bảng _ERPPlanDetail (Trường: TargetProdQty)',
    description: 'Định mức sản lượng yêu cầu hoàn thành của lệnh sản xuất.',
    notes: 'Căn cứ đối chiếu tỷ lệ đạt của ca máy.'
  },
  {
    id: 'col_plan_stat_pass_qty',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'StatPassQty / ActualQty',
    columnName: 'Sản lượng thực tế đạt',
    title: 'Sản lượng thực tế đạt KCS (Actual Pass Qty)',
    scope: 'Mục 6: Bảng Chi tiết Lệnh',
    formula: 'Số lượng thực tế đạt từ phiếu thống kê tương ứng',
    source: 'Bảng _ERPPlanDetail (Trường: StatPassQty)',
    description: 'Số lượng sản phẩm thực tế đã hoàn thành và đạt chuẩn kiểm tra.',
    notes: 'Đối chiếu trực tiếp với TargetProdQty.'
  },
  {
    id: 'col_plan_date_diff',
    reportType: 'plan',
    reportTypeName: 'Kế hoạch SX (KHSX)',
    category: 'TABLES',
    categoryName: 'IV. Bảng biểu Chi tiết',
    columnId: 'dateDiffDays / OpDate - RoutingDocDate',
    columnName: 'Số ngày chênh lệch kế hoạch',
    title: 'Độ lệch ngày giữa Kế hoạch và Thực tế',
    scope: 'Mục 6: Bảng Chi tiết Lệnh',
    formula: 'DATEDIFF(day, RoutingDocDate, OpDate)',
    source: 'So khớp ngày thực hiện OpDate và ngày điều phối RoutingDocDate',
    description: 'Số ngày làm sớm hơn (-) hoặc muộn hơn (+) so với ngày kế hoạch.',
    notes: '=0: Đúng ngày kế hoạch; >0: Làm muộn; <0: Làm sớm.'
  }
]

// Toàn bộ cơ sở dữ liệu cẩm nang hợp nhất
export const ALL_HANDBOOK_DATABASE = [...STAT_FORMULA_DATABASE, ...PLAN_FORMULA_DATABASE]

// Alias tương thích ngược
export const FORMULA_DATABASE = ALL_HANDBOOK_DATABASE
