export { default as UserManagementPage } from './userManagement'
export { default as UserDetailPage } from './userDetailForm'
export { default as RoleGroupPage } from './roleGroup'
export { default as RoleManagementPage } from './roleManagement'
export { default as RootMenuTechniquePage } from './rootMenuTechnique'
export { default as MenuTechniquePage } from './menuTechnique'
