// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: datahub.proto

package datahub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_datahub_proto protoreflect.FileDescriptor

const file_datahub_proto_rawDesc = "" +
	"\n" +
	"\rdatahub.proto\x12\adatahub\x1a\n" +
	"auth.proto\x1a\fconfig.proto\x1a\x12work_process.proto\x1a\vproxy.proto\x1a\vaudit.proto\x1a\fhealth.proto2\xa0\b\n" +
	"\x0eDataHubService\x12@\n" +
	"\x05Login\x12\x1a.datahub.LoginProtoRequest\x1a\x1b.datahub.LoginProtoResponse\x12I\n" +
	"\n" +
	"GetSession\x12\x1c.datahub.SessionProtoRequest\x1a\x1d.datahub.SessionProtoResponse\x12R\n" +
	"\rGetAllConfigs\x12\x1f.datahub.GetConfigsProtoRequest\x1a .datahub.GetConfigsProtoResponse\x12O\n" +
	"\n" +
	"SaveConfig\x12\x1f.datahub.SaveConfigProtoRequest\x1a .datahub.SaveConfigProtoResponse\x12U\n" +
	"\fDeleteConfig\x12!.datahub.DeleteConfigProtoRequest\x1a\".datahub.DeleteConfigProtoResponse\x12G\n" +
	"\fProxyForward\x12\x1a.datahub.ProxyProtoRequest\x1a\x1b.datahub.ProxyProtoResponse\x12J\n" +
	"\vStreamProxy\x12\x1a.datahub.ProxyProtoRequest\x1a\x1b.datahub.ProxyProtoResponse(\x010\x01\x12W\n" +
	"\x10QueryWorkProcess\x12 .datahub.WorkProcessProtoRequest\x1a!.datahub.WorkProcessProtoResponse\x12K\n" +
	"\fGetFactories\x12\x1c.datahub.FactoryProtoRequest\x1a\x1d.datahub.FactoryProtoResponse\x12X\n" +
	"\x0fGetAllEndpoints\x12!.datahub.GetEndpointsProtoRequest\x1a\".datahub.GetEndpointsProtoResponse\x12U\n" +
	"\fSaveEndpoint\x12!.datahub.SaveEndpointProtoRequest\x1a\".datahub.SaveEndpointProtoResponse\x12O\n" +
	"\fGetAuditLogs\x12\x1e.datahub.AuditLogsProtoRequest\x1a\x1f.datahub.AuditLogsProtoResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.datahub.HealthProtoRequest\x1a\x1c.datahub.HealthProtoResponseB\x1cZ\x1aservice-datahub/pb/datahubb\x06proto3"

var file_datahub_proto_goTypes = []any{
	(*LoginProtoRequest)(nil),         // 0: datahub.LoginProtoRequest
	(*SessionProtoRequest)(nil),       // 1: datahub.SessionProtoRequest
	(*GetConfigsProtoRequest)(nil),    // 2: datahub.GetConfigsProtoRequest
	(*SaveConfigProtoRequest)(nil),    // 3: datahub.SaveConfigProtoRequest
	(*DeleteConfigProtoRequest)(nil),  // 4: datahub.DeleteConfigProtoRequest
	(*ProxyProtoRequest)(nil),         // 5: datahub.ProxyProtoRequest
	(*WorkProcessProtoRequest)(nil),   // 6: datahub.WorkProcessProtoRequest
	(*FactoryProtoRequest)(nil),       // 7: datahub.FactoryProtoRequest
	(*GetEndpointsProtoRequest)(nil),  // 8: datahub.GetEndpointsProtoRequest
	(*SaveEndpointProtoRequest)(nil),  // 9: datahub.SaveEndpointProtoRequest
	(*AuditLogsProtoRequest)(nil),     // 10: datahub.AuditLogsProtoRequest
	(*HealthProtoRequest)(nil),        // 11: datahub.HealthProtoRequest
	(*LoginProtoResponse)(nil),        // 12: datahub.LoginProtoResponse
	(*SessionProtoResponse)(nil),      // 13: datahub.SessionProtoResponse
	(*GetConfigsProtoResponse)(nil),   // 14: datahub.GetConfigsProtoResponse
	(*SaveConfigProtoResponse)(nil),   // 15: datahub.SaveConfigProtoResponse
	(*DeleteConfigProtoResponse)(nil), // 16: datahub.DeleteConfigProtoResponse
	(*ProxyProtoResponse)(nil),        // 17: datahub.ProxyProtoResponse
	(*WorkProcessProtoResponse)(nil),  // 18: datahub.WorkProcessProtoResponse
	(*FactoryProtoResponse)(nil),      // 19: datahub.FactoryProtoResponse
	(*GetEndpointsProtoResponse)(nil), // 20: datahub.GetEndpointsProtoResponse
	(*SaveEndpointProtoResponse)(nil), // 21: datahub.SaveEndpointProtoResponse
	(*AuditLogsProtoResponse)(nil),    // 22: datahub.AuditLogsProtoResponse
	(*HealthProtoResponse)(nil),       // 23: datahub.HealthProtoResponse
}
var file_datahub_proto_depIdxs = []int32{
	0,  // 0: datahub.DataHubService.Login:input_type -> datahub.LoginProtoRequest
	1,  // 1: datahub.DataHubService.GetSession:input_type -> datahub.SessionProtoRequest
	2,  // 2: datahub.DataHubService.GetAllConfigs:input_type -> datahub.GetConfigsProtoRequest
	3,  // 3: datahub.DataHubService.SaveConfig:input_type -> datahub.SaveConfigProtoRequest
	4,  // 4: datahub.DataHubService.DeleteConfig:input_type -> datahub.DeleteConfigProtoRequest
	5,  // 5: datahub.DataHubService.ProxyForward:input_type -> datahub.ProxyProtoRequest
	5,  // 6: datahub.DataHubService.StreamProxy:input_type -> datahub.ProxyProtoRequest
	6,  // 7: datahub.DataHubService.QueryWorkProcess:input_type -> datahub.WorkProcessProtoRequest
	7,  // 8: datahub.DataHubService.GetFactories:input_type -> datahub.FactoryProtoRequest
	8,  // 9: datahub.DataHubService.GetAllEndpoints:input_type -> datahub.GetEndpointsProtoRequest
	9,  // 10: datahub.DataHubService.SaveEndpoint:input_type -> datahub.SaveEndpointProtoRequest
	10, // 11: datahub.DataHubService.GetAuditLogs:input_type -> datahub.AuditLogsProtoRequest
	11, // 12: datahub.DataHubService.HealthCheck:input_type -> datahub.HealthProtoRequest
	12, // 13: datahub.DataHubService.Login:output_type -> datahub.LoginProtoResponse
	13, // 14: datahub.DataHubService.GetSession:output_type -> datahub.SessionProtoResponse
	14, // 15: datahub.DataHubService.GetAllConfigs:output_type -> datahub.GetConfigsProtoResponse
	15, // 16: datahub.DataHubService.SaveConfig:output_type -> datahub.SaveConfigProtoResponse
	16, // 17: datahub.DataHubService.DeleteConfig:output_type -> datahub.DeleteConfigProtoResponse
	17, // 18: datahub.DataHubService.ProxyForward:output_type -> datahub.ProxyProtoResponse
	17, // 19: datahub.DataHubService.StreamProxy:output_type -> datahub.ProxyProtoResponse
	18, // 20: datahub.DataHubService.QueryWorkProcess:output_type -> datahub.WorkProcessProtoResponse
	19, // 21: datahub.DataHubService.GetFactories:output_type -> datahub.FactoryProtoResponse
	20, // 22: datahub.DataHubService.GetAllEndpoints:output_type -> datahub.GetEndpointsProtoResponse
	21, // 23: datahub.DataHubService.SaveEndpoint:output_type -> datahub.SaveEndpointProtoResponse
	22, // 24: datahub.DataHubService.GetAuditLogs:output_type -> datahub.AuditLogsProtoResponse
	23, // 25: datahub.DataHubService.HealthCheck:output_type -> datahub.HealthProtoResponse
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_datahub_proto_init() }
func file_datahub_proto_init() {
	if File_datahub_proto != nil {
		return
	}
	file_auth_proto_init()
	file_config_proto_init()
	file_work_process_proto_init()
	file_proxy_proto_init()
	file_audit_proto_init()
	file_health_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datahub_proto_rawDesc), len(file_datahub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datahub_proto_goTypes,
		DependencyIndexes: file_datahub_proto_depIdxs,
	}.Build()
	File_datahub_proto = out.File
	file_datahub_proto_goTypes = nil
	file_datahub_proto_depIdxs = nil
}
