// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: lookup/wh/help_zone.proto

package help_zone

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HelpZoneService_ZoneH_FullMethodName = "/lookup.wh.help_zone.HelpZoneService/ZoneH"
)

// HelpZoneServiceClient is the client API for HelpZoneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelpZoneServiceClient interface {
	ZoneH(ctx context.Context, in *ZoneHRequest, opts ...grpc.CallOption) (*Response, error)
}

type helpZoneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHelpZoneServiceClient(cc grpc.ClientConnInterface) HelpZoneServiceClient {
	return &helpZoneServiceClient{cc}
}

func (c *helpZoneServiceClient) ZoneH(ctx context.Context, in *ZoneHRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, HelpZoneService_ZoneH_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelpZoneServiceServer is the server API for HelpZoneService service.
// All implementations must embed UnimplementedHelpZoneServiceServer
// for forward compatibility.
type HelpZoneServiceServer interface {
	ZoneH(context.Context, *ZoneHRequest) (*Response, error)
	mustEmbedUnimplementedHelpZoneServiceServer()
}

// UnimplementedHelpZoneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHelpZoneServiceServer struct{}

func (UnimplementedHelpZoneServiceServer) ZoneH(context.Context, *ZoneHRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ZoneH not implemented")
}
func (UnimplementedHelpZoneServiceServer) mustEmbedUnimplementedHelpZoneServiceServer() {}
func (UnimplementedHelpZoneServiceServer) testEmbeddedByValue()                         {}

// UnsafeHelpZoneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelpZoneServiceServer will
// result in compilation errors.
type UnsafeHelpZoneServiceServer interface {
	mustEmbedUnimplementedHelpZoneServiceServer()
}

func RegisterHelpZoneServiceServer(s grpc.ServiceRegistrar, srv HelpZoneServiceServer) {
	// If the following call panics, it indicates UnimplementedHelpZoneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HelpZoneService_ServiceDesc, srv)
}

func _HelpZoneService_ZoneH_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneHRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelpZoneServiceServer).ZoneH(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelpZoneService_ZoneH_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelpZoneServiceServer).ZoneH(ctx, req.(*ZoneHRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HelpZoneService_ServiceDesc is the grpc.ServiceDesc for HelpZoneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelpZoneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lookup.wh.help_zone.HelpZoneService",
	HandlerType: (*HelpZoneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ZoneH",
			Handler:    _HelpZoneService_ZoneH_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lookup/wh/help_zone.proto",
}
