// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: users/langs/langs.proto

package langs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LangAResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdxNo         int32                  `protobuf:"varint,1,opt,name=IdxNo,proto3" json:"IdxNo,omitempty"`
	LanguageCode  string                 `protobuf:"bytes,2,opt,name=LanguageCode,proto3" json:"LanguageCode,omitempty"`
	LanguageName  string                 `protobuf:"bytes,3,opt,name=LanguageName,proto3" json:"LanguageName,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=Remark,proto3" json:"Remark,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LangAResult) Reset() {
	*x = LangAResult{}
	mi := &file_users_langs_langs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LangAResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LangAResult) ProtoMessage() {}

func (x *LangAResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_langs_langs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LangAResult.ProtoReflect.Descriptor instead.
func (*LangAResult) Descriptor() ([]byte, []int) {
	return file_users_langs_langs_proto_rawDescGZIP(), []int{0}
}

func (x *LangAResult) GetIdxNo() int32 {
	if x != nil {
		return x.IdxNo
	}
	return 0
}

func (x *LangAResult) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *LangAResult) GetLanguageName() string {
	if x != nil {
		return x.LanguageName
	}
	return ""
}

func (x *LangAResult) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *LangAResult) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type LangUResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LanguageSeq   int32                  `protobuf:"varint,1,opt,name=LanguageSeq,proto3" json:"LanguageSeq,omitempty"`
	IdxNo         int32                  `protobuf:"varint,2,opt,name=IdxNo,proto3" json:"IdxNo,omitempty"`
	LanguageCode  string                 `protobuf:"bytes,3,opt,name=LanguageCode,proto3" json:"LanguageCode,omitempty"`
	LanguageName  string                 `protobuf:"bytes,4,opt,name=LanguageName,proto3" json:"LanguageName,omitempty"`
	Remark        string                 `protobuf:"bytes,5,opt,name=Remark,proto3" json:"Remark,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,6,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LangUResult) Reset() {
	*x = LangUResult{}
	mi := &file_users_langs_langs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LangUResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LangUResult) ProtoMessage() {}

func (x *LangUResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_langs_langs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LangUResult.ProtoReflect.Descriptor instead.
func (*LangUResult) Descriptor() ([]byte, []int) {
	return file_users_langs_langs_proto_rawDescGZIP(), []int{1}
}

func (x *LangUResult) GetLanguageSeq() int32 {
	if x != nil {
		return x.LanguageSeq
	}
	return 0
}

func (x *LangUResult) GetIdxNo() int32 {
	if x != nil {
		return x.IdxNo
	}
	return 0
}

func (x *LangUResult) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *LangUResult) GetLanguageName() string {
	if x != nil {
		return x.LanguageName
	}
	return ""
}

func (x *LangUResult) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *LangUResult) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type LangDResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LanguageSeq   int32                  `protobuf:"varint,1,opt,name=LanguageSeq,proto3" json:"LanguageSeq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LangDResult) Reset() {
	*x = LangDResult{}
	mi := &file_users_langs_langs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LangDResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LangDResult) ProtoMessage() {}

func (x *LangDResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_langs_langs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LangDResult.ProtoReflect.Descriptor instead.
func (*LangDResult) Descriptor() ([]byte, []int) {
	return file_users_langs_langs_proto_rawDescGZIP(), []int{2}
}

func (x *LangDResult) GetLanguageSeq() int32 {
	if x != nil {
		return x.LanguageSeq
	}
	return 0
}

type LangQResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyItem1      string                 `protobuf:"bytes,1,opt,name=KeyItem1,proto3" json:"KeyItem1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LangQResult) Reset() {
	*x = LangQResult{}
	mi := &file_users_langs_langs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LangQResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LangQResult) ProtoMessage() {}

func (x *LangQResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_langs_langs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LangQResult.ProtoReflect.Descriptor instead.
func (*LangQResult) Descriptor() ([]byte, []int) {
	return file_users_langs_langs_proto_rawDescGZIP(), []int{3}
}

func (x *LangQResult) GetKeyItem1() string {
	if x != nil {
		return x.KeyItem1
	}
	return ""
}

type LangARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*LangAResult         `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LangARequest) Reset() {
	*x = LangARequest{}
	mi := &file_users_langs_langs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LangARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LangARequest) ProtoMessage() {}

func (x *LangARequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_langs_langs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LangARequest.ProtoReflect.Descriptor instead.
func (*LangARequest) Descriptor() ([]byte, []int) {
	return file_users_langs_langs_proto_rawDescGZIP(), []int{4}
}

func (x *LangARequest) GetResult() []*LangAResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *LangARequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type LangURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*LangUResult         `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LangURequest) Reset() {
	*x = LangURequest{}
	mi := &file_users_langs_langs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LangURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LangURequest) ProtoMessage() {}

func (x *LangURequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_langs_langs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LangURequest.ProtoReflect.Descriptor instead.
func (*LangURequest) Descriptor() ([]byte, []int) {
	return file_users_langs_langs_proto_rawDescGZIP(), []int{5}
}

func (x *LangURequest) GetResult() []*LangUResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *LangURequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type LangDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*LangDResult         `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LangDRequest) Reset() {
	*x = LangDRequest{}
	mi := &file_users_langs_langs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LangDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LangDRequest) ProtoMessage() {}

func (x *LangDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_langs_langs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LangDRequest.ProtoReflect.Descriptor instead.
func (*LangDRequest) Descriptor() ([]byte, []int) {
	return file_users_langs_langs_proto_rawDescGZIP(), []int{6}
}

func (x *LangDRequest) GetResult() []*LangDResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *LangDRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type LangQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *LangQResult           `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LangQRequest) Reset() {
	*x = LangQRequest{}
	mi := &file_users_langs_langs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LangQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LangQRequest) ProtoMessage() {}

func (x *LangQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_langs_langs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LangQRequest.ProtoReflect.Descriptor instead.
func (*LangQRequest) Descriptor() ([]byte, []int) {
	return file_users_langs_langs_proto_rawDescGZIP(), []int{7}
}

func (x *LangQRequest) GetResult() *LangQResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *LangQRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Page          string                 `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_users_langs_langs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_users_langs_langs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_users_langs_langs_proto_rawDescGZIP(), []int{8}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Response) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

var File_users_langs_langs_proto protoreflect.FileDescriptor

const file_users_langs_langs_proto_rawDesc = "" +
	"\n" +
	"\x17users/langs/langs.proto\x12\x11users.langs.langs\"\xa1\x01\n" +
	"\vLangAResult\x12\x14\n" +
	"\x05IdxNo\x18\x01 \x01(\x05R\x05IdxNo\x12\"\n" +
	"\fLanguageCode\x18\x02 \x01(\tR\fLanguageCode\x12\"\n" +
	"\fLanguageName\x18\x03 \x01(\tR\fLanguageName\x12\x16\n" +
	"\x06Remark\x18\x04 \x01(\tR\x06Remark\x12\x1c\n" +
	"\tCreatedBy\x18\x05 \x01(\tR\tCreatedBy\"\xc3\x01\n" +
	"\vLangUResult\x12 \n" +
	"\vLanguageSeq\x18\x01 \x01(\x05R\vLanguageSeq\x12\x14\n" +
	"\x05IdxNo\x18\x02 \x01(\x05R\x05IdxNo\x12\"\n" +
	"\fLanguageCode\x18\x03 \x01(\tR\fLanguageCode\x12\"\n" +
	"\fLanguageName\x18\x04 \x01(\tR\fLanguageName\x12\x16\n" +
	"\x06Remark\x18\x05 \x01(\tR\x06Remark\x12\x1c\n" +
	"\tUpdatedBy\x18\x06 \x01(\tR\tUpdatedBy\"/\n" +
	"\vLangDResult\x12 \n" +
	"\vLanguageSeq\x18\x01 \x01(\x05R\vLanguageSeq\")\n" +
	"\vLangQResult\x12\x1a\n" +
	"\bKeyItem1\x18\x01 \x01(\tR\bKeyItem1\"\xce\x01\n" +
	"\fLangARequest\x126\n" +
	"\x06result\x18\x01 \x03(\v2\x1e.users.langs.langs.LangAResultR\x06result\x12I\n" +
	"\bmetadata\x18\x02 \x03(\v2-.users.langs.langs.LangARequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xce\x01\n" +
	"\fLangURequest\x126\n" +
	"\x06result\x18\x01 \x03(\v2\x1e.users.langs.langs.LangUResultR\x06result\x12I\n" +
	"\bmetadata\x18\x02 \x03(\v2-.users.langs.langs.LangURequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xce\x01\n" +
	"\fLangDRequest\x126\n" +
	"\x06result\x18\x01 \x03(\v2\x1e.users.langs.langs.LangDResultR\x06result\x12I\n" +
	"\bmetadata\x18\x02 \x03(\v2-.users.langs.langs.LangDRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xce\x01\n" +
	"\fLangQRequest\x126\n" +
	"\x06result\x18\x01 \x01(\v2\x1e.users.langs.langs.LangQResultR\x06result\x12I\n" +
	"\bmetadata\x18\x02 \x03(\v2-.users.langs.langs.LangQRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x12\n" +
	"\x04page\x18\x04 \x01(\tR\x04page2\xaa\x02\n" +
	"\fLangsService\x12E\n" +
	"\x05LangA\x12\x1f.users.langs.langs.LangARequest\x1a\x1b.users.langs.langs.Response\x12E\n" +
	"\x05LangU\x12\x1f.users.langs.langs.LangURequest\x1a\x1b.users.langs.langs.Response\x12E\n" +
	"\x05LangD\x12\x1f.users.langs.langs.LangDRequest\x1a\x1b.users.langs.langs.Response\x12E\n" +
	"\x05LangQ\x12\x1f.users.langs.langs.LangQRequest\x1a\x1b.users.langs.langs.ResponseB%Z#server-core/proto/users/langs/langsb\x06proto3"

var (
	file_users_langs_langs_proto_rawDescOnce sync.Once
	file_users_langs_langs_proto_rawDescData []byte
)

func file_users_langs_langs_proto_rawDescGZIP() []byte {
	file_users_langs_langs_proto_rawDescOnce.Do(func() {
		file_users_langs_langs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_langs_langs_proto_rawDesc), len(file_users_langs_langs_proto_rawDesc)))
	})
	return file_users_langs_langs_proto_rawDescData
}

var file_users_langs_langs_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_users_langs_langs_proto_goTypes = []any{
	(*LangAResult)(nil),  // 0: users.langs.langs.LangAResult
	(*LangUResult)(nil),  // 1: users.langs.langs.LangUResult
	(*LangDResult)(nil),  // 2: users.langs.langs.LangDResult
	(*LangQResult)(nil),  // 3: users.langs.langs.LangQResult
	(*LangARequest)(nil), // 4: users.langs.langs.LangARequest
	(*LangURequest)(nil), // 5: users.langs.langs.LangURequest
	(*LangDRequest)(nil), // 6: users.langs.langs.LangDRequest
	(*LangQRequest)(nil), // 7: users.langs.langs.LangQRequest
	(*Response)(nil),     // 8: users.langs.langs.Response
	nil,                  // 9: users.langs.langs.LangARequest.MetadataEntry
	nil,                  // 10: users.langs.langs.LangURequest.MetadataEntry
	nil,                  // 11: users.langs.langs.LangDRequest.MetadataEntry
	nil,                  // 12: users.langs.langs.LangQRequest.MetadataEntry
}
var file_users_langs_langs_proto_depIdxs = []int32{
	0,  // 0: users.langs.langs.LangARequest.result:type_name -> users.langs.langs.LangAResult
	9,  // 1: users.langs.langs.LangARequest.metadata:type_name -> users.langs.langs.LangARequest.MetadataEntry
	1,  // 2: users.langs.langs.LangURequest.result:type_name -> users.langs.langs.LangUResult
	10, // 3: users.langs.langs.LangURequest.metadata:type_name -> users.langs.langs.LangURequest.MetadataEntry
	2,  // 4: users.langs.langs.LangDRequest.result:type_name -> users.langs.langs.LangDResult
	11, // 5: users.langs.langs.LangDRequest.metadata:type_name -> users.langs.langs.LangDRequest.MetadataEntry
	3,  // 6: users.langs.langs.LangQRequest.result:type_name -> users.langs.langs.LangQResult
	12, // 7: users.langs.langs.LangQRequest.metadata:type_name -> users.langs.langs.LangQRequest.MetadataEntry
	4,  // 8: users.langs.langs.LangsService.LangA:input_type -> users.langs.langs.LangARequest
	5,  // 9: users.langs.langs.LangsService.LangU:input_type -> users.langs.langs.LangURequest
	6,  // 10: users.langs.langs.LangsService.LangD:input_type -> users.langs.langs.LangDRequest
	7,  // 11: users.langs.langs.LangsService.LangQ:input_type -> users.langs.langs.LangQRequest
	8,  // 12: users.langs.langs.LangsService.LangA:output_type -> users.langs.langs.Response
	8,  // 13: users.langs.langs.LangsService.LangU:output_type -> users.langs.langs.Response
	8,  // 14: users.langs.langs.LangsService.LangD:output_type -> users.langs.langs.Response
	8,  // 15: users.langs.langs.LangsService.LangQ:output_type -> users.langs.langs.Response
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_users_langs_langs_proto_init() }
func file_users_langs_langs_proto_init() {
	if File_users_langs_langs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_langs_langs_proto_rawDesc), len(file_users_langs_langs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_langs_langs_proto_goTypes,
		DependencyIndexes: file_users_langs_langs_proto_depIdxs,
		MessageInfos:      file_users_langs_langs_proto_msgTypes,
	}.Build()
	File_users_langs_langs_proto = out.File
	file_users_langs_langs_proto_goTypes = nil
	file_users_langs_langs_proto_depIdxs = nil
}
