// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: users/app/screens.proto

package screens

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScreensAResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdxNo         int32                  `protobuf:"varint,1,opt,name=IdxNo,proto3" json:"IdxNo,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,2,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,3,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	TabSeq        string                 `protobuf:"bytes,4,opt,name=TabSeq,proto3" json:"TabSeq,omitempty"`
	ScreenKey     string                 `protobuf:"bytes,5,opt,name=ScreenKey,proto3" json:"ScreenKey,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=Path,proto3" json:"Path,omitempty"`
	LangSeq       int32                  `protobuf:"varint,8,opt,name=LangSeq,proto3" json:"LangSeq,omitempty"`
	ScreenName    string                 `protobuf:"bytes,9,opt,name=ScreenName,proto3" json:"ScreenName,omitempty"`
	Order         int32                  `protobuf:"varint,10,opt,name=Order,proto3" json:"Order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreensAResult) Reset() {
	*x = ScreensAResult{}
	mi := &file_users_app_screens_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreensAResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreensAResult) ProtoMessage() {}

func (x *ScreensAResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_screens_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreensAResult.ProtoReflect.Descriptor instead.
func (*ScreensAResult) Descriptor() ([]byte, []int) {
	return file_users_app_screens_proto_rawDescGZIP(), []int{0}
}

func (x *ScreensAResult) GetIdxNo() int32 {
	if x != nil {
		return x.IdxNo
	}
	return 0
}

func (x *ScreensAResult) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ScreensAResult) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *ScreensAResult) GetTabSeq() string {
	if x != nil {
		return x.TabSeq
	}
	return ""
}

func (x *ScreensAResult) GetScreenKey() string {
	if x != nil {
		return x.ScreenKey
	}
	return ""
}

func (x *ScreensAResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ScreensAResult) GetLangSeq() int32 {
	if x != nil {
		return x.LangSeq
	}
	return 0
}

func (x *ScreensAResult) GetScreenName() string {
	if x != nil {
		return x.ScreenName
	}
	return ""
}

func (x *ScreensAResult) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type ScreensUResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdxNo         int32                  `protobuf:"varint,1,opt,name=IdxNo,proto3" json:"IdxNo,omitempty"`
	IdSeq         string                 `protobuf:"bytes,2,opt,name=IdSeq,proto3" json:"IdSeq,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,3,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	TabSeq        string                 `protobuf:"bytes,4,opt,name=TabSeq,proto3" json:"TabSeq,omitempty"`
	ScreenKey     string                 `protobuf:"bytes,5,opt,name=ScreenKey,proto3" json:"ScreenKey,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=Path,proto3" json:"Path,omitempty"`
	LangSeq       int32                  `protobuf:"varint,8,opt,name=LangSeq,proto3" json:"LangSeq,omitempty"`
	ScreenName    string                 `protobuf:"bytes,9,opt,name=ScreenName,proto3" json:"ScreenName,omitempty"`
	Order         int32                  `protobuf:"varint,10,opt,name=Order,proto3" json:"Order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreensUResult) Reset() {
	*x = ScreensUResult{}
	mi := &file_users_app_screens_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreensUResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreensUResult) ProtoMessage() {}

func (x *ScreensUResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_screens_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreensUResult.ProtoReflect.Descriptor instead.
func (*ScreensUResult) Descriptor() ([]byte, []int) {
	return file_users_app_screens_proto_rawDescGZIP(), []int{1}
}

func (x *ScreensUResult) GetIdxNo() int32 {
	if x != nil {
		return x.IdxNo
	}
	return 0
}

func (x *ScreensUResult) GetIdSeq() string {
	if x != nil {
		return x.IdSeq
	}
	return ""
}

func (x *ScreensUResult) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *ScreensUResult) GetTabSeq() string {
	if x != nil {
		return x.TabSeq
	}
	return ""
}

func (x *ScreensUResult) GetScreenKey() string {
	if x != nil {
		return x.ScreenKey
	}
	return ""
}

func (x *ScreensUResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ScreensUResult) GetLangSeq() int32 {
	if x != nil {
		return x.LangSeq
	}
	return 0
}

func (x *ScreensUResult) GetScreenName() string {
	if x != nil {
		return x.ScreenName
	}
	return ""
}

func (x *ScreensUResult) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type ScreensDResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdSeq         string                 `protobuf:"bytes,1,opt,name=IdSeq,proto3" json:"IdSeq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreensDResult) Reset() {
	*x = ScreensDResult{}
	mi := &file_users_app_screens_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreensDResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreensDResult) ProtoMessage() {}

func (x *ScreensDResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_screens_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreensDResult.ProtoReflect.Descriptor instead.
func (*ScreensDResult) Descriptor() ([]byte, []int) {
	return file_users_app_screens_proto_rawDescGZIP(), []int{2}
}

func (x *ScreensDResult) GetIdSeq() string {
	if x != nil {
		return x.IdSeq
	}
	return ""
}

type ScreensQResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyItem1      string                 `protobuf:"bytes,1,opt,name=KeyItem1,proto3" json:"KeyItem1,omitempty"`
	KeyItem2      string                 `protobuf:"bytes,2,opt,name=KeyItem2,proto3" json:"KeyItem2,omitempty"`
	KeyItem3      string                 `protobuf:"bytes,3,opt,name=KeyItem3,proto3" json:"KeyItem3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreensQResult) Reset() {
	*x = ScreensQResult{}
	mi := &file_users_app_screens_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreensQResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreensQResult) ProtoMessage() {}

func (x *ScreensQResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_screens_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreensQResult.ProtoReflect.Descriptor instead.
func (*ScreensQResult) Descriptor() ([]byte, []int) {
	return file_users_app_screens_proto_rawDescGZIP(), []int{3}
}

func (x *ScreensQResult) GetKeyItem1() string {
	if x != nil {
		return x.KeyItem1
	}
	return ""
}

func (x *ScreensQResult) GetKeyItem2() string {
	if x != nil {
		return x.KeyItem2
	}
	return ""
}

func (x *ScreensQResult) GetKeyItem3() string {
	if x != nil {
		return x.KeyItem3
	}
	return ""
}

type ScreensARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*ScreensAResult      `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreensARequest) Reset() {
	*x = ScreensARequest{}
	mi := &file_users_app_screens_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreensARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreensARequest) ProtoMessage() {}

func (x *ScreensARequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_screens_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreensARequest.ProtoReflect.Descriptor instead.
func (*ScreensARequest) Descriptor() ([]byte, []int) {
	return file_users_app_screens_proto_rawDescGZIP(), []int{4}
}

func (x *ScreensARequest) GetResult() []*ScreensAResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ScreensARequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ScreensURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*ScreensUResult      `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreensURequest) Reset() {
	*x = ScreensURequest{}
	mi := &file_users_app_screens_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreensURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreensURequest) ProtoMessage() {}

func (x *ScreensURequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_screens_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreensURequest.ProtoReflect.Descriptor instead.
func (*ScreensURequest) Descriptor() ([]byte, []int) {
	return file_users_app_screens_proto_rawDescGZIP(), []int{5}
}

func (x *ScreensURequest) GetResult() []*ScreensUResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ScreensURequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ScreensDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*ScreensDResult      `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreensDRequest) Reset() {
	*x = ScreensDRequest{}
	mi := &file_users_app_screens_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreensDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreensDRequest) ProtoMessage() {}

func (x *ScreensDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_screens_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreensDRequest.ProtoReflect.Descriptor instead.
func (*ScreensDRequest) Descriptor() ([]byte, []int) {
	return file_users_app_screens_proto_rawDescGZIP(), []int{6}
}

func (x *ScreensDRequest) GetResult() []*ScreensDResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ScreensDRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ScreensQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ScreensQResult        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreensQRequest) Reset() {
	*x = ScreensQRequest{}
	mi := &file_users_app_screens_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreensQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreensQRequest) ProtoMessage() {}

func (x *ScreensQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_screens_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreensQRequest.ProtoReflect.Descriptor instead.
func (*ScreensQRequest) Descriptor() ([]byte, []int) {
	return file_users_app_screens_proto_rawDescGZIP(), []int{7}
}

func (x *ScreensQRequest) GetResult() *ScreensQResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ScreensQRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Page          string                 `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_users_app_screens_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_screens_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_users_app_screens_proto_rawDescGZIP(), []int{8}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Response) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

var File_users_app_screens_proto protoreflect.FileDescriptor

const file_users_app_screens_proto_rawDesc = "" +
	"\n" +
	"\x17users/app/screens.proto\x12\x11users.app.screens\"\xfc\x01\n" +
	"\x0eScreensAResult\x12\x14\n" +
	"\x05IdxNo\x18\x01 \x01(\x05R\x05IdxNo\x12\x1c\n" +
	"\tCreatedBy\x18\x02 \x01(\tR\tCreatedBy\x12\x1c\n" +
	"\tUpdatedBy\x18\x03 \x01(\tR\tUpdatedBy\x12\x16\n" +
	"\x06TabSeq\x18\x04 \x01(\tR\x06TabSeq\x12\x1c\n" +
	"\tScreenKey\x18\x05 \x01(\tR\tScreenKey\x12\x12\n" +
	"\x04Path\x18\a \x01(\tR\x04Path\x12\x18\n" +
	"\aLangSeq\x18\b \x01(\x05R\aLangSeq\x12\x1e\n" +
	"\n" +
	"ScreenName\x18\t \x01(\tR\n" +
	"ScreenName\x12\x14\n" +
	"\x05Order\x18\n" +
	" \x01(\x05R\x05Order\"\xf4\x01\n" +
	"\x0eScreensUResult\x12\x14\n" +
	"\x05IdxNo\x18\x01 \x01(\x05R\x05IdxNo\x12\x14\n" +
	"\x05IdSeq\x18\x02 \x01(\tR\x05IdSeq\x12\x1c\n" +
	"\tUpdatedBy\x18\x03 \x01(\tR\tUpdatedBy\x12\x16\n" +
	"\x06TabSeq\x18\x04 \x01(\tR\x06TabSeq\x12\x1c\n" +
	"\tScreenKey\x18\x05 \x01(\tR\tScreenKey\x12\x12\n" +
	"\x04Path\x18\a \x01(\tR\x04Path\x12\x18\n" +
	"\aLangSeq\x18\b \x01(\x05R\aLangSeq\x12\x1e\n" +
	"\n" +
	"ScreenName\x18\t \x01(\tR\n" +
	"ScreenName\x12\x14\n" +
	"\x05Order\x18\n" +
	" \x01(\x05R\x05Order\"&\n" +
	"\x0eScreensDResult\x12\x14\n" +
	"\x05IdSeq\x18\x01 \x01(\tR\x05IdSeq\"d\n" +
	"\x0eScreensQResult\x12\x1a\n" +
	"\bKeyItem1\x18\x01 \x01(\tR\bKeyItem1\x12\x1a\n" +
	"\bKeyItem2\x18\x02 \x01(\tR\bKeyItem2\x12\x1a\n" +
	"\bKeyItem3\x18\x03 \x01(\tR\bKeyItem3\"\xd7\x01\n" +
	"\x0fScreensARequest\x129\n" +
	"\x06result\x18\x01 \x03(\v2!.users.app.screens.ScreensAResultR\x06result\x12L\n" +
	"\bmetadata\x18\x02 \x03(\v20.users.app.screens.ScreensARequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x01\n" +
	"\x0fScreensURequest\x129\n" +
	"\x06result\x18\x01 \x03(\v2!.users.app.screens.ScreensUResultR\x06result\x12L\n" +
	"\bmetadata\x18\x02 \x03(\v20.users.app.screens.ScreensURequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x01\n" +
	"\x0fScreensDRequest\x129\n" +
	"\x06result\x18\x01 \x03(\v2!.users.app.screens.ScreensDResultR\x06result\x12L\n" +
	"\bmetadata\x18\x02 \x03(\v20.users.app.screens.ScreensDRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x01\n" +
	"\x0fScreensQRequest\x129\n" +
	"\x06result\x18\x01 \x01(\v2!.users.app.screens.ScreensQResultR\x06result\x12L\n" +
	"\bmetadata\x18\x02 \x03(\v20.users.app.screens.ScreensQRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x12\n" +
	"\x04page\x18\x04 \x01(\tR\x04page2\xc4\x02\n" +
	"\x0eScreensService\x12K\n" +
	"\bScreensA\x12\".users.app.screens.ScreensARequest\x1a\x1b.users.app.screens.Response\x12K\n" +
	"\bScreensU\x12\".users.app.screens.ScreensURequest\x1a\x1b.users.app.screens.Response\x12K\n" +
	"\bScreensD\x12\".users.app.screens.ScreensDRequest\x1a\x1b.users.app.screens.Response\x12K\n" +
	"\bScreensQ\x12\".users.app.screens.ScreensQRequest\x1a\x1b.users.app.screens.ResponseB%Z#server-core/proto/users/app/screensb\x06proto3"

var (
	file_users_app_screens_proto_rawDescOnce sync.Once
	file_users_app_screens_proto_rawDescData []byte
)

func file_users_app_screens_proto_rawDescGZIP() []byte {
	file_users_app_screens_proto_rawDescOnce.Do(func() {
		file_users_app_screens_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_app_screens_proto_rawDesc), len(file_users_app_screens_proto_rawDesc)))
	})
	return file_users_app_screens_proto_rawDescData
}

var file_users_app_screens_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_users_app_screens_proto_goTypes = []any{
	(*ScreensAResult)(nil),  // 0: users.app.screens.ScreensAResult
	(*ScreensUResult)(nil),  // 1: users.app.screens.ScreensUResult
	(*ScreensDResult)(nil),  // 2: users.app.screens.ScreensDResult
	(*ScreensQResult)(nil),  // 3: users.app.screens.ScreensQResult
	(*ScreensARequest)(nil), // 4: users.app.screens.ScreensARequest
	(*ScreensURequest)(nil), // 5: users.app.screens.ScreensURequest
	(*ScreensDRequest)(nil), // 6: users.app.screens.ScreensDRequest
	(*ScreensQRequest)(nil), // 7: users.app.screens.ScreensQRequest
	(*Response)(nil),        // 8: users.app.screens.Response
	nil,                     // 9: users.app.screens.ScreensARequest.MetadataEntry
	nil,                     // 10: users.app.screens.ScreensURequest.MetadataEntry
	nil,                     // 11: users.app.screens.ScreensDRequest.MetadataEntry
	nil,                     // 12: users.app.screens.ScreensQRequest.MetadataEntry
}
var file_users_app_screens_proto_depIdxs = []int32{
	0,  // 0: users.app.screens.ScreensARequest.result:type_name -> users.app.screens.ScreensAResult
	9,  // 1: users.app.screens.ScreensARequest.metadata:type_name -> users.app.screens.ScreensARequest.MetadataEntry
	1,  // 2: users.app.screens.ScreensURequest.result:type_name -> users.app.screens.ScreensUResult
	10, // 3: users.app.screens.ScreensURequest.metadata:type_name -> users.app.screens.ScreensURequest.MetadataEntry
	2,  // 4: users.app.screens.ScreensDRequest.result:type_name -> users.app.screens.ScreensDResult
	11, // 5: users.app.screens.ScreensDRequest.metadata:type_name -> users.app.screens.ScreensDRequest.MetadataEntry
	3,  // 6: users.app.screens.ScreensQRequest.result:type_name -> users.app.screens.ScreensQResult
	12, // 7: users.app.screens.ScreensQRequest.metadata:type_name -> users.app.screens.ScreensQRequest.MetadataEntry
	4,  // 8: users.app.screens.ScreensService.ScreensA:input_type -> users.app.screens.ScreensARequest
	5,  // 9: users.app.screens.ScreensService.ScreensU:input_type -> users.app.screens.ScreensURequest
	6,  // 10: users.app.screens.ScreensService.ScreensD:input_type -> users.app.screens.ScreensDRequest
	7,  // 11: users.app.screens.ScreensService.ScreensQ:input_type -> users.app.screens.ScreensQRequest
	8,  // 12: users.app.screens.ScreensService.ScreensA:output_type -> users.app.screens.Response
	8,  // 13: users.app.screens.ScreensService.ScreensU:output_type -> users.app.screens.Response
	8,  // 14: users.app.screens.ScreensService.ScreensD:output_type -> users.app.screens.Response
	8,  // 15: users.app.screens.ScreensService.ScreensQ:output_type -> users.app.screens.Response
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_users_app_screens_proto_init() }
func file_users_app_screens_proto_init() {
	if File_users_app_screens_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_app_screens_proto_rawDesc), len(file_users_app_screens_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_app_screens_proto_goTypes,
		DependencyIndexes: file_users_app_screens_proto_depIdxs,
		MessageInfos:      file_users_app_screens_proto_msgTypes,
	}.Build()
	File_users_app_screens_proto = out.File
	file_users_app_screens_proto_goTypes = nil
	file_users_app_screens_proto_depIdxs = nil
}
