// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: users/roles/perm_actions.proto

package perm_actions

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PermActionsService_PermActionsA_FullMethodName = "/users.roles.perm_actions.PermActionsService/PermActionsA"
	PermActionsService_PermActionsU_FullMethodName = "/users.roles.perm_actions.PermActionsService/PermActionsU"
	PermActionsService_PermActionsD_FullMethodName = "/users.roles.perm_actions.PermActionsService/PermActionsD"
	PermActionsService_PermActionsQ_FullMethodName = "/users.roles.perm_actions.PermActionsService/PermActionsQ"
)

// PermActionsServiceClient is the client API for PermActionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PermActionsServiceClient interface {
	PermActionsA(ctx context.Context, in *PermActionsARequest, opts ...grpc.CallOption) (*Response, error)
	PermActionsU(ctx context.Context, in *PermActionsURequest, opts ...grpc.CallOption) (*Response, error)
	PermActionsD(ctx context.Context, in *PermActionsDRequest, opts ...grpc.CallOption) (*Response, error)
	PermActionsQ(ctx context.Context, in *PermActionsQRequest, opts ...grpc.CallOption) (*Response, error)
}

type permActionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPermActionsServiceClient(cc grpc.ClientConnInterface) PermActionsServiceClient {
	return &permActionsServiceClient{cc}
}

func (c *permActionsServiceClient) PermActionsA(ctx context.Context, in *PermActionsARequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PermActionsService_PermActionsA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permActionsServiceClient) PermActionsU(ctx context.Context, in *PermActionsURequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PermActionsService_PermActionsU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permActionsServiceClient) PermActionsD(ctx context.Context, in *PermActionsDRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PermActionsService_PermActionsD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permActionsServiceClient) PermActionsQ(ctx context.Context, in *PermActionsQRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PermActionsService_PermActionsQ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermActionsServiceServer is the server API for PermActionsService service.
// All implementations must embed UnimplementedPermActionsServiceServer
// for forward compatibility.
type PermActionsServiceServer interface {
	PermActionsA(context.Context, *PermActionsARequest) (*Response, error)
	PermActionsU(context.Context, *PermActionsURequest) (*Response, error)
	PermActionsD(context.Context, *PermActionsDRequest) (*Response, error)
	PermActionsQ(context.Context, *PermActionsQRequest) (*Response, error)
	mustEmbedUnimplementedPermActionsServiceServer()
}

// UnimplementedPermActionsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPermActionsServiceServer struct{}

func (UnimplementedPermActionsServiceServer) PermActionsA(context.Context, *PermActionsARequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method PermActionsA not implemented")
}
func (UnimplementedPermActionsServiceServer) PermActionsU(context.Context, *PermActionsURequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method PermActionsU not implemented")
}
func (UnimplementedPermActionsServiceServer) PermActionsD(context.Context, *PermActionsDRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method PermActionsD not implemented")
}
func (UnimplementedPermActionsServiceServer) PermActionsQ(context.Context, *PermActionsQRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method PermActionsQ not implemented")
}
func (UnimplementedPermActionsServiceServer) mustEmbedUnimplementedPermActionsServiceServer() {}
func (UnimplementedPermActionsServiceServer) testEmbeddedByValue()                            {}

// UnsafePermActionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermActionsServiceServer will
// result in compilation errors.
type UnsafePermActionsServiceServer interface {
	mustEmbedUnimplementedPermActionsServiceServer()
}

func RegisterPermActionsServiceServer(s grpc.ServiceRegistrar, srv PermActionsServiceServer) {
	// If the following call panics, it indicates UnimplementedPermActionsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PermActionsService_ServiceDesc, srv)
}

func _PermActionsService_PermActionsA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermActionsARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermActionsServiceServer).PermActionsA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermActionsService_PermActionsA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermActionsServiceServer).PermActionsA(ctx, req.(*PermActionsARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermActionsService_PermActionsU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermActionsURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermActionsServiceServer).PermActionsU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermActionsService_PermActionsU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermActionsServiceServer).PermActionsU(ctx, req.(*PermActionsURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermActionsService_PermActionsD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermActionsDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermActionsServiceServer).PermActionsD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermActionsService_PermActionsD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermActionsServiceServer).PermActionsD(ctx, req.(*PermActionsDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermActionsService_PermActionsQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermActionsQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermActionsServiceServer).PermActionsQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermActionsService_PermActionsQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermActionsServiceServer).PermActionsQ(ctx, req.(*PermActionsQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PermActionsService_ServiceDesc is the grpc.ServiceDesc for PermActionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PermActionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.roles.perm_actions.PermActionsService",
	HandlerType: (*PermActionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PermActionsA",
			Handler:    _PermActionsService_PermActionsA_Handler,
		},
		{
			MethodName: "PermActionsU",
			Handler:    _PermActionsService_PermActionsU_Handler,
		},
		{
			MethodName: "PermActionsD",
			Handler:    _PermActionsService_PermActionsD_Handler,
		},
		{
			MethodName: "PermActionsQ",
			Handler:    _PermActionsService_PermActionsQ_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users/roles/perm_actions.proto",
}
