syntax = "proto3";

package users.roles.perm_actions;

option go_package = "server-core/proto/users/roles/perm_actions";

service PermActionsService {
  rpc PermActionsA (PermActionsARequest) returns (Response);
  rpc PermActionsU (PermActionsURequest) returns (Response);
  rpc PermActionsD (PermActionsDRequest) returns (Response);
  rpc PermActionsQ (PermActionsQRequest) returns (Response);
}

message PermActionsAResult {
  int32 IdxNo = 1;
  string ActionCode = 2;
  string ActionName = 3;
  string LangKey = 4;
  bool IsDefaultAllow = 5;
  string Comment = 6;
  int64 RowVersion = 7;
  string CreatedBy = 8;
  string UpdatedBy = 9;
}

message PermActionsUResult {
  int32 IdxNo = 1;
  string IdSeq = 2;
  string ActionCode = 3;
  string ActionName = 4;
  string LangKey = 5;
  bool IsDefaultAllow = 6;
  string Comment = 7;
  int64 RowVersion = 8;
  string UpdatedBy = 9;
}

message PermActionsDResult {
  string IdSeq = 1;
  int64 RowVersion = 2;
}

message PermActionsQResult {
  string ActionCode = 1;
  string ActionName = 2;
  string KeyItem1 = 3;
  string KeyItem2 = 4;
  string KeyItem3 = 5;
}

message PermActionsARequest {
  repeated PermActionsAResult result = 1;
  map<string, string> metadata = 2;
}

message PermActionsURequest {
  repeated PermActionsUResult result = 1;
  map<string, string> metadata = 2;
}

message PermActionsDRequest {
  repeated PermActionsDResult result = 1;
  map<string, string> metadata = 2;
}

message PermActionsQRequest {
  PermActionsQResult result = 1;
  map<string, string> metadata = 2;
}

message Response {
  bool success = 1;
  string message = 2;
  string data = 3;
  string page = 4;
}
