// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: lookup/basic/help_define.proto

package help_define

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HelpDefineService_OrgDefineH_FullMethodName             = "/lookup.basic.help_define.HelpDefineService/OrgDefineH"
	HelpDefineService_OrgDefineItemH_FullMethodName         = "/lookup.basic.help_define.HelpDefineService/OrgDefineItemH"
	HelpDefineService_OrgCodeHelpDefineItemH_FullMethodName = "/lookup.basic.help_define.HelpDefineService/OrgCodeHelpDefineItemH"
	HelpDefineService_HelpDefineItemAppH_FullMethodName     = "/lookup.basic.help_define.HelpDefineService/HelpDefineItemAppH"
)

// HelpDefineServiceClient is the client API for HelpDefineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelpDefineServiceClient interface {
	OrgDefineH(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error)
	OrgDefineItemH(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error)
	OrgCodeHelpDefineItemH(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error)
	HelpDefineItemAppH(ctx context.Context, in *HelpDefineItemAppRequest, opts ...grpc.CallOption) (*HelpDefineItemAppResponse, error)
}

type helpDefineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHelpDefineServiceClient(cc grpc.ClientConnInterface) HelpDefineServiceClient {
	return &helpDefineServiceClient{cc}
}

func (c *helpDefineServiceClient) OrgDefineH(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, HelpDefineService_OrgDefineH_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helpDefineServiceClient) OrgDefineItemH(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, HelpDefineService_OrgDefineItemH_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helpDefineServiceClient) OrgCodeHelpDefineItemH(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, HelpDefineService_OrgCodeHelpDefineItemH_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helpDefineServiceClient) HelpDefineItemAppH(ctx context.Context, in *HelpDefineItemAppRequest, opts ...grpc.CallOption) (*HelpDefineItemAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelpDefineItemAppResponse)
	err := c.cc.Invoke(ctx, HelpDefineService_HelpDefineItemAppH_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelpDefineServiceServer is the server API for HelpDefineService service.
// All implementations must embed UnimplementedHelpDefineServiceServer
// for forward compatibility.
type HelpDefineServiceServer interface {
	OrgDefineH(context.Context, *Empty) (*Response, error)
	OrgDefineItemH(context.Context, *Empty) (*Response, error)
	OrgCodeHelpDefineItemH(context.Context, *Empty) (*Response, error)
	HelpDefineItemAppH(context.Context, *HelpDefineItemAppRequest) (*HelpDefineItemAppResponse, error)
	mustEmbedUnimplementedHelpDefineServiceServer()
}

// UnimplementedHelpDefineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHelpDefineServiceServer struct{}

func (UnimplementedHelpDefineServiceServer) OrgDefineH(context.Context, *Empty) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgDefineH not implemented")
}
func (UnimplementedHelpDefineServiceServer) OrgDefineItemH(context.Context, *Empty) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgDefineItemH not implemented")
}
func (UnimplementedHelpDefineServiceServer) OrgCodeHelpDefineItemH(context.Context, *Empty) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgCodeHelpDefineItemH not implemented")
}
func (UnimplementedHelpDefineServiceServer) HelpDefineItemAppH(context.Context, *HelpDefineItemAppRequest) (*HelpDefineItemAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HelpDefineItemAppH not implemented")
}
func (UnimplementedHelpDefineServiceServer) mustEmbedUnimplementedHelpDefineServiceServer() {}
func (UnimplementedHelpDefineServiceServer) testEmbeddedByValue()                           {}

// UnsafeHelpDefineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelpDefineServiceServer will
// result in compilation errors.
type UnsafeHelpDefineServiceServer interface {
	mustEmbedUnimplementedHelpDefineServiceServer()
}

func RegisterHelpDefineServiceServer(s grpc.ServiceRegistrar, srv HelpDefineServiceServer) {
	// If the following call panics, it indicates UnimplementedHelpDefineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HelpDefineService_ServiceDesc, srv)
}

func _HelpDefineService_OrgDefineH_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelpDefineServiceServer).OrgDefineH(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelpDefineService_OrgDefineH_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelpDefineServiceServer).OrgDefineH(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelpDefineService_OrgDefineItemH_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelpDefineServiceServer).OrgDefineItemH(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelpDefineService_OrgDefineItemH_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelpDefineServiceServer).OrgDefineItemH(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelpDefineService_OrgCodeHelpDefineItemH_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelpDefineServiceServer).OrgCodeHelpDefineItemH(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelpDefineService_OrgCodeHelpDefineItemH_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelpDefineServiceServer).OrgCodeHelpDefineItemH(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelpDefineService_HelpDefineItemAppH_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelpDefineItemAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelpDefineServiceServer).HelpDefineItemAppH(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelpDefineService_HelpDefineItemAppH_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelpDefineServiceServer).HelpDefineItemAppH(ctx, req.(*HelpDefineItemAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HelpDefineService_ServiceDesc is the grpc.ServiceDesc for HelpDefineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelpDefineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lookup.basic.help_define.HelpDefineService",
	HandlerType: (*HelpDefineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrgDefineH",
			Handler:    _HelpDefineService_OrgDefineH_Handler,
		},
		{
			MethodName: "OrgDefineItemH",
			Handler:    _HelpDefineService_OrgDefineItemH_Handler,
		},
		{
			MethodName: "OrgCodeHelpDefineItemH",
			Handler:    _HelpDefineService_OrgCodeHelpDefineItemH_Handler,
		},
		{
			MethodName: "HelpDefineItemAppH",
			Handler:    _HelpDefineService_HelpDefineItemAppH_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lookup/basic/help_define.proto",
}
