// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: users/app/tabs.proto

package tabs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TabsAResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdxNo         int32                  `protobuf:"varint,1,opt,name=IdxNo,proto3" json:"IdxNo,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,2,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,3,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=Key,proto3" json:"Key,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=Path,proto3" json:"Path,omitempty"`
	Order         int32                  `protobuf:"varint,7,opt,name=Order,proto3" json:"Order,omitempty"`
	LangSeq       int32                  `protobuf:"varint,8,opt,name=LangSeq,proto3" json:"LangSeq,omitempty"`
	TabName       string                 `protobuf:"bytes,9,opt,name=TabName,proto3" json:"TabName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabsAResult) Reset() {
	*x = TabsAResult{}
	mi := &file_users_app_tabs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabsAResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabsAResult) ProtoMessage() {}

func (x *TabsAResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_tabs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabsAResult.ProtoReflect.Descriptor instead.
func (*TabsAResult) Descriptor() ([]byte, []int) {
	return file_users_app_tabs_proto_rawDescGZIP(), []int{0}
}

func (x *TabsAResult) GetIdxNo() int32 {
	if x != nil {
		return x.IdxNo
	}
	return 0
}

func (x *TabsAResult) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *TabsAResult) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *TabsAResult) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TabsAResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TabsAResult) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *TabsAResult) GetLangSeq() int32 {
	if x != nil {
		return x.LangSeq
	}
	return 0
}

func (x *TabsAResult) GetTabName() string {
	if x != nil {
		return x.TabName
	}
	return ""
}

type TabsUResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdxNo         int32                  `protobuf:"varint,1,opt,name=IdxNo,proto3" json:"IdxNo,omitempty"`
	IdSeq         string                 `protobuf:"bytes,2,opt,name=IdSeq,proto3" json:"IdSeq,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,3,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=Key,proto3" json:"Key,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=Path,proto3" json:"Path,omitempty"`
	Order         int32                  `protobuf:"varint,7,opt,name=Order,proto3" json:"Order,omitempty"`
	LangSeq       int32                  `protobuf:"varint,8,opt,name=LangSeq,proto3" json:"LangSeq,omitempty"`
	TabName       string                 `protobuf:"bytes,9,opt,name=TabName,proto3" json:"TabName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabsUResult) Reset() {
	*x = TabsUResult{}
	mi := &file_users_app_tabs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabsUResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabsUResult) ProtoMessage() {}

func (x *TabsUResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_tabs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabsUResult.ProtoReflect.Descriptor instead.
func (*TabsUResult) Descriptor() ([]byte, []int) {
	return file_users_app_tabs_proto_rawDescGZIP(), []int{1}
}

func (x *TabsUResult) GetIdxNo() int32 {
	if x != nil {
		return x.IdxNo
	}
	return 0
}

func (x *TabsUResult) GetIdSeq() string {
	if x != nil {
		return x.IdSeq
	}
	return ""
}

func (x *TabsUResult) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *TabsUResult) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TabsUResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TabsUResult) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *TabsUResult) GetLangSeq() int32 {
	if x != nil {
		return x.LangSeq
	}
	return 0
}

func (x *TabsUResult) GetTabName() string {
	if x != nil {
		return x.TabName
	}
	return ""
}

type TabsDResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdSeq         string                 `protobuf:"bytes,1,opt,name=IdSeq,proto3" json:"IdSeq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabsDResult) Reset() {
	*x = TabsDResult{}
	mi := &file_users_app_tabs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabsDResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabsDResult) ProtoMessage() {}

func (x *TabsDResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_tabs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabsDResult.ProtoReflect.Descriptor instead.
func (*TabsDResult) Descriptor() ([]byte, []int) {
	return file_users_app_tabs_proto_rawDescGZIP(), []int{2}
}

func (x *TabsDResult) GetIdSeq() string {
	if x != nil {
		return x.IdSeq
	}
	return ""
}

type TabsQResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyItem1      string                 `protobuf:"bytes,1,opt,name=KeyItem1,proto3" json:"KeyItem1,omitempty"`
	KeyItem2      string                 `protobuf:"bytes,2,opt,name=KeyItem2,proto3" json:"KeyItem2,omitempty"`
	KeyItem3      string                 `protobuf:"bytes,3,opt,name=KeyItem3,proto3" json:"KeyItem3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabsQResult) Reset() {
	*x = TabsQResult{}
	mi := &file_users_app_tabs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabsQResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabsQResult) ProtoMessage() {}

func (x *TabsQResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_tabs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabsQResult.ProtoReflect.Descriptor instead.
func (*TabsQResult) Descriptor() ([]byte, []int) {
	return file_users_app_tabs_proto_rawDescGZIP(), []int{3}
}

func (x *TabsQResult) GetKeyItem1() string {
	if x != nil {
		return x.KeyItem1
	}
	return ""
}

func (x *TabsQResult) GetKeyItem2() string {
	if x != nil {
		return x.KeyItem2
	}
	return ""
}

func (x *TabsQResult) GetKeyItem3() string {
	if x != nil {
		return x.KeyItem3
	}
	return ""
}

type TabsARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*TabsAResult         `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabsARequest) Reset() {
	*x = TabsARequest{}
	mi := &file_users_app_tabs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabsARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabsARequest) ProtoMessage() {}

func (x *TabsARequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_tabs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabsARequest.ProtoReflect.Descriptor instead.
func (*TabsARequest) Descriptor() ([]byte, []int) {
	return file_users_app_tabs_proto_rawDescGZIP(), []int{4}
}

func (x *TabsARequest) GetResult() []*TabsAResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TabsARequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TabsURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*TabsUResult         `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabsURequest) Reset() {
	*x = TabsURequest{}
	mi := &file_users_app_tabs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabsURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabsURequest) ProtoMessage() {}

func (x *TabsURequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_tabs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabsURequest.ProtoReflect.Descriptor instead.
func (*TabsURequest) Descriptor() ([]byte, []int) {
	return file_users_app_tabs_proto_rawDescGZIP(), []int{5}
}

func (x *TabsURequest) GetResult() []*TabsUResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TabsURequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TabsDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*TabsDResult         `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabsDRequest) Reset() {
	*x = TabsDRequest{}
	mi := &file_users_app_tabs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabsDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabsDRequest) ProtoMessage() {}

func (x *TabsDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_tabs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabsDRequest.ProtoReflect.Descriptor instead.
func (*TabsDRequest) Descriptor() ([]byte, []int) {
	return file_users_app_tabs_proto_rawDescGZIP(), []int{6}
}

func (x *TabsDRequest) GetResult() []*TabsDResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TabsDRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TabsQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *TabsQResult           `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabsQRequest) Reset() {
	*x = TabsQRequest{}
	mi := &file_users_app_tabs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabsQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabsQRequest) ProtoMessage() {}

func (x *TabsQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_tabs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabsQRequest.ProtoReflect.Descriptor instead.
func (*TabsQRequest) Descriptor() ([]byte, []int) {
	return file_users_app_tabs_proto_rawDescGZIP(), []int{7}
}

func (x *TabsQRequest) GetResult() *TabsQResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TabsQRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Page          string                 `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_users_app_tabs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_users_app_tabs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_users_app_tabs_proto_rawDescGZIP(), []int{8}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Response) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

var File_users_app_tabs_proto protoreflect.FileDescriptor

const file_users_app_tabs_proto_rawDesc = "" +
	"\n" +
	"\x14users/app/tabs.proto\x12\x0eusers.app.tabs\"\xcf\x01\n" +
	"\vTabsAResult\x12\x14\n" +
	"\x05IdxNo\x18\x01 \x01(\x05R\x05IdxNo\x12\x1c\n" +
	"\tCreatedBy\x18\x02 \x01(\tR\tCreatedBy\x12\x1c\n" +
	"\tUpdatedBy\x18\x03 \x01(\tR\tUpdatedBy\x12\x10\n" +
	"\x03Key\x18\x04 \x01(\tR\x03Key\x12\x12\n" +
	"\x04Path\x18\x05 \x01(\tR\x04Path\x12\x14\n" +
	"\x05Order\x18\a \x01(\x05R\x05Order\x12\x18\n" +
	"\aLangSeq\x18\b \x01(\x05R\aLangSeq\x12\x18\n" +
	"\aTabName\x18\t \x01(\tR\aTabName\"\xc7\x01\n" +
	"\vTabsUResult\x12\x14\n" +
	"\x05IdxNo\x18\x01 \x01(\x05R\x05IdxNo\x12\x14\n" +
	"\x05IdSeq\x18\x02 \x01(\tR\x05IdSeq\x12\x1c\n" +
	"\tUpdatedBy\x18\x03 \x01(\tR\tUpdatedBy\x12\x10\n" +
	"\x03Key\x18\x04 \x01(\tR\x03Key\x12\x12\n" +
	"\x04Path\x18\x05 \x01(\tR\x04Path\x12\x14\n" +
	"\x05Order\x18\a \x01(\x05R\x05Order\x12\x18\n" +
	"\aLangSeq\x18\b \x01(\x05R\aLangSeq\x12\x18\n" +
	"\aTabName\x18\t \x01(\tR\aTabName\"#\n" +
	"\vTabsDResult\x12\x14\n" +
	"\x05IdSeq\x18\x01 \x01(\tR\x05IdSeq\"a\n" +
	"\vTabsQResult\x12\x1a\n" +
	"\bKeyItem1\x18\x01 \x01(\tR\bKeyItem1\x12\x1a\n" +
	"\bKeyItem2\x18\x02 \x01(\tR\bKeyItem2\x12\x1a\n" +
	"\bKeyItem3\x18\x03 \x01(\tR\bKeyItem3\"\xc8\x01\n" +
	"\fTabsARequest\x123\n" +
	"\x06result\x18\x01 \x03(\v2\x1b.users.app.tabs.TabsAResultR\x06result\x12F\n" +
	"\bmetadata\x18\x02 \x03(\v2*.users.app.tabs.TabsARequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc8\x01\n" +
	"\fTabsURequest\x123\n" +
	"\x06result\x18\x01 \x03(\v2\x1b.users.app.tabs.TabsUResultR\x06result\x12F\n" +
	"\bmetadata\x18\x02 \x03(\v2*.users.app.tabs.TabsURequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc8\x01\n" +
	"\fTabsDRequest\x123\n" +
	"\x06result\x18\x01 \x03(\v2\x1b.users.app.tabs.TabsDResultR\x06result\x12F\n" +
	"\bmetadata\x18\x02 \x03(\v2*.users.app.tabs.TabsDRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc8\x01\n" +
	"\fTabsQRequest\x123\n" +
	"\x06result\x18\x01 \x01(\v2\x1b.users.app.tabs.TabsQResultR\x06result\x12F\n" +
	"\bmetadata\x18\x02 \x03(\v2*.users.app.tabs.TabsQRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x12\n" +
	"\x04page\x18\x04 \x01(\tR\x04page2\x91\x02\n" +
	"\vTabsService\x12?\n" +
	"\x05TabsA\x12\x1c.users.app.tabs.TabsARequest\x1a\x18.users.app.tabs.Response\x12?\n" +
	"\x05TabsU\x12\x1c.users.app.tabs.TabsURequest\x1a\x18.users.app.tabs.Response\x12?\n" +
	"\x05TabsD\x12\x1c.users.app.tabs.TabsDRequest\x1a\x18.users.app.tabs.Response\x12?\n" +
	"\x05TabsQ\x12\x1c.users.app.tabs.TabsQRequest\x1a\x18.users.app.tabs.ResponseB\"Z server-core/proto/users/app/tabsb\x06proto3"

var (
	file_users_app_tabs_proto_rawDescOnce sync.Once
	file_users_app_tabs_proto_rawDescData []byte
)

func file_users_app_tabs_proto_rawDescGZIP() []byte {
	file_users_app_tabs_proto_rawDescOnce.Do(func() {
		file_users_app_tabs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_app_tabs_proto_rawDesc), len(file_users_app_tabs_proto_rawDesc)))
	})
	return file_users_app_tabs_proto_rawDescData
}

var file_users_app_tabs_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_users_app_tabs_proto_goTypes = []any{
	(*TabsAResult)(nil),  // 0: users.app.tabs.TabsAResult
	(*TabsUResult)(nil),  // 1: users.app.tabs.TabsUResult
	(*TabsDResult)(nil),  // 2: users.app.tabs.TabsDResult
	(*TabsQResult)(nil),  // 3: users.app.tabs.TabsQResult
	(*TabsARequest)(nil), // 4: users.app.tabs.TabsARequest
	(*TabsURequest)(nil), // 5: users.app.tabs.TabsURequest
	(*TabsDRequest)(nil), // 6: users.app.tabs.TabsDRequest
	(*TabsQRequest)(nil), // 7: users.app.tabs.TabsQRequest
	(*Response)(nil),     // 8: users.app.tabs.Response
	nil,                  // 9: users.app.tabs.TabsARequest.MetadataEntry
	nil,                  // 10: users.app.tabs.TabsURequest.MetadataEntry
	nil,                  // 11: users.app.tabs.TabsDRequest.MetadataEntry
	nil,                  // 12: users.app.tabs.TabsQRequest.MetadataEntry
}
var file_users_app_tabs_proto_depIdxs = []int32{
	0,  // 0: users.app.tabs.TabsARequest.result:type_name -> users.app.tabs.TabsAResult
	9,  // 1: users.app.tabs.TabsARequest.metadata:type_name -> users.app.tabs.TabsARequest.MetadataEntry
	1,  // 2: users.app.tabs.TabsURequest.result:type_name -> users.app.tabs.TabsUResult
	10, // 3: users.app.tabs.TabsURequest.metadata:type_name -> users.app.tabs.TabsURequest.MetadataEntry
	2,  // 4: users.app.tabs.TabsDRequest.result:type_name -> users.app.tabs.TabsDResult
	11, // 5: users.app.tabs.TabsDRequest.metadata:type_name -> users.app.tabs.TabsDRequest.MetadataEntry
	3,  // 6: users.app.tabs.TabsQRequest.result:type_name -> users.app.tabs.TabsQResult
	12, // 7: users.app.tabs.TabsQRequest.metadata:type_name -> users.app.tabs.TabsQRequest.MetadataEntry
	4,  // 8: users.app.tabs.TabsService.TabsA:input_type -> users.app.tabs.TabsARequest
	5,  // 9: users.app.tabs.TabsService.TabsU:input_type -> users.app.tabs.TabsURequest
	6,  // 10: users.app.tabs.TabsService.TabsD:input_type -> users.app.tabs.TabsDRequest
	7,  // 11: users.app.tabs.TabsService.TabsQ:input_type -> users.app.tabs.TabsQRequest
	8,  // 12: users.app.tabs.TabsService.TabsA:output_type -> users.app.tabs.Response
	8,  // 13: users.app.tabs.TabsService.TabsU:output_type -> users.app.tabs.Response
	8,  // 14: users.app.tabs.TabsService.TabsD:output_type -> users.app.tabs.Response
	8,  // 15: users.app.tabs.TabsService.TabsQ:output_type -> users.app.tabs.Response
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_users_app_tabs_proto_init() }
func file_users_app_tabs_proto_init() {
	if File_users_app_tabs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_app_tabs_proto_rawDesc), len(file_users_app_tabs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_app_tabs_proto_goTypes,
		DependencyIndexes: file_users_app_tabs_proto_depIdxs,
		MessageInfos:      file_users_app_tabs_proto_msgTypes,
	}.Build()
	File_users_app_tabs_proto = out.File
	file_users_app_tabs_proto_goTypes = nil
	file_users_app_tabs_proto_depIdxs = nil
}
