// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: users/technique/tbl_grp_perm_role.proto

package tbl_grp_perm_role

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TblGrpPermRoleService_TblGrpPermRoleA_FullMethodName = "/users.technique.tbl_grp_perm_role.TblGrpPermRoleService/TblGrpPermRoleA"
	TblGrpPermRoleService_TblGrpPermRoleU_FullMethodName = "/users.technique.tbl_grp_perm_role.TblGrpPermRoleService/TblGrpPermRoleU"
	TblGrpPermRoleService_TblGrpPermRoleD_FullMethodName = "/users.technique.tbl_grp_perm_role.TblGrpPermRoleService/TblGrpPermRoleD"
	TblGrpPermRoleService_TblGrpPermRoleQ_FullMethodName = "/users.technique.tbl_grp_perm_role.TblGrpPermRoleService/TblGrpPermRoleQ"
)

// TblGrpPermRoleServiceClient is the client API for TblGrpPermRoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TblGrpPermRoleServiceClient interface {
	TblGrpPermRoleA(ctx context.Context, in *TblGrpPermRoleARequest, opts ...grpc.CallOption) (*Response, error)
	TblGrpPermRoleU(ctx context.Context, in *TblGrpPermRoleURequest, opts ...grpc.CallOption) (*Response, error)
	TblGrpPermRoleD(ctx context.Context, in *TblGrpPermRoleDRequest, opts ...grpc.CallOption) (*Response, error)
	TblGrpPermRoleQ(ctx context.Context, in *TblGrpPermRoleQRequest, opts ...grpc.CallOption) (*Response, error)
}

type tblGrpPermRoleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTblGrpPermRoleServiceClient(cc grpc.ClientConnInterface) TblGrpPermRoleServiceClient {
	return &tblGrpPermRoleServiceClient{cc}
}

func (c *tblGrpPermRoleServiceClient) TblGrpPermRoleA(ctx context.Context, in *TblGrpPermRoleARequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, TblGrpPermRoleService_TblGrpPermRoleA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tblGrpPermRoleServiceClient) TblGrpPermRoleU(ctx context.Context, in *TblGrpPermRoleURequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, TblGrpPermRoleService_TblGrpPermRoleU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tblGrpPermRoleServiceClient) TblGrpPermRoleD(ctx context.Context, in *TblGrpPermRoleDRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, TblGrpPermRoleService_TblGrpPermRoleD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tblGrpPermRoleServiceClient) TblGrpPermRoleQ(ctx context.Context, in *TblGrpPermRoleQRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, TblGrpPermRoleService_TblGrpPermRoleQ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TblGrpPermRoleServiceServer is the server API for TblGrpPermRoleService service.
// All implementations must embed UnimplementedTblGrpPermRoleServiceServer
// for forward compatibility.
type TblGrpPermRoleServiceServer interface {
	TblGrpPermRoleA(context.Context, *TblGrpPermRoleARequest) (*Response, error)
	TblGrpPermRoleU(context.Context, *TblGrpPermRoleURequest) (*Response, error)
	TblGrpPermRoleD(context.Context, *TblGrpPermRoleDRequest) (*Response, error)
	TblGrpPermRoleQ(context.Context, *TblGrpPermRoleQRequest) (*Response, error)
	mustEmbedUnimplementedTblGrpPermRoleServiceServer()
}

// UnimplementedTblGrpPermRoleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTblGrpPermRoleServiceServer struct{}

func (UnimplementedTblGrpPermRoleServiceServer) TblGrpPermRoleA(context.Context, *TblGrpPermRoleARequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method TblGrpPermRoleA not implemented")
}
func (UnimplementedTblGrpPermRoleServiceServer) TblGrpPermRoleU(context.Context, *TblGrpPermRoleURequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method TblGrpPermRoleU not implemented")
}
func (UnimplementedTblGrpPermRoleServiceServer) TblGrpPermRoleD(context.Context, *TblGrpPermRoleDRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method TblGrpPermRoleD not implemented")
}
func (UnimplementedTblGrpPermRoleServiceServer) TblGrpPermRoleQ(context.Context, *TblGrpPermRoleQRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method TblGrpPermRoleQ not implemented")
}
func (UnimplementedTblGrpPermRoleServiceServer) mustEmbedUnimplementedTblGrpPermRoleServiceServer() {}
func (UnimplementedTblGrpPermRoleServiceServer) testEmbeddedByValue()                               {}

// UnsafeTblGrpPermRoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TblGrpPermRoleServiceServer will
// result in compilation errors.
type UnsafeTblGrpPermRoleServiceServer interface {
	mustEmbedUnimplementedTblGrpPermRoleServiceServer()
}

func RegisterTblGrpPermRoleServiceServer(s grpc.ServiceRegistrar, srv TblGrpPermRoleServiceServer) {
	// If the following call panics, it indicates UnimplementedTblGrpPermRoleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TblGrpPermRoleService_ServiceDesc, srv)
}

func _TblGrpPermRoleService_TblGrpPermRoleA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TblGrpPermRoleARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TblGrpPermRoleServiceServer).TblGrpPermRoleA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TblGrpPermRoleService_TblGrpPermRoleA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TblGrpPermRoleServiceServer).TblGrpPermRoleA(ctx, req.(*TblGrpPermRoleARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TblGrpPermRoleService_TblGrpPermRoleU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TblGrpPermRoleURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TblGrpPermRoleServiceServer).TblGrpPermRoleU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TblGrpPermRoleService_TblGrpPermRoleU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TblGrpPermRoleServiceServer).TblGrpPermRoleU(ctx, req.(*TblGrpPermRoleURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TblGrpPermRoleService_TblGrpPermRoleD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TblGrpPermRoleDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TblGrpPermRoleServiceServer).TblGrpPermRoleD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TblGrpPermRoleService_TblGrpPermRoleD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TblGrpPermRoleServiceServer).TblGrpPermRoleD(ctx, req.(*TblGrpPermRoleDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TblGrpPermRoleService_TblGrpPermRoleQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TblGrpPermRoleQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TblGrpPermRoleServiceServer).TblGrpPermRoleQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TblGrpPermRoleService_TblGrpPermRoleQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TblGrpPermRoleServiceServer).TblGrpPermRoleQ(ctx, req.(*TblGrpPermRoleQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TblGrpPermRoleService_ServiceDesc is the grpc.ServiceDesc for TblGrpPermRoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TblGrpPermRoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.technique.tbl_grp_perm_role.TblGrpPermRoleService",
	HandlerType: (*TblGrpPermRoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TblGrpPermRoleA",
			Handler:    _TblGrpPermRoleService_TblGrpPermRoleA_Handler,
		},
		{
			MethodName: "TblGrpPermRoleU",
			Handler:    _TblGrpPermRoleService_TblGrpPermRoleU_Handler,
		},
		{
			MethodName: "TblGrpPermRoleD",
			Handler:    _TblGrpPermRoleService_TblGrpPermRoleD_Handler,
		},
		{
			MethodName: "TblGrpPermRoleQ",
			Handler:    _TblGrpPermRoleService_TblGrpPermRoleQ_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users/technique/tbl_grp_perm_role.proto",
}
