// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: users/roles/root_menu.proto

package root_menu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RootMenuAResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdxNo         int32                  `protobuf:"varint,1,opt,name=IdxNo,proto3" json:"IdxNo,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=Label,proto3" json:"Label,omitempty"`
	Link          string                 `protobuf:"bytes,4,opt,name=Link,proto3" json:"Link,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Utilities     bool                   `protobuf:"varint,6,opt,name=Utilities,proto3" json:"Utilities,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,7,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,8,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	RowVersion    int64                  `protobuf:"varint,9,opt,name=RowVersion,proto3" json:"RowVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootMenuAResult) Reset() {
	*x = RootMenuAResult{}
	mi := &file_users_roles_root_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootMenuAResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootMenuAResult) ProtoMessage() {}

func (x *RootMenuAResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_roles_root_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootMenuAResult.ProtoReflect.Descriptor instead.
func (*RootMenuAResult) Descriptor() ([]byte, []int) {
	return file_users_roles_root_menu_proto_rawDescGZIP(), []int{0}
}

func (x *RootMenuAResult) GetIdxNo() int32 {
	if x != nil {
		return x.IdxNo
	}
	return 0
}

func (x *RootMenuAResult) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RootMenuAResult) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *RootMenuAResult) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *RootMenuAResult) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *RootMenuAResult) GetUtilities() bool {
	if x != nil {
		return x.Utilities
	}
	return false
}

func (x *RootMenuAResult) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *RootMenuAResult) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *RootMenuAResult) GetRowVersion() int64 {
	if x != nil {
		return x.RowVersion
	}
	return 0
}

type RootMenuUResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdxNo         int32                  `protobuf:"varint,1,opt,name=IdxNo,proto3" json:"IdxNo,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=Label,proto3" json:"Label,omitempty"`
	Link          string                 `protobuf:"bytes,4,opt,name=Link,proto3" json:"Link,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Id            int32                  `protobuf:"varint,6,opt,name=Id,proto3" json:"Id,omitempty"`
	Utilities     bool                   `protobuf:"varint,7,opt,name=Utilities,proto3" json:"Utilities,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,9,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	RowVersion    int64                  `protobuf:"varint,10,opt,name=RowVersion,proto3" json:"RowVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootMenuUResult) Reset() {
	*x = RootMenuUResult{}
	mi := &file_users_roles_root_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootMenuUResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootMenuUResult) ProtoMessage() {}

func (x *RootMenuUResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_roles_root_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootMenuUResult.ProtoReflect.Descriptor instead.
func (*RootMenuUResult) Descriptor() ([]byte, []int) {
	return file_users_roles_root_menu_proto_rawDescGZIP(), []int{1}
}

func (x *RootMenuUResult) GetIdxNo() int32 {
	if x != nil {
		return x.IdxNo
	}
	return 0
}

func (x *RootMenuUResult) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RootMenuUResult) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *RootMenuUResult) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *RootMenuUResult) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *RootMenuUResult) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RootMenuUResult) GetUtilities() bool {
	if x != nil {
		return x.Utilities
	}
	return false
}

func (x *RootMenuUResult) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RootMenuUResult) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *RootMenuUResult) GetRowVersion() int64 {
	if x != nil {
		return x.RowVersion
	}
	return 0
}

type RootMenuDResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	RowVersion    int64                  `protobuf:"varint,2,opt,name=RowVersion,proto3" json:"RowVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootMenuDResult) Reset() {
	*x = RootMenuDResult{}
	mi := &file_users_roles_root_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootMenuDResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootMenuDResult) ProtoMessage() {}

func (x *RootMenuDResult) ProtoReflect() protoreflect.Message {
	mi := &file_users_roles_root_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootMenuDResult.ProtoReflect.Descriptor instead.
func (*RootMenuDResult) Descriptor() ([]byte, []int) {
	return file_users_roles_root_menu_proto_rawDescGZIP(), []int{2}
}

func (x *RootMenuDResult) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RootMenuDResult) GetRowVersion() int64 {
	if x != nil {
		return x.RowVersion
	}
	return 0
}

type RootMenuARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*RootMenuAResult     `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootMenuARequest) Reset() {
	*x = RootMenuARequest{}
	mi := &file_users_roles_root_menu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootMenuARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootMenuARequest) ProtoMessage() {}

func (x *RootMenuARequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_roles_root_menu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootMenuARequest.ProtoReflect.Descriptor instead.
func (*RootMenuARequest) Descriptor() ([]byte, []int) {
	return file_users_roles_root_menu_proto_rawDescGZIP(), []int{3}
}

func (x *RootMenuARequest) GetResult() []*RootMenuAResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RootMenuARequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RootMenuURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*RootMenuUResult     `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootMenuURequest) Reset() {
	*x = RootMenuURequest{}
	mi := &file_users_roles_root_menu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootMenuURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootMenuURequest) ProtoMessage() {}

func (x *RootMenuURequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_roles_root_menu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootMenuURequest.ProtoReflect.Descriptor instead.
func (*RootMenuURequest) Descriptor() ([]byte, []int) {
	return file_users_roles_root_menu_proto_rawDescGZIP(), []int{4}
}

func (x *RootMenuURequest) GetResult() []*RootMenuUResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RootMenuURequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RootMenuDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*RootMenuDResult     `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootMenuDRequest) Reset() {
	*x = RootMenuDRequest{}
	mi := &file_users_roles_root_menu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootMenuDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootMenuDRequest) ProtoMessage() {}

func (x *RootMenuDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_roles_root_menu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootMenuDRequest.ProtoReflect.Descriptor instead.
func (*RootMenuDRequest) Descriptor() ([]byte, []int) {
	return file_users_roles_root_menu_proto_rawDescGZIP(), []int{5}
}

func (x *RootMenuDRequest) GetResult() []*RootMenuDResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RootMenuDRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RootMenuQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        map[string]string      `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootMenuQRequest) Reset() {
	*x = RootMenuQRequest{}
	mi := &file_users_roles_root_menu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootMenuQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootMenuQRequest) ProtoMessage() {}

func (x *RootMenuQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_roles_root_menu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootMenuQRequest.ProtoReflect.Descriptor instead.
func (*RootMenuQRequest) Descriptor() ([]byte, []int) {
	return file_users_roles_root_menu_proto_rawDescGZIP(), []int{6}
}

func (x *RootMenuQRequest) GetResult() map[string]string {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RootMenuQRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ErrorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_users_roles_root_menu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_users_roles_root_menu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_users_roles_root_menu_proto_rawDescGZIP(), []int{7}
}

func (x *ErrorInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Error         *ErrorInfo             `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Page          string                 `protobuf:"bytes,5,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_users_roles_root_menu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_users_roles_root_menu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_users_roles_root_menu_proto_rawDescGZIP(), []int{8}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Response) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Response) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

var File_users_roles_root_menu_proto protoreflect.FileDescriptor

const file_users_roles_root_menu_proto_rawDesc = "" +
	"\n" +
	"\x1busers/roles/root_menu.proto\x12\x0froles.root_menu\"\xf1\x01\n" +
	"\x0fRootMenuAResult\x12\x14\n" +
	"\x05IdxNo\x18\x01 \x01(\x05R\x05IdxNo\x12\x10\n" +
	"\x03Key\x18\x02 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Label\x18\x03 \x01(\tR\x05Label\x12\x12\n" +
	"\x04Link\x18\x04 \x01(\tR\x04Link\x12\x12\n" +
	"\x04Icon\x18\x05 \x01(\tR\x04Icon\x12\x1c\n" +
	"\tUtilities\x18\x06 \x01(\bR\tUtilities\x12\x1c\n" +
	"\tCreatedBy\x18\a \x01(\tR\tCreatedBy\x12\x1c\n" +
	"\tUpdatedBy\x18\b \x01(\tR\tUpdatedBy\x12\x1e\n" +
	"\n" +
	"RowVersion\x18\t \x01(\x03R\n" +
	"RowVersion\"\x81\x02\n" +
	"\x0fRootMenuUResult\x12\x14\n" +
	"\x05IdxNo\x18\x01 \x01(\x05R\x05IdxNo\x12\x10\n" +
	"\x03Key\x18\x02 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Label\x18\x03 \x01(\tR\x05Label\x12\x12\n" +
	"\x04Link\x18\x04 \x01(\tR\x04Link\x12\x12\n" +
	"\x04Icon\x18\x05 \x01(\tR\x04Icon\x12\x0e\n" +
	"\x02Id\x18\x06 \x01(\x05R\x02Id\x12\x1c\n" +
	"\tUtilities\x18\a \x01(\bR\tUtilities\x12\x1c\n" +
	"\tUpdatedAt\x18\b \x01(\tR\tUpdatedAt\x12\x1c\n" +
	"\tUpdatedBy\x18\t \x01(\tR\tUpdatedBy\x12\x1e\n" +
	"\n" +
	"RowVersion\x18\n" +
	" \x01(\x03R\n" +
	"RowVersion\"A\n" +
	"\x0fRootMenuDResult\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x1e\n" +
	"\n" +
	"RowVersion\x18\x02 \x01(\x03R\n" +
	"RowVersion\"\xd6\x01\n" +
	"\x10RootMenuARequest\x128\n" +
	"\x06result\x18\x01 \x03(\v2 .roles.root_menu.RootMenuAResultR\x06result\x12K\n" +
	"\bmetadata\x18\x02 \x03(\v2/.roles.root_menu.RootMenuARequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x01\n" +
	"\x10RootMenuURequest\x128\n" +
	"\x06result\x18\x01 \x03(\v2 .roles.root_menu.RootMenuUResultR\x06result\x12K\n" +
	"\bmetadata\x18\x02 \x03(\v2/.roles.root_menu.RootMenuURequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x01\n" +
	"\x10RootMenuDRequest\x128\n" +
	"\x06result\x18\x01 \x03(\v2 .roles.root_menu.RootMenuDResultR\x06result\x12K\n" +
	"\bmetadata\x18\x02 \x03(\v2/.roles.root_menu.RootMenuDRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x02\n" +
	"\x10RootMenuQRequest\x12E\n" +
	"\x06result\x18\x01 \x03(\v2-.roles.root_menu.RootMenuQRequest.ResultEntryR\x06result\x12K\n" +
	"\bmetadata\x18\x02 \x03(\v2/.roles.root_menu.RootMenuQRequest.MetadataEntryR\bmetadata\x1a9\n" +
	"\vResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\tErrorInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x98\x01\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x120\n" +
	"\x05error\x18\x04 \x01(\v2\x1a.roles.root_menu.ErrorInfoR\x05error\x12\x12\n" +
	"\x04page\x18\x05 \x01(\tR\x04page2\xbd\x02\n" +
	"\x0fRootMenuService\x12I\n" +
	"\tRootMenuA\x12!.roles.root_menu.RootMenuARequest\x1a\x19.roles.root_menu.Response\x12I\n" +
	"\tRootMenuU\x12!.roles.root_menu.RootMenuURequest\x1a\x19.roles.root_menu.Response\x12I\n" +
	"\tRootMenuD\x12!.roles.root_menu.RootMenuDRequest\x1a\x19.roles.root_menu.Response\x12I\n" +
	"\tRootMenuQ\x12!.roles.root_menu.RootMenuQRequest\x1a\x19.roles.root_menu.ResponseB)Z'server-core/proto/users/roles/root_menub\x06proto3"

var (
	file_users_roles_root_menu_proto_rawDescOnce sync.Once
	file_users_roles_root_menu_proto_rawDescData []byte
)

func file_users_roles_root_menu_proto_rawDescGZIP() []byte {
	file_users_roles_root_menu_proto_rawDescOnce.Do(func() {
		file_users_roles_root_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_roles_root_menu_proto_rawDesc), len(file_users_roles_root_menu_proto_rawDesc)))
	})
	return file_users_roles_root_menu_proto_rawDescData
}

var file_users_roles_root_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_users_roles_root_menu_proto_goTypes = []any{
	(*RootMenuAResult)(nil),  // 0: roles.root_menu.RootMenuAResult
	(*RootMenuUResult)(nil),  // 1: roles.root_menu.RootMenuUResult
	(*RootMenuDResult)(nil),  // 2: roles.root_menu.RootMenuDResult
	(*RootMenuARequest)(nil), // 3: roles.root_menu.RootMenuARequest
	(*RootMenuURequest)(nil), // 4: roles.root_menu.RootMenuURequest
	(*RootMenuDRequest)(nil), // 5: roles.root_menu.RootMenuDRequest
	(*RootMenuQRequest)(nil), // 6: roles.root_menu.RootMenuQRequest
	(*ErrorInfo)(nil),        // 7: roles.root_menu.ErrorInfo
	(*Response)(nil),         // 8: roles.root_menu.Response
	nil,                      // 9: roles.root_menu.RootMenuARequest.MetadataEntry
	nil,                      // 10: roles.root_menu.RootMenuURequest.MetadataEntry
	nil,                      // 11: roles.root_menu.RootMenuDRequest.MetadataEntry
	nil,                      // 12: roles.root_menu.RootMenuQRequest.ResultEntry
	nil,                      // 13: roles.root_menu.RootMenuQRequest.MetadataEntry
}
var file_users_roles_root_menu_proto_depIdxs = []int32{
	0,  // 0: roles.root_menu.RootMenuARequest.result:type_name -> roles.root_menu.RootMenuAResult
	9,  // 1: roles.root_menu.RootMenuARequest.metadata:type_name -> roles.root_menu.RootMenuARequest.MetadataEntry
	1,  // 2: roles.root_menu.RootMenuURequest.result:type_name -> roles.root_menu.RootMenuUResult
	10, // 3: roles.root_menu.RootMenuURequest.metadata:type_name -> roles.root_menu.RootMenuURequest.MetadataEntry
	2,  // 4: roles.root_menu.RootMenuDRequest.result:type_name -> roles.root_menu.RootMenuDResult
	11, // 5: roles.root_menu.RootMenuDRequest.metadata:type_name -> roles.root_menu.RootMenuDRequest.MetadataEntry
	12, // 6: roles.root_menu.RootMenuQRequest.result:type_name -> roles.root_menu.RootMenuQRequest.ResultEntry
	13, // 7: roles.root_menu.RootMenuQRequest.metadata:type_name -> roles.root_menu.RootMenuQRequest.MetadataEntry
	7,  // 8: roles.root_menu.Response.error:type_name -> roles.root_menu.ErrorInfo
	3,  // 9: roles.root_menu.RootMenuService.RootMenuA:input_type -> roles.root_menu.RootMenuARequest
	4,  // 10: roles.root_menu.RootMenuService.RootMenuU:input_type -> roles.root_menu.RootMenuURequest
	5,  // 11: roles.root_menu.RootMenuService.RootMenuD:input_type -> roles.root_menu.RootMenuDRequest
	6,  // 12: roles.root_menu.RootMenuService.RootMenuQ:input_type -> roles.root_menu.RootMenuQRequest
	8,  // 13: roles.root_menu.RootMenuService.RootMenuA:output_type -> roles.root_menu.Response
	8,  // 14: roles.root_menu.RootMenuService.RootMenuU:output_type -> roles.root_menu.Response
	8,  // 15: roles.root_menu.RootMenuService.RootMenuD:output_type -> roles.root_menu.Response
	8,  // 16: roles.root_menu.RootMenuService.RootMenuQ:output_type -> roles.root_menu.Response
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_users_roles_root_menu_proto_init() }
func file_users_roles_root_menu_proto_init() {
	if File_users_roles_root_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_roles_root_menu_proto_rawDesc), len(file_users_roles_root_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_roles_root_menu_proto_goTypes,
		DependencyIndexes: file_users_roles_root_menu_proto_depIdxs,
		MessageInfos:      file_users_roles_root_menu_proto_msgTypes,
	}.Build()
	File_users_roles_root_menu_proto = out.File
	file_users_roles_root_menu_proto_goTypes = nil
	file_users_roles_root_menu_proto_depIdxs = nil
}
